<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="edit_transaction">
</div>
</div> 

 <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            </div>
   </div>

 <div class="row">
     <div class="col-md-1 grid-spacing">
     <button class="btn btn-primary" id="income" type="button">Add Income</button>
     </div>
     <div class="col-md-1 grid-spacing">
     <button class="btn btn-primary" id="expense" type="button">Add Expense</button>
     </div>
</div>


   <div class="row" id="add_income" style="display:none;">


                        <div class="col-md-12 widget-module">

                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Income Transaction</h4>

                                </div>

                                <div class="widget-container">
                                    <form class="form-horizontal" id="add-income" method="post">

                                      <div class="row">
                                        <div class="form-group">
                                        <div class="col-lg-2">
                                            <input type="text" class="form-control date-pick" name="date" placeholder="Date" id="date" autocomplete='off'>
                                                <input type="hidden" name="action" value="income">

                                        </div>
                                        <div class="col-lg-4">
                                             <input type="text" class="form-control" name="description" id="description" placeholder="Enter Description" autocomplete='off'>
                                        </div>
                                        <div class="col-lg-2">
                                             <input type="text" class="form-control" name="amount" id="amount" placeholder="Amount" autocomplete='off'>
                                        </div>
                                        <div class="col-lg-2">
                                            <select class="select2" name="category" name="category">
                                                    <option value="">Select Category</option>
                                                    <?php
                                                    $inc = 0;
                                                    $exp = 0;
                                                    foreach ($this->systemAccount as  $system) {
                                                    ?>
                                                      <optgroup label="<?php echo ucfirst($system['account']); ?>">
                                                    <?php
                                                       foreach ($this->nonPayAccounts as  $nonPay) {
                                                        if($system['id']==4 &&$inc==0) {
                                                          foreach ($this->uncategoryAccounts as  $uncategory) { if($uncategory['did']=='i1') {
                                                               $inc++;
                                                    ?>
                                                       <option value="<?php echo $uncategory['did']; ?>"><?php echo $uncategory['name']; ?></option>
                                                    <?php
                                                              }
                                                          }
                                                        } else if($system['id']==5 &&$exp==0) {
                                                          foreach ($this->uncategoryAccounts as  $uncategory) { if($uncategory['did']=='e1') {
                                                              $exp++;
                                                    ?>
                                                      <option value="<?php echo $uncategory['did']; ?>"><?php echo $uncategory['name']; ?></option>
                                                    <?php
                                                           } 
                                                          }
                                                        } else if($system['id']==$nonPay['fksys_id'] && $nonPay['delete_status']==1  && $nonPay['payment_status']==0) {
                                                     ?>
                                                          <option value="<?php echo $nonPay['id']; ?>"><?php echo ucfirst($nonPay['name']); ?></option>
                                                     <?php 
                                                          }
                                                       }
                                                      ?>
                                                        </optgroup>
                                                     <?php 
                                                     }
                                                     ?>                   
                                                    </select>
                                        </div>
                                        <div class="col-lg-2">
                                            <select class="select2" name="account" id="account">
                                                    <option value="">Select Account</option>
                                                     <?php
                                                    foreach ($this->systemAccount as  $system) {
                                                    ?>
                                                      <optgroup label="<?php echo ucfirst($system['account']); ?>">
                                                    <?php
                                                       foreach ($this->payAccounts as  $pay) {
                                                        if($system['id']==$pay['fksys_id'] && $pay['delete_status']==1  && $pay['payment_status']==1) {
                                                     ?>
                                                          <option value="<?php echo $pay['id']; ?>"><?php echo ucfirst($pay['name']); ?></option>
                                                     <?php 
                                                          }
                                                       }
                                                      ?>
                                                        </optgroup>
                                                     <?php 
                                                     }
                                                     ?>    
                                                    </select>
                                        </div>
                                    </div>
                                    </div>


                                    <div class="form-group" id="viewCustomer" style="display:none;">

                                      <div class="col-md-offset-6">

                                            <div class="col-lg-2">
                                            <select class="select2" name="customer" id="customer">
                                                    <option value="">Select Customer</option>
                                                     <?php
                                                       foreach ($this->customersList as  $customer) {
                                                        if($customer['delete_status']==1) {
                                                     ?>
                                                          <option value="<?php echo $customer['id']; ?>"><?php echo ucfirst($customer['name']); ?></option>
                                                     <?php 
                                                        }
                                                       }
                                                      ?>
                                                        
                                                    </select>
                                        </div>

                                      </div>

                                    </div>

                                  <div class="form-group" id="splitCustomer" style="display:none;">
                                    <table id="myTable" class="order-list">
                                        <thead>
                                            <tr>
                                                <td>Name</td>
                                                <td>Amount</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <input type="text" name="name1"  class="form-control" />
                                                </td>
                                                <td>
                                                    <input type="text" name="price1"   class="form-control"/>
                                                </td>
                                                <td><a class="deleteRow"></a>

                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <input type="text" name="name2"  class="form-control"/>
                                                </td>
                                                <td>
                                                    <input type="text" name="price2"  class="form-control"/>
                                                </td>
                                                <td><a class="deleteRow"></a>

                                                </td>
                                            </tr>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <td colspan="5" style="text-align: left;">
                                                    <input type="button" class="btn btn-info" id="addrow" value="Add Row" />
                                                   <strong> <a href="javascript:void(0)" id="cancel" onclick="return cancelSplit('customer');">Cancel</a></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan=""><strong>Available: <span id="grandtotal"></span></strong>
                                                <input type="hidden" name="split_amount" id="split_amount">
                                                <input type="hidden" name="split" id="split" value="">
                                                <input type="hidden" name="split_count" id="split_count" value="">

                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                  </div>

                                    <div class="form-group view_more">
                                     <div class="col-md-2">
                                      <strong><a href="javascript:void(0)"  onclick="return viewSplit('customer');">Split Transaction</a></strong>
                                      </div>
                                      <div class="col-md-offset-6">
                                          <strong><a href="javascript:void(0)" id="view_details" onclick="return viewMore('customer');">More Details</a></strong>
                                      </div>
                                    </div>




                                    <div class="form-group">
                                    <div class="col-lg-3">
                                                <div class="form-actions">
                                                    <input type="submit" name="submit" class="btn btn-primary" value="Save" />
                                                    <button type="reset" class="btn">Cancel</button>
                                                </div>
                                            </div>
                                  </div>
                                       
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>



 <div class="row" id="add_expense" style="display:none;">
                        <div class="col-md-12 widget-module">
                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Expense Transaction</h4>

                                </div>
                                <div class="widget-container">
                                    <form class="form-horizontal" id="add-expense" method="post">
                                        <div class="row">
                                        <div class="form-group">
                                        <div class="col-lg-2">
                                            <input type="text" class="form-control date-pick" name="date" placeholder="Date" id="date" autocomplete='off'>
                                                <input type="hidden" name="action" value="expense">
                                        </div>
                                        <div class="col-lg-4">
                                             <input type="text" class="form-control" name="description" id="description" placeholder="Enter Description" autocomplete='off'>
                                        </div>
                                        <div class="col-lg-2">
                                             <input type="text" class="form-control" name="amount" id="amounts" placeholder="Amount" autocomplete='off'>
                                        </div>
                                        <div class="col-lg-2">
                                            <select class="select2" name="category" name="category">
                                                    <option value="">Select Category</option>
                                                    <?php
                                                    $inc = 0;
                                                    $exp = 0;
                                                    foreach ($this->systemAccount as  $system) {
                                                    ?>
                                                      <optgroup label="<?php echo ucfirst($system['account']); ?>">
                                                    <?php
                                                       foreach ($this->nonPayAccounts as  $nonPay) {
                                                        if($system['id']==4 &&$inc==0) {
                                                          $inc++;
                                                    ?>
                                                       <option value="01"><?php echo $this->getUncategory['unCategorized']['01']; ?></option>
                                                    <?php
                                                        } else if($system['id']==5 &&$exp==0) {
                                                          $exp++;
                                                    ?>
                                                      <option value="02"><?php echo $this->getUncategory['unCategorized']['02']; ?></option>
                                                    <?php
                                                        }else if($system['id']==$nonPay['fksys_id'] && $nonPay['delete_status']==1  && $nonPay['payment_status']==0) {
                                                     ?>
                                                          <option value="<?php echo $nonPay['id']; ?>"><?php echo ucfirst($nonPay['name']); ?></option>
                                                     <?php 
                                                          }
                                                       }
                                                      ?>
                                                        </optgroup>
                                                     <?php 
                                                     }
                                                     ?>                   
                                                    </select>
                                        </div>
                                        <div class="col-lg-2">
                                            <select class="select2" name="account" id="account">
                                                    <option value="">Select Account</option>
                                                     <?php
                                                    foreach ($this->systemAccount as  $system) {
                                                    ?>
                                                      <optgroup label="<?php echo ucfirst($system['account']); ?>">
                                                    <?php
                                                       foreach ($this->payAccounts as  $pay) {
                                                        if($system['id']==$pay['fksys_id'] && $pay['delete_status']==1  && $pay['payment_status']==1) {
                                                     ?>
                                                          <option value="<?php echo $pay['id']; ?>"><?php echo ucfirst($pay['name']); ?></option>
                                                     <?php 
                                                          }
                                                       }
                                                      ?>
                                                        </optgroup>
                                                     <?php 
                                                     }
                                                     ?>    
                                                    </select>
                                        </div>
                                    </div>
                                    </div>

                                     <div class="form-group" id="viewVendor" style="display:none;">

                                      <div class="col-md-offset-6">

                                            <div class="col-lg-2">
                                            <select class="select2" name="vendor" id="vendor">
                                                    <option value="">Select Vendor</option>
                                                     <?php
                                                       foreach ($this->vendorsList as  $vendor) {
                                                        if($vendor['delete_status']==1) {
                                                     ?>
                                                          <option value="<?php echo $vendor['id']; ?>"><?php echo ucfirst($vendor['name']); ?></option>
                                                     <?php 
                                                          }
                                                       }
                                                      ?>
                                                        
                                                    </select>
                                        </div>

                                      </div>

                                    </div>


                                    <div class="form-group" id="splitVendor" style="display:none;">
                                    <table id="myTables" class="order-lists">
                                        <thead>
                                            <tr>
                                                <td>Name</td>
                                                <td>Amount</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <input type="text" name="name1"  class="form-control"/>
                                                </td>
                                                <td>
                                                    <input type="text" name="price1"  class="form-control"/>
                                                </td>
                                                <td><a class="deleteRows"></a>

                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <input type="text" name="name2"  class="form-control"/>
                                                </td>
                                                <td>
                                                    <input type="text" name="price2"  class="form-control"/>
                                                </td>
                                                <td><a class="deleteRows"></a>

                                                </td>
                                            </tr>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <td colspan="5" style="text-align: left;">
                                                    <input type="button" class="btn btn-info" id="addrows" value="Add Row" />
                                                    <strong><a href="javascript:void(0)" id="cancel" onclick="return cancelSplit('vendor');">Cancel</a></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan=""><strong>Available: <span id="grandtotals"></span></strong>
                                                <input type="hidden" name="split_amount" id="split_amounts">
                                                <input type="hidden" name="split" id="splits" value="">
                                                <input type="hidden" name="split_count" id="split_counts" value="">

                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                  </div>


                                    <div class="form-group view_more">
                                     <div class="col-md-2">
                                         <strong><a href="javascript:void(0)"  onclick="return viewSplit('vendor');">Split Transaction</a></strong>
                                      </div>
                                      <div class="col-md-offset-6">
                                          <strong><a href="javascript:void(0)" id="view_details" onclick="return viewMore('vendor');">More Details</a></strong>
                                      </div>
                                    </div>


                                    <div class="form-group">
                                    <div class="col-lg-3">
                                                <div class="form-actions">
                                                    <input type="submit" name="submit" class="btn btn-primary" value="Save" />
                                                    <button type="reset" class="btn">Cancel</button>
                                                </div>
                                            </div>
                                  </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


 <div class="row">
                        <div class="col-md-12">
                            <div class="box-widget">
                                <table class="table data-tbl-boxy responsive">
                                    <thead>
                                        <tr>
                                            <th>
                                               S.No.
                                            </th>
                                            <th>
                                                Date
                                            </th>
                                            <th>
                                                Description
                                            </th>
                                            <th>
                                                Amount
                                            </th>
                                             <th>
                                                Transaction type
                                            </th>
                                            <th>
                                                Category
                                            </th>
                                            <th>
                                                Account
                                            </th>
                                            <th>
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                   <?php 
                                       $i=1;
                                      foreach ($this->transactions as $transaction) {
                                   ?>
                                   <tr>
                                      <td><?php echo $i++; ?></td>
                                      <td><?php echo date("d-m-Y",strtotime($transaction['date'])); ?></td>
                                      <td><?php echo $transaction['description']; ?></td>
                                      <td><?php echo $transaction['amount']; ?></td>
                                      <td><?php 
                                            if($transaction['transaction_category']==1)  {
                                              echo "Income";
                                            } else if($transaction['transaction_category']==2)  {
                                              echo "Expense";
                                            }
                                          ?>
                                      </td>
                                      <td><?php
                                                foreach ($this->nonPayAccounts as  $nonPay) { 
                                                  if($nonPay['id'] == $transaction['category']) {
                                                      echo ucfirst($nonPay['name']); 
                                                      break;
                                                    } else {
                                                        if($transaction['category']=='i1') {
                                                          echo "Uncategorized Income";
                                                          break;
                                                        } else if($transaction['category']=='e1') {
                                                          echo "Uncategorized Expense";
                                                          break;
                                                        } else if($transaction['category']=='inv1') {
                                                          echo "Invoice Payment";
                                                          break;
                                                        } else if($transaction['category']=='bill1') {
                                                          echo "Bill payment";
                                                          break;
                                                        }
                                                    }//else if($transaction['category']=='i1') {
                                                     // echo "Uncategorized Expense";
                                                       /* foreach ($this->uncategoryAccounts as $uncategory) { 
                                                          if($uncategory['did'] == $transaction['category']) {
                                                            echo ucfirst($uncategory['name']); 
                                                          }
                                                  }*/
                                                //}
                                             }
                                         // echo $transaction['category']; 
                                          ?>
                                      </td>
                                      <td><?php foreach ($this->payAccounts as  $pay) { 
                                              if($pay['id'] == $transaction['account'])
                                                echo ucfirst($pay['name']); 
                                            }
                                       ?></td>
                                      <td>
                                      <div class="col-md-2">
                                        <?php 
                                          if($transaction['verify_status']==1) {
                                        ?>
                                          <a class="btn btn-mini btn-success" href="javascript:void(0)" data-original-title="Unverify"  onclick="unverify('<?php echo base64_encode($transaction['id']); ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          } else if($transaction['verify_status']==0) {
                                        ?>
                                          <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Verify"  onclick="verify('<?php echo base64_encode($transaction['id']); ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          }
                                        ?>
                                        </div>

                                        <div class="btn-group col-md-1">
                                    <button data-toggle="dropdown" class="btn btn-small dropdown-toggle"> <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                      <?php 
                                        if($transaction['transaction_category']==1 && $transaction['transaction_type']!=5)
                                        {
                                      ?>
                                        <li><a class="create-payment" href="javascript:void(0)"  data-index="<?php echo base64_encode($transaction['id']);   ?>" data-type="<?php echo base64_encode(5);   ?>" data-trans="<?php echo base64_encode($transaction['transaction_type']);   ?>" data-amount="<?php echo base64_encode($transaction['amount']);   ?>">Make Invoice Payment</a></li>
                                      <?php
                                        } else if($transaction['transaction_category']==2 && $transaction['transaction_type']!=6) {
                                      ?>
                                        <li><a class="create-payment" href="javascript:void(0)"  data-index="<?php echo base64_encode($transaction['id']);   ?>" data-type="<?php echo base64_encode(6);   ?>" data-trans="<?php echo base64_encode($transaction['transaction_type']);   ?>" data-amount="<?php echo base64_encode($transaction['amount']);   ?>">Make Bill Payment</a></li>
                                      <?php
                                        }
                                      ?>
                                       <?php
                                          if(($transaction['transaction_type']!=5 && $transaction['transaction_type']!=6) && ($transaction['verify_status']==0) ) {
                                      ?>
                                        <li><a class="edit-transaction" href="javascript:void(0)" data-index="<?php echo base64_encode($transaction['id']);   ?>" data-type="<?php echo base64_encode($transaction['transaction_type']);   ?>">Edit</a></li>
                                      <?php
                                        }
                                      ?>
                                        <li><a href="javascript:void(0)" onclick="return deleteTransaction('<?php echo base64_encode($transaction['id']); ?>','<?php echo base64_encode($transaction['transaction_type']); ?>');">Delete</a></li>
                                    </ul>
                                    </div>

                                      </td>
                                   </tr>
                                   <?php
                                      }
                                   ?>                               
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>



</div>
</div>
 <script type="text/javascript">
    
 </script>