<?php
$logSession = new Zend_Session_Namespace('sess_login');
if(isset($logSession->proxy_name) && !empty($logSession->proxy_name)) {
  $company_name = ucfirst($logSession->proxy_name);
} else {
  $company_name = ucfirst($logSession->name);
}
?>
<div class="main-container">
<div class="container">
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."reports"; ?>">Reports</a></li>
   <li class="active">Ageing Payables</li>
</ul>
  <div class="row">
    <div class="col-md-12">

      <form class="form-horizontal" id="report-period" method="post">
<!--         <div class="form-group">

          <label class="col-lg-5 control-label">Cut-Off Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="from_date" id="from_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->from) && !empty($this->from)) { echo $this->from; } else { echo date('01-01-Y'); } ?>" autocomplete="off"/>
          </div>

        </div> -->

        <div class="form-group">

          <label class="col-lg-5 control-label">Report Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="to_date" id="to_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->to) && !empty($this->to)) { echo $this->to; } else { echo date('d-m-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Update</button>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>

    <div class="row">
      <div class="col-md-2 pull-right">
          <button class="print btn btn-inverse" type="button" rel="content"><i class="icon-print"></i> Print</button>
          <button class="btn btn-inverse" type="button"  onclick="tableToExcel('content', 'Account Payables')"><i class="icon-file-excel"></i> Excel</button>
      </div>
    </div>

  <div class="row">
    <div class="col-md-12">

           <h4 align="center"><?php echo $company_name; ?> </h4> 
           <h4 align="center">Ageing Report - Payables</h4> 
           <h4 align="center"> Cut-Off Date : <?php echo $this->from; ?> / Report Date : <?php echo $this->to; ?></h4> 

     <div class="box-widget">
        <div class="widget-head clearfix">
            <span class="h-icon"><i class="icon-power-cord"></i></span>
            <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">Ageing Report - Payables</a></h4>
        </div>
        <div class="widget-container">
        <div class="widget-block">
        <div class="widget-content">
        <table class="table responsive">
            <thead>
              <tr>
                 <th>
                    Name
                 </th>
                  <th style="text-align:right;">
                    Amount Due
                 </th>
                  <th style="text-align:right;">
                    1 - 30
                 </th>
                  <th style="text-align:right;">
                    30 - 60
                 </th>
                  <th style="text-align:right;">
                    60 - 90
                 </th>
                  <th style="text-align:right;">
                    90 - 120
                 </th>
                  <th style="text-align:right;">
                    > 120
                 </th>
                 <th style="text-align:right;">
                    Total
                 </th>
              </tr>
            </thead>
            <tbody>
            <?php

              $start = date('Y-m-d',strtotime($this->to));
              $start_ts = strtotime($start);


                 $first_payable = 0.00;
                 $second_payable = 0.00;
                 $third_payable = 0.00;
                 $fourth_payable = 0.00;
                 $fifth_payable = 0.00;
                 $sixth_payable = 0.00;
                 $total_payable = 0.00;
                 $total_due = 0.00;

                foreach ($this->accountPayables as $keys => $payables) {
                      $first = '0.00';
                      $second = '0.00';
                      $third = '0.00';
                      $fourth = '0.00';
                      $fifth = '0.00';
                      $sixth = '0.00';
                      $due   = '0.00';
                      $vendor_name = '';
                  foreach ($this->vendors as $vendor) {
                     if($vendor['id']==$keys) {
                        $vendor_name = $vendor['vendor_name'];
                     }
                  }
                  foreach($payables as $key => $payable) {
                      $payable_amount =  $payable['pending'];
                      if($payable_amount!=0) {
                      $end = $payable['due_date'];
                      $end_ts = strtotime($end);
                      $diff = $end_ts - $start_ts;
                      $days = round($diff / 86400);
                      if($days>0) {
                        echo $payable_amount;
                        $first += $payable_amount;
                        $first_payable += $payable_amount;
                      } else {
                        $day = abs($days);
                        if($day<=30) {
                          $second += $payable_amount;
                          $second_payable += $payable_amount;
                        } else if($day>30 && $day<=60) {
                          $third += $payable_amount;
                          $third_payable += $payable_amount;
                        } else if($day>60 && $day<=90) {
                          $fourth += $payable_amount;
                          $fourth_payable += $payable_amount;
                        } else if($day>90 && $day<=120) {
                          $fifth += $payable_amount;
                          $fifth_payable += $payable_amount;
                        } else if($day>120) {
                          $sixth += $payable_amount;
                          $sixth_payable += $payable_amount;
                        }
                      }
                      $total_payable += $payable_amount;
                  }
                }
                   $due               = $second+$third+$fourth+$fifth+$sixth;
                   $total_due        += $due;
                    if($due!=0) {
            ?>
                <tr>
                  <td><a href="<?php echo $this->sitePath."reports/index/outstanding-bills/vendor/".base64_encode($keys)."/date/".$this->to."/"; ?>"><?php echo ucfirst($vendor_name); ?></a></td>
                  <td style="text-align:right; "><?php echo number_format($due,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($second,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($third,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fourth,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fifth,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($sixth,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($due,2,'.',','); ?></td>
                </tr>

            <?php
                  }
                }
            ?>

            <tr>
                  <td><strong>Total payables</strong></td>
                  <td style="text-align:right; "><?php echo number_format($total_due,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($second_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($third_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fourth_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fifth_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($sixth_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($total_due,2,'.',','); ?></td>
            </tr>
           
            </tbody>
        </table>
        </div>
        </div>
        </div>
        </div>
    </div>

</div>
</div>
<div id="content" style="display:none;">
     <h4 align="center"><?php echo $company_name; ?> </h4> 
     <h4 align="center">Ageing Report - Payables</h4> 
     <h4 align="center"> Cut-Off Date : <?php echo $this->from; ?> / Report Date : <?php echo $this->to; ?></h4>  

     <table border="0" align="center" cellpadding="7" cellspacing="7" width="100%">
            <thead>
              <tr>
                 <th>
                    Name
                 </th>
                  <th style="text-align:right;">
                    Amount Due
                 </th>
                  <th style="text-align:right;">
                    1 - 30
                 </th>
                  <th style="text-align:right;">
                    30 - 60
                 </th>
                  <th style="text-align:right;">
                    60 - 90
                 </th>
                  <th style="text-align:right;">
                    90 - 120
                 </th>
                  <th style="text-align:right;">
                    > 120
                 </th>
                 <th style="text-align:right;">
                    Total
                 </th>
              </tr>
            </thead>
            <tbody>
            <?php

              $start = date('Y-m-d');
              $start_ts = strtotime($start);


                 $first_payable = 0.00;
                 $second_payable = 0.00;
                 $third_payable = 0.00;
                 $fourth_payable = 0.00;
                 $fifth_payable = 0.00;
                 $sixth_payable = 0.00;
                 $total_payable = 0.00;
                 $total_due = 0.00;

                foreach ($this->accountPayables as $keys => $payables) {
                      $first = '0.00';
                      $second = '0.00';
                      $third = '0.00';
                      $fourth = '0.00';
                      $fifth = '0.00';
                      $sixth = '0.00';
                      $due   = '0.00';
                      $vendor_name = '';
                  foreach ($this->vendors as $vendor) {
                     if($vendor['id']==$keys) {
                        $vendor_name = $vendor['vendor_name'];
                     }
                  }
                  foreach($payables as $key => $payable) {
                      $payable_amount =  $payable['pending'];
                      if($payable_amount!=0) {
                      $end = $payable['due_date'];
                      $end_ts = strtotime($end);
                      $diff = $end_ts - $start_ts;
                      $days = round($diff / 86400);
                      if($days>0) {
                        $first = $payable_amount;
                        $first_payable += $payable_amount;
                      } else {
                        $day = abs($days);
                        if($day<=30) {
                          $second += $payable_amount;
                          $second_payable += $payable_amount;
                        } else if($day>30 && $day<=60) {
                          $third += $payable_amount;
                          $third_payable += $payable_amount;
                        } else if($day>60 && $day<=90) {
                          $fourth += $payable_amount;
                          $fourth_payable += $payable_amount;
                        } else if($day>90 && $day<=120) {
                          $fifth += $payable_amount;
                          $fifth_payable += $payable_amount;
                        } else if($day>120) {
                          $sixth += $payable_amount;
                          $sixth_payable += $payable_amount;
                        }
                      }
                      $total_payable += $payable_amount;
                  }
                }
                   $due               = $second+$third+$fourth+$fifth+$sixth;
                   $total_due        += $due;
                    if($due!=0) {
            ?>
                <tr>
                  <td><?php echo $vendor_name; ?></td>
                  <td style="text-align:right; "><?php echo number_format($due,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($second,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($third,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fourth,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fifth,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($sixth,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($due,2,'.',','); ?></td>
                </tr>

            <?php
                  }
                }
            ?>

            <tr>
                  <td><strong>Total payables</strong></td>
                  <td style="text-align:right; "><?php echo number_format($total_due,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($second_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($third_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fourth_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($fifth_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($sixth_payable,2,'.',','); ?></td>
                  <td style="text-align:right; "><?php echo number_format($total_due,2,'.',','); ?></td>
            </tr>            </tbody>
        </table>
</div>
<script type="text/javascript">
  (function ($) {
  var rules = document.styleSheets[document.styleSheets.length-1].cssRules;
  for (var idx = 0, len = rules.length; idx < len; idx++) {
    $(rules[idx].selectorText).each(function (i, elem) {
      elem.style.cssText += rules[idx].style.cssText;
    });
  }
  $('style').remove();
})(jQuery);

var tableToExcel = (function() {
  var uri = 'data:application/vnd.ms-excel;base64,'
    , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
    , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
    , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
  return function(table, name) {
    if (!table.nodeType) table = document.getElementById(table)
    var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML}
    window.location.href = uri + base64(format(template, ctx))
  }
})()
</script>