

<div class="main-container">
<div class="container">

 <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            </div>
 </div>

  <div class="row">
    <div class="col-md-12">

      <form class="form-horizontal" id="report-period" method="post">
        <div class="form-group">

          <label class="col-lg-5 control-label">From Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="from_date" id="from_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->from) && !empty($this->from)) { echo $this->from; } else { echo date('01-01-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">

          <label class="col-lg-5 control-label">To Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="to_date" id="to_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->to) && !empty($this->to)) { echo $this->to; } else { echo date('d-m-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Update</button>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>

   <div class="row">


                        <div class="col-md-12">
                            
                            <div class="box-widget">
                                <div class="widget-head clearfix">
                                    <span class="h-icon"><i class="icon-power-cord"></i></span>
                                    <h4 class="pull-left"><a href="javascript:void(0)" style="color:#fff;">Balance Sheet</a></h4>
                                </div>
                                <div class="widget-container">
                                    <div class="widget-block">
                                        <div class="widget-content">
                                            <table class="table responsive">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            Account
                                                        </th>
                                                        <th>
                                                            Amount
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                    $l=1;
                                                    $total_assets = 0.00;
                                                    $active = array();
                                                ?>
                                                   <tr class="balance_account assets_active">
                                                    <td><span style="font-weight:bold; font-size:14px; cursor: pointer;">Assets</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->asset as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account assets_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                        </tr>
                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account assets_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(1,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                 foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 1 && $account['account_id']==$levelThree) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        if(isset($this->paymentAccount[$account['id']]) && !empty($this->paymentAccount[$account['id']])) {
                                                                $active[] = "assets_".$l2."_".$l3;
                                                                $amount = $this->paymentAccount[$account['id']];
                                                                $total_assets += $this->paymentAccount[$account['id']];
                                                                $pay_accounts = "pay_accounts";
                                                        } else {
                                                            $amount = 0.00;
                                                            $pay_accounts = "non_pay_accounts";
                                                        }
                                            ?>
                                                 <tr class="balance_account <?php echo $pay_accounts; ?> success assets_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <?php echo number_format($amount,2,'.',','); ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                                }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                             <tr class="balance_account assets_active">
                                                    <td><span style="font-weight:bold; font-size:14px; cursor: pointer;">Total Assets</span></td>
                                                    <td><?php echo number_format($total_assets,2,'.',','); ?></td>
                                             </tr>

                                             <?php 
                                                $total_liabilities = 0.00;
                                                $l = 2;
                                             ?>
                                             <tr class="balance_account liability_active">
                                                    <td><span style="font-weight:bold; font-size:14px;  cursor:pointer;">Liability/Credit Card</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->liability as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account liability_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                        </tr>
                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account liability_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(2,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                 foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 2 && $account['account_id']==$levelThree) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                       
                                                      if(isset($this->paymentAccount[$account['id']]) && !empty($this->paymentAccount[$account['id']])) {
                                                                $active[] = "liability_".$l2."_".$l3;
                                                                $amount = $this->paymentAccount[$account['id']];
                                                                $total_liabilities += $this->paymentAccount[$account['id']];
                                                                $pay_accounts = "pay_accounts";
                                                        } else {
                                                            $amount = 0.00;
                                                            $pay_accounts = "non_pay_accounts";
                                                        }
                                            ?>
                                                 <tr class="balance_account <?php echo $pay_accounts; ?> success liability_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <?php echo number_format($amount,2,'.',','); ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                                }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                             <tr class="balance_account liability_active">
                                                    <td><span style="font-weight:bold; font-size:14px; cursor: pointer;">Total Liabilities</span></td>
                                                    <td><?php echo number_format($total_liabilities,2,'.',','); ?></td>
                                             </tr>



                                           
                                             <?php 
                                                $total_equities = 0.00;
                                                $l = 5;
                                             ?>
                                             <tr class="balance_account equity_active">
                                                    <td><span style="font-weight:bold; font-size:14px;">Equity</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->equity as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account equity_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                        </tr>
                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account equity_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(5,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                         <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                 foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 5 && $account['account_id']==$levelThree) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        
                                                         if(isset($this->paymentAccount[$account['id']]) && !empty($this->paymentAccount[$account['id']])) {
                                                                $active[] = "equity_".$l2."_".$l3;
                                                                $amount = $this->paymentAccount[$account['id']];
                                                                $total_equities += $this->paymentAccount[$account['id']];
                                                                $pay_accounts = "pay_accounts";
                                                        } else {
                                                            $amount = 0.00;
                                                            $pay_accounts = "non_pay_accounts";
                                                        }
                                            ?>
                                                 <tr class="balance_account <?php echo $pay_accounts; ?> success equity_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <?php echo number_format($amount,2,'.',','); ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                                }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                              <tr class="balance_account equity_active">
                                                    <td><span style="font-weight:bold; font-size:14px; cursor: pointer;">Total Equity</span></td>
                                                    <td><?php echo number_format($total_equities,2,'.',','); ?></td>
                                             </tr>

                                              <tr class="balance_account active">
                                                    <td><span style="font-weight:bold; font-size:14px; cursor: pointer;">Total Liabilities and Equity</span></td>
                                                    <td><?php echo number_format(($total_liabilities + $total_equities),2,'.',','); ?></td>
                                             </tr>

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


</div>
</div>
<?php
    //print_r($active);
?>
<script type="text/javascript">

$(document).ready(function() {
    <?php 
        foreach ($active as $act) {
           $levels = explode("_", $act);
    ?>
        $(".pay_accounts").show();
        $(".non_pay_accounts").hide();
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").show();
        $("<?php echo ".".$act; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$act; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
    <?php
        }
    ?>
});


function account(value) {
    if(value==1) {
        $(".assets_active").show();
        $(".liability_active").show();
        $(".income_active").show();
        $(".expense_active").show();
        $(".equity_active").show();
    } else if(value==2) {
        $(".assets_active").show();
        $(".liability_active").show();
        $(".income_active").hide();
        $(".expense_active").hide();
        $(".equity_active").show();
    }  else if(value==3) {
        $(".assets_active").hide();
        $(".liability_active").hide();
        $(".income_active").show();
        $(".expense_active").show();
        $(".equity_active").hide();
    }
}



</script>