<?php
$logSession = new Zend_Session_Namespace('sess_login');
if(isset($logSession->proxy_name) && !empty($logSession->proxy_name)) {
  $company_name = ucfirst($logSession->proxy_name);
} else {
  $company_name = ucfirst($logSession->name);
}
?>
<div class="main-container">
<div class="container">
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."reports"; ?>">Reports</a></li>
   <li class="active">Bank Reconcilation</li>
</ul>
  <div class="row">
    <div class="col-md-12">

      <form class="form-horizontal" id="report-period" method="get">

         <div class="form-group">

          <label class="col-lg-5 control-label">Account <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <select name="account" id="account" class="form-control">
                   <option value="">Select Account</option>
                       <?php 
                          $accountSelect = '';
                          $accountName = '';
                          $accountType = array();
                          if(isset($this->generalAccount) && !empty($this->generalAccount)) {
                              foreach ($this->generalAccount as $account) {
                                if($account['account_type']==1 && $account['level1']==1 && $account['level2']==1) {

                       ?>

                       <?php 
                          /*if(!in_array($account['account_type'], $accountType)) {
                            if($account['account_type']==1) {
                              echo '<optgroup label="Assets">';
                            } else if($account['account_type']==2) {
                             echo '<optgroup label="Liability / Credit Card">';
                            } else if($account['account_type']==3) {
                             echo '<optgroup label="Income">';
                            } else if($account['account_type']==4) {
                             echo '<optgroup label="Expense">';
                            } else if($account['account_type']==5) {
                             echo '<optgroup label="Equity">';
                            }
                            $accountType[] = $account['account_type'];
                          }*/
                                if(isset($this->currentAccount) && !empty($this->currentAccount)  && $account['id']==$this->currentAccount ) {
                                    $accountSelect = 'selected';
                                    $accountName = $account['account_name'];
                                    $accountId = $account['account_type'];
                                } else { 
                                    $accountSelect = '';
                                }
                       ?>
                    <option value="<?php echo $account['id']; ?>" <?php echo $accountSelect; ?>><?php echo ucfirst($account['account_name']); ?></option>
                      <?php
                                 }
                               }
                           } 
                        ?>
                </select> 
          </div>

        </div>

        <div class="form-group">

          <label class="col-lg-5 control-label">From Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="from_date" id="from_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->from) && !empty($this->from)) { echo $this->from; } else { echo date('01-01-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">

          <label class="col-lg-5 control-label">To Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="to_date" id="to_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->to) && !empty($this->to)) { echo $this->to; } else { echo date('d-m-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Update</button>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>

<?php 
 // if(isset($this->accountLedger) && !empty($this->accountLedger)) {
?>

    <div class="row">
      <div class="col-md-2 pull-right">
          <button class="print btn btn-inverse" type="button" rel="content"><i class="icon-print"></i> Print</button>
          <button class="btn btn-inverse" type="button"  onclick="tableToExcel('content', 'Account Transactions')"><i class="icon-file-excel"></i> Excel</button>
      </div>
    </div>


 <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            </div>
 </div>

  <div class="row">
    <div class="col-md-12">

     <h4 align="center"><?php echo $company_name; ?> </h4> 
     <h4 align="center"><?php echo $accountName; ?> Bank Reconcilation</h4> 
     <h4 align="center">Dated From <?php echo $this->from; ?> To <?php echo $this->to; ?></h4> 

     <div class="box-widget">
        <div class="widget-head clearfix">
            <span class="h-icon"><i class="icon-power-cord"></i></span>
            <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">Bank Reconcilation</a></h4>
        </div>
        <div class="widget-container">
        <div class="widget-block">
        <div class="widget-content">
        <form class="form-horizontal" id="bank-reconcile" method="post">
        <table class="table responsive">
            
            <tbody>
                <?php

                  $check = 0;
                  $tots = 0;
                  $debit_amount = 0.00;
                  $credit_amount = 0.00;
                  foreach ($this->generalAccount as $general) {
                    $bank_not_debit_amount  = 0.00;
                    $bank_not_credit_amount = 0.00;
                    $heading = 0;
                    $i = 0;
                    $runningBalance = 0.00;
                    
                ?>


                <?php 
                  if(($general['debit_opening_balance']>0 || $general['credit_opening_balance']>0) && $general['id']==$this->currentAccount) {
                    $heading++;
                ?>

                  <tr>
                      <td colspan="7" style="text-align:center;"><strong style="font-size:14px;"><?php echo ucfirst($general['account_name']); ?></strong></td>
                    </tr>
                    <tr>
                      <th colspan="4"></th>
                      <th colspan="2" style="text-align:center;">Transactions</th>
                      <!-- <th colspan="2" style="text-align:center;">Balance</th> -->
                      <th></th>
                    </tr>


                    <tr>
                      <th width="10%">Date</th>
                      <th width="20%">Transaction Description</th>
                      <th width="10%">Counterparties</th>
                      <!-- <th width="10%">Type</th> -->
                      <th width="15%">Vch No.</th>
                      <th width="15%" style="text-align:right;">Debit</th>
                      <th width="15%" style="text-align:right;">Credit</th>
                      <!-- <th width="10%" style="text-align:right;">Debit</th>
                      <th width="10%" style="text-align:right;">Credit</th> -->
                      <th width="15%" style="text-align:center;">Bank Date</th>
                    </tr>

<!--                   <tr>
                      <td></td>
                      <td><strong>Opening Balance</strong></td>
                      <td></td>
                      <td></td>
                      <td style="text-align:right;"><?php if($general['debit_opening_balance']>0) { echo number_format($general['debit_opening_balance'],2,'.',','); } ?></td>
                      <td style="text-align:right;"><?php if($general['credit_opening_balance']>0) { echo number_format($general['credit_opening_balance'],2,'.',','); } ?></td>
                      <td style="text-align:right;">
                        <?php
                          if($general['debit_opening_balance']!=0 && $general['debit_opening_balance']>0) {
                            $runningBalance = $general['debit_opening_balance'];
                            echo number_format($general['debit_opening_balance'],2,'.',',');
                          } else {
                            echo "-";
                          } 
                        ?>
                      </td>
                       <td style="text-align:right;">
                        <?php
                          if($general['credit_opening_balance']!=0 && $general['credit_opening_balance']>0) {
                            $runningBalance = -($general['credit_opening_balance']);
                            echo number_format($general['credit_opening_balance'],2,'.',',');
                          } else {
                            echo "-";
                          } 
                        ?>
                      </td>
                      <td></td>
                    </tr> -->

                <?php 
                  }
                ?>
                
                 

                <?php 
                if(isset($this->accountLedger) && !empty($this->accountLedger)) {
                  foreach ($this->accountLedger as $keys => $ledger) {
                    if($general['id']==$keys && $general['id']==$this->currentAccount) {
                      
                      $runningBalance = $this->compBalance;
                      $check++;
                ?>
                    <!-- <tr>
                      <td colspan="8" style="text-align:center;"><strong style="font-size:14px;"><?php echo ucfirst($general['account_name']); ?></strong></td>
                    </tr> -->

                <?php
                  if($heading==0) {
                ?>
                    <tr>
                      <td colspan="7" style="text-align:center;"><strong style="font-size:14px;"><?php echo ucfirst($general['account_name']); ?></strong></td>
                    </tr>

                     <tr>
                      <th colspan="4"></th>
                      <th colspan="2" style="text-align:center;">Transactions</th>
                      <!-- <th colspan="2" style="text-align:center;">Balance</th> -->
                      <th></th>
                     </tr>

                    <tr>
                      <th width="10%">Date</th>
                      <th width="20%">Transaction Description</th>
                      <th width="10%">Counterparties</th>
                      <!-- <th width="10%">Type</th> -->
                      <th width="15%">Vch No.</th>
                      <th width="15%" style="text-align:right;">Debit</th>
                      <th width="15%" style="text-align:right;">Credit</th>
                      <!-- <th width="10%" style="text-align:right;">Debit</th>
                      <th width="10%" style="text-align:right;">Credit</th> -->
                      <th width="15%" style="text-align:center;">Bank Date</th>
                    </tr>
                <?php
                    }
                ?>


                    
                <?php 
                      $bank_not_debit_amount  = 0.00;
                      $bank_not_credit_amount = 0.00;
                      foreach ($ledger as $keyss => $data) {
                        
                        $debit_amount  = abs($data['debit_amount']);
                        $credit_amount = abs($data['credit_amount']);

                        $split = explode("_", $keyss);

                        $pid = $split[0]."_".$data['type'];
                        //echo $runningBalance;
                        /*if($debit_amount!=0 && $debit_amount>0) {
                            $runningBalance += $debit_amount;
                          } else if($credit_amount!=0 && $credit_amount>0) {
                            $runningBalance -= $credit_amount;
                          }*/
                          /*if($runningBalance<0) {
                            $amt = number_format(abs($runningBalance),2,'.',',');
                          } else {
                            $amt = number_format($runningBalance,2,'.',',');
                          }*/
                ?>
                   <tr>
                        <td width="10%"><?php echo date('d-m-Y',strtotime($data['date'])); ?></td>
                      <td width="20%"><?php echo ucfirst($data['transaction']); ?></td>
                      <td width="10%"><?php echo ucfirst($data['name']); ?></td>
                     <!--  <td width="10%"><?php echo $data['type']; ?></td> -->
                      <td width="15%"><?php echo $data['no']; ?></td>
                       <td width="15%" style="text-align:right;"><?php echo number_format($debit_amount,2,'.',','); ?></td>
                      <td width="15%" style="text-align:right;"><?php echo number_format($credit_amount,2,'.',','); ?></td>
                        <?
                          if($data['bank_date']!=0) {
                            $bank = date('d-m-Y',strtotime($data['bank_date']));
                            if(strtotime($bank) > strtotime($this->to)) {
                              $bank_not_debit_amount  += $debit_amount;
                              $bank_not_credit_amount += $credit_amount;
                            } 
                          } else {
                            $bank = '';

                            $bank_not_debit_amount  += $debit_amount;
                            $bank_not_credit_amount += $credit_amount;
                          }
                        ?>
                        <td width="15%" style="text-align:center;"><div class="col-lg-10">
                              <input type="text" name="bank_date[<?php echo $data['pid']; ?>]" id="bank_date_<?php echo $data['pid']; ?>" class="form-control date-pick bank_date_<?php echo $data['pid']; ?>" style="margin-left:20px;" value="<?php echo $bank; ?>"  />
                            </div>
                        </td>
                    </tr>

                    <?php 
                          }
                        }
                      }
                    ?>

                    <?php

                       if($runningBalance!=0) {
                        $tots++;
                        $compBalance = abs($runningBalance);
                        $bankNot     = $bank_not_debit_amount-$bank_not_credit_amount;
                        $bankBalance = $compBalance-$bankNot;
                    ?>


                      <tr>
                      <td colspan="4" style="text-align:right;"><strong>Company Balance</strong></td>
                      <?php
                          if($runningBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($runningBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($runningBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                      <td></td>
                    </tr>

                     <tr>
                      <td colspan="4" style="text-align:right;"><strong>Amounts not Reflected in Bank</strong></td>
                         <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_debit_amount,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_credit_amount,2,'.',','); ?></td>

                      <td></td>
                    </tr>

                    <tr>
                      <td colspan="4" style="text-align:right;"><strong>Bank Balance</strong></td>
                      <?php
                          if($bankBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($bankBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                         <!-- <td width="10%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="10%" style="text-align:right;"></td> -->

                      <td></td>
                    </tr>

                    <?php
                      }
                    ?>

                <?php
                  }
                }
                ?>

                <?php 

                  if($tots==0) {
                    foreach ($this->generalAccount as $general) {
                      if($general['id']==$this->currentAccount) {
                        $runningBalance = $this->compBalance;
                ?>


                <?php

                       if($runningBalance!=0) {
                        
                        $compBalance = abs($runningBalance);
                        $bankNot     = $bank_not_debit_amount-$bank_not_credit_amount;
                        $bankBalance = $compBalance-$bankNot;
                    ?>


                      <tr>
                      <td colspan="4" style="text-align:right;"><strong>Company Balance</strong></td>
                      <?php
                          if($runningBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($runningBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($runningBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                      <td></td>
                    </tr>

                     <tr>
                      <td colspan="4" style="text-align:right;"><strong>Amounts not Reflected in Bank</strong></td>
                         <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_debit_amount,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_credit_amount,2,'.',','); ?></td>

                      <td></td>
                    </tr>

                    <tr>
                      <td colspan="4" style="text-align:right;"><strong>Bank Balance</strong></td>
                      <?php
                          if($bankBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($bankBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                         <!-- <td width="10%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="10%" style="text-align:right;"></td> -->

                      <td></td>
                    </tr>

                    <?php
                      }
                    ?>

                <?php
                    }
                    }
                  }
                ?>


            </tbody>


        </table>
        </div>
        <?php
          if($check!=0) {
        ?>
        <div class="form-group">
                                            <label class="col-lg-5 control-label">&nbsp;</label>
                                            <div class="col-lg-3">
                                                <div class="form-actions">
                                                    <button type="submit" id="update" class="btn btn-primary">Update</button>
                                                    <a href="<?php echo $this->sitePath."settings/account/" ?>" class="btn btn-default">Cancel</a>
                                                </div>
                                            </div>
                                        </div>
        <?php
          }
        ?>
        </form>
        </div>
        </div>
        </div>
        </div>
    </div>

</div>
</div>


<div id="content" style="display:none;">


          <table class="table responsive" align="center" width="100%" cellpadding="5" cellspacing="5" style="width:100%;">
            
            <tbody>

               <?php

                  $check = 0;
                  $tots = 0;
                  $debit_amount = 0.00;
                  $credit_amount = 0.00;
                  foreach ($this->generalAccount as $general) {
                    $bank_not_debit_amount  = 0.00;
                    $bank_not_credit_amount = 0.00;
                    $heading = 0;
                    $i = 0;
                    $runningBalance = 0.00;
                    
                ?>


                <?php 
                  if(($general['debit_opening_balance']>0 || $general['credit_opening_balance']>0) && $general['id']==$this->currentAccount) {
                    $heading++;
                ?>

                  <tr>
                      <td colspan="7" style="text-align:center;"><strong style="font-size:14px;"><?php echo ucfirst($general['account_name']); ?></strong></td>
                    </tr>
                    <tr>
                      <th colspan="4"></th>
                      <th colspan="2" style="text-align:center;">Transactions</th>
                      <!-- <th colspan="2" style="text-align:center;">Balance</th> -->
                      <th></th>
                    </tr>


                    <tr>
                      <th width="10%">Date</th>
                      <th width="20%">Transaction Description</th>
                      <th width="10%">Counterparties</th>
                      <!-- <th width="10%">Type</th> -->
                      <th width="15%">Vch No.</th>
                      <th width="15%" style="text-align:right;">Debit</th>
                      <th width="15%" style="text-align:right;">Credit</th>
                      <!-- <th width="10%" style="text-align:right;">Debit</th>
                      <th width="10%" style="text-align:right;">Credit</th> -->
                      <th width="15%" style="text-align:center;">Bank Date</th>
                    </tr>

<!--                   <tr>
                      <td></td>
                      <td><strong>Opening Balance</strong></td>
                      <td></td>
                      <td></td>
                      <td style="text-align:right;"><?php if($general['debit_opening_balance']>0) { echo number_format($general['debit_opening_balance'],2,'.',','); } ?></td>
                      <td style="text-align:right;"><?php if($general['credit_opening_balance']>0) { echo number_format($general['credit_opening_balance'],2,'.',','); } ?></td>
                      <td style="text-align:right;">
                        <?php
                          if($general['debit_opening_balance']!=0 && $general['debit_opening_balance']>0) {
                            $runningBalance = $general['debit_opening_balance'];
                            echo number_format($general['debit_opening_balance'],2,'.',',');
                          } else {
                            echo "-";
                          } 
                        ?>
                      </td>
                       <td style="text-align:right;">
                        <?php
                          if($general['credit_opening_balance']!=0 && $general['credit_opening_balance']>0) {
                            $runningBalance = -($general['credit_opening_balance']);
                            echo number_format($general['credit_opening_balance'],2,'.',',');
                          } else {
                            echo "-";
                          } 
                        ?>
                      </td>
                      <td></td>
                    </tr> -->

                <?php 
                  }
                ?>
                
                 

                <?php 
                if(isset($this->accountLedger) && !empty($this->accountLedger)) {
                  foreach ($this->accountLedger as $keys => $ledger) {
                    if($general['id']==$keys && $general['id']==$this->currentAccount) {
                      
                      $runningBalance = $this->compBalance;
                      $check++;
                ?>
                    <!-- <tr>
                      <td colspan="8" style="text-align:center;"><strong style="font-size:14px;"><?php echo ucfirst($general['account_name']); ?></strong></td>
                    </tr> -->

                <?php
                  if($heading==0) {
                ?>
                    <tr>
                      <td colspan="7" style="text-align:center;"><strong style="font-size:14px;"><?php echo ucfirst($general['account_name']); ?></strong></td>
                    </tr>

                     <tr>
                      <th colspan="4"></th>
                      <th colspan="2" style="text-align:center;">Transactions</th>
                      <!-- <th colspan="2" style="text-align:center;">Balance</th> -->
                      <th></th>
                     </tr>

                    <tr>
                      <th width="10%">Date</th>
                      <th width="20%">Transaction Description</th>
                      <th width="10%">Counterparties</th>
                      <!-- <th width="10%">Type</th> -->
                      <th width="15%">Vch No.</th>
                      <th width="15%" style="text-align:right;">Debit</th>
                      <th width="15%" style="text-align:right;">Credit</th>
                      <!-- <th width="10%" style="text-align:right;">Debit</th>
                      <th width="10%" style="text-align:right;">Credit</th> -->
                      <th width="15%" style="text-align:center;">Bank Date</th>
                    </tr>
                <?php
                    }
                ?>


                    
                <?php 
                      $bank_not_debit_amount  = 0.00;
                      $bank_not_credit_amount = 0.00;
                      foreach ($ledger as $keyss => $data) {
                        
                        $debit_amount  = abs($data['debit_amount']);
                        $credit_amount = abs($data['credit_amount']);

                        $split = explode("_", $keyss);

                        $pid = $split[0]."_".$data['type'];
                        //echo $runningBalance;
                        /*if($debit_amount!=0 && $debit_amount>0) {
                            $runningBalance += $debit_amount;
                          } else if($credit_amount!=0 && $credit_amount>0) {
                            $runningBalance -= $credit_amount;
                          }*/
                          /*if($runningBalance<0) {
                            $amt = number_format(abs($runningBalance),2,'.',',');
                          } else {
                            $amt = number_format($runningBalance,2,'.',',');
                          }*/
                ?>
                   <tr>
                        <td width="10%"><?php echo date('d-m-Y',strtotime($data['date'])); ?></td>
                      <td width="20%"><?php echo ucfirst($data['transaction']); ?></td>
                      <td width="10%"><?php echo ucfirst($data['name']); ?></td>
                     <!--  <td width="10%"><?php echo $data['type']; ?></td> -->
                      <td width="15%"><?php echo $data['no']; ?></td>
                       <td width="15%" style="text-align:right;"><?php echo number_format($debit_amount,2,'.',','); ?></td>
                      <td width="15%" style="text-align:right;"><?php echo number_format($credit_amount,2,'.',','); ?></td>
                        <?
                          if($data['bank_date']!=0) {
                            $bank = date('d-m-Y',strtotime($data['bank_date']));
                            if(strtotime($bank) > strtotime($this->to)) {
                              $bank_not_debit_amount  += $debit_amount;
                              $bank_not_credit_amount += $credit_amount;
                            } 
                          } else {
                            $bank = '';

                            $bank_not_debit_amount  += $debit_amount;
                            $bank_not_credit_amount += $credit_amount;
                          }
                        ?>
                        <td width="15%" style="text-align:center;"><?php echo $bank; ?>                        </td>
                    </tr>

                    <?php 
                          }
                        }
                      }
                    ?>

                    <?php

                       if($runningBalance!=0) {
                        $tots++;
                        $compBalance = abs($runningBalance);
                        $bankNot     = $bank_not_debit_amount-$bank_not_credit_amount;
                        $bankBalance = $compBalance-$bankNot;
                    ?>


                      <tr>
                      <td colspan="4" style="text-align:right;"><strong>Company Balance</strong></td>
                      <?php
                          if($runningBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($runningBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($runningBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                      <td></td>
                    </tr>

                     <tr>
                      <td colspan="4" style="text-align:right;"><strong>Amounts not Reflected in Bank</strong></td>
                         <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_debit_amount,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_credit_amount,2,'.',','); ?></td>

                      <td></td>
                    </tr>

                    <tr>
                      <td colspan="4" style="text-align:right;"><strong>Bank Balance</strong></td>
                      <?php
                          if($bankBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($bankBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                         <!-- <td width="10%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="10%" style="text-align:right;"></td> -->

                      <td></td>
                    </tr>

                    <?php
                      }
                    ?>

                <?php
                  }
                }
                ?>

                <?php 

                  if($tots==0) {
                    foreach ($this->generalAccount as $general) {
                      if($general['id']==$this->currentAccount) {
                        $runningBalance = $this->compBalance;
                ?>


                <?php

                       if($runningBalance!=0) {
                        
                        $compBalance = abs($runningBalance);
                        $bankNot     = $bank_not_debit_amount-$bank_not_credit_amount;
                        $bankBalance = $compBalance-$bankNot;
                    ?>


                      <tr>
                      <td colspan="4" style="text-align:right;"><strong>Company Balance</strong></td>
                      <?php
                          if($runningBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($runningBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($runningBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                      <td></td>
                    </tr>

                     <tr>
                      <td colspan="4" style="text-align:right;"><strong>Amounts not Reflected in Bank</strong></td>
                         <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_debit_amount,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bank_not_credit_amount,2,'.',','); ?></td>

                      <td></td>
                    </tr>

                    <tr>
                      <td colspan="4" style="text-align:right;"><strong>Bank Balance</strong></td>
                      <?php
                          if($bankBalance<0) {
                        ?>
                          <td width="15%" style="text-align:right;">-</td>
                          <td width="15%" style="text-align:right;"><?php echo number_format(abs($bankBalance),2,'.',','); ?></td>

                        <?php
                          } else {
                        ?>
                          <td width="15%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="15%" style="text-align:right;">-</td>
                        <?php
                          }
                        ?>
                         <!-- <td width="10%" style="text-align:right;"><?php echo number_format($bankBalance,2,'.',','); ?></td>
                          <td width="10%" style="text-align:right;"></td> -->

                      <td></td>
                    </tr>

                    <?php
                      }
                    ?>

                <?php
                    }
                    }
                  }
                ?>


            </tbody>


        </table>



</div>

<?php
//  }
?>
<script type="text/javascript">
  (function ($) {
  var rules = document.styleSheets[document.styleSheets.length-1].cssRules;
  for (var idx = 0, len = rules.length; idx < len; idx++) {
    $(rules[idx].selectorText).each(function (i, elem) {
      elem.style.cssText += rules[idx].style.cssText;
    });
  }
  $('style').remove();
})(jQuery);

var tableToExcel = (function() {
  var uri = 'data:application/vnd.ms-excel;base64,'
    , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
    , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
    , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
  return function(table, name) {
    if (!table.nodeType) table = document.getElementById(table)
    var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML}
    window.location.href = uri + base64(format(template, ctx))
  }
})()
</script>