<?php
$logSession = new Zend_Session_Namespace('sess_login');
if(isset($logSession->proxy_name) && !empty($logSession->proxy_name)) {
  $company_name = ucfirst($logSession->proxy_name);
} else {
  $company_name = ucfirst($logSession->name);
}
?>
<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."reports"; ?>">Reports</a></li>
   <li><a href="<?php echo $this->sitePath."reports/index/expense-by-vendor"; ?>">Expense By Vendor</a></li>
   <li class="active">Expense By Vendor COA</li>
</ul>

    <div class="row">
      <div class="col-md-4 col-md-offset-2 pull-right">
          <button class="print btn btn-inverse" type="button" rel="content"><i class="icon-print"></i> Print</button>
          <button class="btn btn-inverse" type="button"  onclick="tableToExcel('content', 'Income By Customer')"><i class="icon-file-excel"></i> Excel</button>
      </div>
    </div>



  <div class="row">
    <div class="col-md-8 col-md-offset-2">

     <h4 align="center"><?php echo $company_name; ?> </h4> 
     <h4 align="center">Expense By Vendor</h4> 
     <h4 align="center"><?php echo ucfirst($this->vendor); ?></h4> 
     <h4 align="center">Dated From <?php echo $this->from; ?> To <?php echo $this->to; ?></h4> 


     <div class="box-widget">
                                <div class="widget-head clearfix">
                                    <span class="h-icon"><i class="icon-power-cord"></i></span>
                                    <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">Expense By Vendor COA</a></h4>
                                </div>
                                <div class="widget-container">
                                    <div class="widget-block">
                                        <div class="widget-content">
                                            <table class="table responsive">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            Chart of Accounts
                                                        </th>
                                                        <th style="text-align:right; padding-right:50px;">
                                                            Amount
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                    $l=1;
                                                    $active = array();
                                                    $asset_level1 = 1;
                                                    $asset_level2 = 2;
                                                    $total_expense = 0.00;
                                                ?>




                                                  <?php 
                                                $l = 1;
                                             ?>
                                             <tr class="balance_account assets_active">
                                                    <td><span style="font-weight:bold; font-size:14px;">Assets</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->assets as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account assets_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                        </tr>


                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account assets_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(3,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                    foreach ($this->coa as $account) {
                                                     
                                                        if($account['type'] == 1 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "assets_".$l2."_".$l3;
                                                        $total_expense += $account['amount'];
                                            ?>
                                                 <tr class="balance_account success assets_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['name']; ?></span></td>
                                                        <td style="text-align:right; padding-right:50px;"><?php echo number_format($account['amount'],2,'.',','); ?></td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                       
                                                    }
                                                }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>



                                                
                                                   

                                             <?php 
                                                $l = 3;
                                             ?>
                                             <tr class="other_account expense_active">
                                                    <td><span style="font-weight:bold; font-size:14px;">Expense</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->expense as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="other_account expense_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                        </tr>


                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="other_account expense_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(3,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                    foreach ($this->coa as $account) {
                                                        if($account['type'] == 4 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "expense_".$l2."_".$l3;
                                                        $total_expense += $account['amount'];
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['name']; ?></span></td>
                                                        <td style="text-align:right; padding-right:50px;"><?php echo number_format($account['amount'],2,'.',','); ?></td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                       
                                                    }
                                                }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                             <tr>
                                               <td style="text-align:right;"><strong>Total</strong></td>
                                               <td style="text-align:right; padding-right:50px;"><strong><?php echo number_format($total_expense,2,'.',','); ?></strong></td>
                                             </tr>

                                             

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>


    </div>

</div>
</div>

</div>




  <div class="row" id="content" style="display:none;">
    <div class="col-md-8 col-md-offset-2">

     <h4 align="center"><?php echo $company_name; ?> </h4> 
     <h4 align="center">Expense By Vendor</h4> 
     <h4 align="center"><?php echo ucfirst($this->vendor); ?></h4> 
     <h4 align="center">Dated From <?php echo $this->from; ?> To <?php echo $this->to; ?></h4> 


     <div class="box-widget">
                                <div class="widget-head clearfix">
                                    <span class="h-icon"><i class="icon-power-cord"></i></span>
                                    <!-- <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">Expense By Vendor COA</a></h4> -->
                                </div>
                                <div class="widget-container">
                                    <div class="widget-block">
                                        <div class="widget-content">
                                            <table class="table responsive" align="center" width="70%" cellpadding="5" cellspacing="5" style="width:70%;">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            Chart of Accounts
                                                        </th>
                                                        <th style="text-align:right; padding-right:50px;">
                                                            Amount
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                    $l=1;
                                                    $active = array();
                                                    $asset_level1 = 1;
                                                    $asset_level2 = 2;
                                                    $total_expense = 0.00;
                                                ?>


                                            <?php 
                                                $l = 1;
                                             ?>
                                             <tr class="balance_account assets_active">
                                                    <td><span style="font-weight:bold; font-size:14px;">Assets</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->assets as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account assets_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                        </tr>


                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account assets_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(3,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                    foreach ($this->coa as $account) {
                                                     
                                                        if($account['type'] == 1 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "assets_".$l2."_".$l3;
                                                        $total_expense += $account['amount'];
                                            ?>
                                                 <tr class="balance_account success assets_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['name']; ?></span></td>
                                                        <td style="text-align:right; padding-right:50px;"><?php echo number_format($account['amount'],2,'.',','); ?></td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                       
                                                    }
                                                }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>







                                                   

                                             <?php 
                                                $l = 3;
                                             ?>
                                             <tr class="other_account expense_active">
                                                    <td><span style="font-weight:bold; font-size:14px;">Expense</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->expense as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="other_account expense_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                        </tr>


                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="other_account expense_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(3,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                    foreach ($this->coa as $account) {
                                                        if($account['type'] == 4 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "expense_".$l2."_".$l3;
                                                        $total_expense += $account['amount'];
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['name']; ?></span></td>
                                                        <td style="text-align:right; padding-right:50px;"><?php echo number_format($account['amount'],2,'.',','); ?></td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                       
                                                    }
                                                }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                             <tr>
                                               <td style="text-align:right;"><strong>Total</strong></td>
                                               <td style="text-align:right; padding-right:50px;"><strong><?php echo number_format($total_expense,2,'.',','); ?></strong></td>
                                             </tr>

                                             

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>


    </div>

</div>

<script type="text/javascript">

  $(document).ready(function() {
    <?php 
        foreach ($active as $act) {
           $levels = explode("_", $act);
    ?>
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").show();
        $("<?php echo ".".$act; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$act; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
    <?php
        }
    ?>
  });

  (function ($) {
  var rules = document.styleSheets[document.styleSheets.length-1].cssRules;
  for (var idx = 0, len = rules.length; idx < len; idx++) {
    $(rules[idx].selectorText).each(function (i, elem) {
      elem.style.cssText += rules[idx].style.cssText;
    });
  }
  $('style').remove();
})(jQuery);

var tableToExcel = (function() {
  var uri = 'data:application/vnd.ms-excel;base64,'
    , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
    , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
    , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
  return function(table, name) {
    if (!table.nodeType) table = document.getElementById(table)
    var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML}
    window.location.href = uri + base64(format(template, ctx))
  }
})()
</script>
