<div class="main-container">
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <form class="form-horizontal" id="report-period" method="post">
        <div class="form-group">

          <label class="col-lg-5 control-label">From Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="from_date" id="from_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->from) && !empty($this->from)) { echo $this->from; } else { echo date('01-01-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">

          <label class="col-lg-5 control-label">To Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="to_date" id="to_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->to) && !empty($this->to)) { echo $this->to; } else { echo date('d-m-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Update</button>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
     <div class="box-widget">
        <div class="widget-head clearfix">
            <span class="h-icon"><i class="icon-power-cord"></i></span>
            <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">Income</a></h4>
        </div>
        <div class="widget-container">
        <div class="widget-block">
        <div class="widget-content">
        <table class="table responsive">
            <thead>
              <tr>
                 <th>
                    Accounts
                 </th>
                 <th>
                    
                 </th>
              </tr>
            </thead>
            <tbody>
            <?php
                $total_income = 0.00;
                foreach ($this->incomeAcc as $key => $inc) {
                    $total_income += $inc;
            ?>
                <tr>
                   <td>
                    <?php
                        foreach ($this->incomeCoa as $incType) {
                           if($key==$incType['id']) {
                               echo $incType['account_name'];
                           }
                         } 
                    ?>
                    </td>
                    <td><?php echo $inc; ?></td>
                </tr>

            <?php
                }
            ?>
            <tr>
                <td><strong>Total Income</strong></td>
                <td><strong><?php echo $total_income; ?></strong></td>
            </tr>
            </tbody>
        </table>
        </div>
        </div>
        </div>
        </div>
    </div>

    <div class="col-md-6">
     <div class="box-widget">
        <div class="widget-head clearfix">
            <span class="h-icon"><i class="icon-power-cord"></i></span>
            <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">Expense</a></h4>
        </div>
        <div class="widget-container">
        <div class="widget-block">
        <div class="widget-content">
        <table class="table responsive">
            <thead>
              <tr>
                 <th>
                    Accounts
                 </th>
                 <th>
                    
                 </th>
              </tr>
            </thead>
            <tbody>
            <?php
                $total_expense = 0.00;
                foreach ($this->expenseAcc as $key => $exp) {
                    $total_expense += $exp;
            ?>
                <tr>
                   <td>
                    <?php
                        foreach ($this->expenseCoa as $expType) {
                           if($key==$expType['id']) {
                               echo $expType['account_name'];
                           }
                         } 
                    ?>
                    </td>
                    <td><?php echo $exp; ?></td>
                </tr>

            <?php
                }
            ?>
            <tr>
                <td><strong>Total Expense</strong></td>
                <td><strong><?php echo $total_expense; ?></strong></td>
            </tr>
            </tbody>
        </table>
        </div>
        </div>
        </div>
        </div>
    </div>
  </div>

  <div class="row">
        <div class="col-md-12">
        <?php 
            $net_profit = $total_income - $total_expense;
        ?>
        <h4>Net Profit : <?php echo $net_profit; ?></h4>
        </div>
  </div>

</div>
</div>
<script type="text/javascript">
/* var nowTemp = new Date();
var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
 
var checkin = $('#from_date').datepicker({
  onRender: function(date) {
    return date.valueOf() < now.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  if (ev.date.valueOf() > checkout.date.valueOf()) {
    var newDate = new Date(ev.date)
    newDate.setDate(newDate.getDate() + 1);
    checkout.setValue(newDate);
  }
  checkin.hide();
  $('#to_date')[0].focus();
}).data('datepicker');
var checkout = $('#to_date').datepicker({
  onRender: function(date) {
    return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  checkout.hide();
}).data('datepicker'); */
</script>