<div class="main-container">
<div class="container">
<div class="board-widget">
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li class="active">Reports</li>
</ul>
                        <div class="row">
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/balance-sheet"; ?>"><i class="icon-file"></i><span class="board-widget-label">Balance Sheet</span></a>
                                </div>
                            </div>
                            <div class=" col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/income-statement"; ?>"><i class="icon-stats-2"></i><span class="board-widget-label">Income Statement</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/cashflow"; ?>"><i class="icon-money"></i><span class="board-widget-label">Cash Flow Analysis</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/bank-reconcile"; ?>"><i class="icon-building"></i><span class="board-widget-label">Bank Reconciliation</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/iras-audit-file"; ?>"><i class="icon-file-5"></i><span class="board-widget-label">IRAS Audit File</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/sales-tax"; ?>"><i class="icon-factory"></i><span class="board-widget-label">Sales Tax Report</span></a>
                                </div>
                            </div>

                             <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/account-receivables"; ?>"><i class="icon-arrow-left-7"></i><span class="board-widget-label">Ageing Report - Receivables</span></a>
                                </div>
                            </div>
                            <div class=" col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/account-payables"; ?>"><i class="icon-arrow-right-7"></i><span class="board-widget-label">Ageing Report - Payables</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/general-ledger"; ?>"><i class="icon-book"></i><span class="board-widget-label">General Ledger</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/income-by-customer"; ?>"><i class="icon-tag-2"></i><span class="board-widget-label">Income By Customer</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/expense-by-vendor"; ?>"><i class="icon-cart-2"></i><span class="board-widget-label">Expense By Vendor</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/account-transactions"; ?>"><i class="icon-notebook"></i><span class="board-widget-label">Account Transactions</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."reports/index/foreign-currency"; ?>"><i class="icon-calculate-2"></i><span class="board-widget-label">Gain / Loss on Foreign Currency</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
</div>
</div>