<div class="main-container">
<div class="container">
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."reports"; ?>">Reports</a></li>
   <li class="active">IRAS Audit</li>
</ul>
  <div class="row">
    <div class="col-md-12">

      <form class="form-horizontal" id="report-period" method="post">
        <div class="form-group">

          <label class="col-lg-5 control-label">From Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="from_date" id="from_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->from) && !empty($this->from)) { echo $this->from; } else { echo date('01-01-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">

          <label class="col-lg-5 control-label">To Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="to_date" id="to_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->to) && !empty($this->to)) { echo $this->to; } else { echo date('d-m-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Update</button>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>

    <div class="row">

    <div class="col-md-12">

      <form class="form-horizontal" id="addReport" method="post">
        <div class="form-group">
         <div class="col-lg-2">
          <input type="checkbox" name="report" id="report" class="report" value="1"> <strong>Company Information Table</strong>
         </div>
          <div class="col-lg-2">
          <input type="checkbox" name="report" id="report" class="report" value="2"> <strong>Purchase Listing Table</strong>
          </div>
           <div class="col-lg-2">
          <input type="checkbox" name="report" id="report" class="report" value="3"> <strong>Supply Listing Table</strong>
          </div>
           <div class="col-lg-2">
          <input type="checkbox" name="report" id="report" class="report" value="4"> <strong>General Ledger Table</strong>
          </div>
           <div class="col-lg-2">
          <input type="checkbox" name="report" id="report" class="report" value="5" checked> <strong>Select All</strong>
          </div>
          <input type="hidden" id="test" value="sd">
        </div>
      </form>

 
    <a href="javascript:void(0)" target='_blank' class="btn btn-primary" onclick="generateExcel();">Excel</a>
 
    <a href="javascript:void(0)" class="btn btn-primary" onclick="generateXML();">XML</a>

    </div>

    </div>

    <script type="text/javascript">

    </script>
  



</div>
</div>
<script type="text/javascript">
/* var nowTemp = new Date();
var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
 
var checkin = $('#from_date').datepicker({
  onRender: function(date) {
    return date.valueOf() < now.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  if (ev.date.valueOf() > checkout.date.valueOf()) {
    var newDate = new Date(ev.date)
    newDate.setDate(newDate.getDate() + 1);
    checkout.setValue(newDate);
  }
  checkin.hide();
  $('#to_date')[0].focus();
}).data('datepicker');
var checkout = $('#to_date').datepicker({
  onRender: function(date) {
    return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  checkout.hide();
}).data('datepicker'); */
    function generateXML() {
      var from = $("#from_date").val();
      var to = $("#to_date").val();
      var vals ='';
     var checkboxes = document.getElementsByName('report');
      for (var i=0, n=checkboxes.length;i<n;i++) {
        if (checkboxes[i].checked) 
        {
          if(vals=='') {
            vals += checkboxes[i].value;
          } else {
            vals += ","+checkboxes[i].value;
          }
        }
      }
     
      window.open('<?php echo $this->sitePath; ?>reports/index/iras-audit-file-xml/fromDate/'+from+'/toDate/'+to+'/reportType/'+vals);
    }

    function generateExcel() {
      var from = $("#from_date").val();
      var to = $("#to_date").val();
      var vals ='';
     var checkboxes = document.getElementsByName('report');
      for (var i=0, n=checkboxes.length;i<n;i++) {
        if (checkboxes[i].checked) 
        {
          if(vals=='') {
            vals += checkboxes[i].value;
          } else {
            vals += ","+checkboxes[i].value;
          }
        }
      }
     
      window.open('<?php echo $this->sitePath; ?>reports/index/iras-audit-file-excel/fromDate/'+from+'/toDate/'+to+'/reportType/'+vals);
    }
</script>