<?php
$logSession = new Zend_Session_Namespace('sess_login');
if(isset($logSession->proxy_name) && !empty($logSession->proxy_name)) {
  $company_name = ucfirst($logSession->proxy_name);
} else {
  $company_name = ucfirst($logSession->name);
}
?>
<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."reports"; ?>">Reports</a></li>
   <li><a href="<?php echo $this->sitePath."reports/index/sales-tax"; ?>">Sales Tax</a></li>
   <li class="active"><?php echo $this->code; ?></li>
</ul>



    <div class="row">
      <div class="col-md-2 pull-right">
          <button class="print btn btn-inverse" type="button" rel="content"><i class="icon-print"></i> Print</button>
          <button class="btn btn-inverse" type="button"  onclick="tableToExcel('content', 'Sales Tax')"><i class="icon-file-excel"></i> Excel</button>
      </div>
    </div>

<?php
  $type = '';
  if($this->sales==1) {
    $type = 'Supply';
  } else if($this->sales==2) {
    $type = 'Purchase';
  }
?>
  <div class="row">
    <div class="col-md-12">
           <h4 align="center"><?php echo $company_name; ?> </h4> 
           <h4 align="center">Sales <?php echo $type; ?> Tax</h4> 
           <h4 align="center"><?php echo $this->code; ?></h4>
           <h4 align="center">Dated From <?php echo $this->from; ?> To <?php echo $this->to; ?></h4> 
    </div>
    <div class="col-md-8 col-md-offset-2">
     <div class="box-widget" style="margin-bottom:0px;">
        <div class="widget-head clearfix">
            <span class="h-icon"><i class="icon-power-cord"></i></span>
            <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;"><?php echo $this->code; ?></a></h4>
        </div>
        <div class="widget-container">
        <div class="widget-block">
        <div class="widget-content">
        <table class="table responsive">
            <thead>
              <tr>
                 <th>Date</th>
                 <th>
                    Transaction No
                 </th>
                 <th style="text-align:right;">
                    GST Base
                 </th>
                 <th style="text-align:right;">
                    GST
                 </th>
              </tr>
            </thead>
            <tbody>
             

             <?php 
                $amount = 0.00;
                $tax_amount = 0.00;
                foreach ($this->tax as $key => $sale) {
                  foreach ($sale as $keys => $value) {
                    $amount += $value['amount'];
                    $tax_amount += $value['tax_amount'];
                  /*foreach ($this->taxes as $tax) {
                    if($tax['id']==$key) {
                      foreach ($this->supply as $keys => $supply) {
                        if($tax['tax_code']==$keys) {
                          $code = $supply['name'];
                        }
                      }
                    }
                  }*/
              ?>


              <tr>

                <td><?php echo date('d-m-Y',strtotime($value['date'])); ?></td>
                <td><?php echo $value['no']; ?></td>
                <td style="text-align:right;">
                <?php 
                  if($value['amount']<0) {
                    echo "(".number_format(abs($value['amount']),2,'.',',').")"; 
                  } else {
                    echo number_format($value['amount'],2,'.',',');
                  }
                ?>
                </td>
                <td style="text-align:right;">
                <?php 
                 if($value['tax_amount']<0) {
                    echo "(".number_format(abs($value['tax_amount']),2,'.',',').")"; 
                  } else {
                    echo number_format($value['tax_amount'],2,'.',',');
                  }
                ?>
                </td>

              </tr>


              <?php 
                  }
                }
              ?>


              <tr>

                <td colspan="2"><strong>Total</strong></td>
                <td style="text-align:right;">
                <?php 
                  if($amount<0) {
                    echo "(".number_format(abs($amount),2,'.',',').")"; 
                  } else {
                    echo number_format($amount,2,'.',',');
                  }
                ?>
                </td>
                <td style="text-align:right;">
                <?php 
                 if($tax_amount<0) {
                    echo "(".number_format(abs($tax_amount),2,'.',',').")"; 
                  } else {
                    echo number_format($tax_amount,2,'.',',');
                  }
                ?>
                </td>

              </tr>
                              

            </tbody>
        </table>
        </div>
        </div>
        </div>
        </div>
    </div>

    


  </div>

<!--   <div class="row">
        <div class="col-md-12">
        <?php 
          $net_profit = $total_income - $total_expense;
        ?>
        <h4>Net Profit : 
        <?php
         if($net_profit<0) {
            $negative_format = "(".number_format(abs($net_profit),2,'.',',').")";
            echo $negative_format;
         } else {
            echo number_format($net_profit,2,'.',',');
         }
        ?></h4>
        </div>
  </div>
 -->
</div>
</div>

<div id="content" style="display:none;">
      <h4 align="center"><?php echo $company_name; ?> </h4> 
           <h4 align="center">Sales <?php echo $this->code; ?> Tax</h4> 
           <h4 align="center"><?php echo $this->code; ?></h4>
           <h4 align="center">Dated From <?php echo $this->from; ?> To <?php echo $this->to; ?></h4>  
        <table class="table responsive" border="0" align="center" cellpadding="7" cellspacing="7" width="100%">
            <thead>
              <tr>
                 <th>Date</th>
                 <th>
                    Transaction No
                 </th>
                 <th style="text-align:right;">
                    GST Base
                 </th>
                 <th style="text-align:right;">
                    GST
                 </th>
              </tr>
            </thead>
            <tbody>
             

             <?php 
                $amount = 0.00;
                $tax_amount = 0.00;
                foreach ($this->tax as $key => $sale) {
                  foreach ($sale as $keys => $value) {
                    $amount += $value['amount'];
                    $tax_amount += $value['tax_amount'];
                  /*foreach ($this->taxes as $tax) {
                    if($tax['id']==$key) {
                      foreach ($this->supply as $keys => $supply) {
                        if($tax['tax_code']==$keys) {
                          $code = $supply['name'];
                        }
                      }
                    }
                  }*/
              ?>


              <tr>

                <td><?php echo date('d-m-Y',strtotime($value['date'])); ?></td>
                <td><?php echo $value['no']; ?></td>
                <td style="text-align:right;">
                <?php 
                  if($value['amount']<0) {
                    echo "(".number_format(abs($value['amount']),2,'.',',').")"; 
                  } else {
                    echo number_format($value['amount'],2,'.',',');
                  }
                ?>
                </td>
                <td style="text-align:right;">
                <?php 
                 if($value['tax_amount']<0) {
                    echo "(".number_format(abs($value['tax_amount']),2,'.',',').")"; 
                  } else {
                    echo number_format($value['tax_amount'],2,'.',',');
                  }
                ?>
                </td>

              </tr>


              <?php 
                  }
                }
              ?>


              <tr>

                <td colspan="2"><strong>Total</strong></td>
                <td style="text-align:right;">
                <?php 
                  if($amount<0) {
                    echo "(".number_format(abs($amount),2,'.',',').")"; 
                  } else {
                    echo number_format($amount,2,'.',',');
                  }
                ?>
                </td>
                <td style="text-align:right;">
                <?php 
                 if($tax_amount<0) {
                    echo "(".number_format(abs($tax_amount),2,'.',',').")"; 
                  } else {
                    echo number_format($tax_amount,2,'.',',');
                  }
                ?>
                </td>

              </tr>
                              

            </tbody>

        </table>


</div>
<script type="text/javascript">
/* var nowTemp = new Date();
var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
 
var checkin = $('#from_date').datepicker({
  onRender: function(date) {
    return date.valueOf() < now.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  if (ev.date.valueOf() > checkout.date.valueOf()) {
    var newDate = new Date(ev.date)
    newDate.setDate(newDate.getDate() + 1);
    checkout.setValue(newDate);
  }
  checkin.hide();
  $('#to_date')[0].focus();
}).data('datepicker');
var checkout = $('#to_date').datepicker({
  onRender: function(date) {
    return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  checkout.hide();
}).data('datepicker'); */
</script>
<script type="text/javascript">

  (function ($) {
  var rules = document.styleSheets[document.styleSheets.length-1].cssRules;
  for (var idx = 0, len = rules.length; idx < len; idx++) {
    $(rules[idx].selectorText).each(function (i, elem) {
      elem.style.cssText += rules[idx].style.cssText;
    });
  }
  $('style').remove();
})(jQuery);

var tableToExcel = (function() {
  var uri = 'data:application/vnd.ms-excel;base64,'
    , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
    , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
    , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
  return function(table, name) {
    if (!table.nodeType) table = document.getElementById(table)
    var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML}
    window.location.href = uri + base64(format(template, ctx))
  }
})()
</script>