
<div class="row">
<div class="col-md-12 widget-module">
<div class="box-widget">
          <div class="widget-head clearfix">
             <span class="h-icon"><i class="icon-menu"></i></span>
              <h4 class="pull-left">Add Customer</h4>
                                    
           </div>
<div class="widget-container">
          <div class="widget-block">
             <div class="widget-content box-padding">
          <form class="form-horizontal" id="add-customer" method="post">
					<div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Customer / Company Name <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="customer_name"  name="customer_name"  class="form-control" />
                                        </div>
                                    <label class="col-lg-2 control-label">Customer ID</label>
                                        <div class="col-lg-3">
                                            <input type="text" id="customer_id" readonly name="customer_id"  class="form-control" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Address Line 1 <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="address1"  name="address1"  class="form-control" />
                                        </div>
                                    <label class="col-lg-2 control-label">Customer Company Reg No <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="customer_reg_no" name="customer_reg_no"  class="form-control" />
                                        </div>
                            </div>

                             <div class="form-group">
                                    <label class="col-lg-2 control-label">Address Line 2 </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="address2"  name="address2"  class="form-control" />
                                        </div>
                                    <label class="col-lg-2 control-label">Main Office Number <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="office_number" name="office_number"  class="form-control" />
                                        </div>
                            </div>

                             <div class="form-group">
                                    <label class="col-lg-2 control-label">City <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="city"  name="city"  class="form-control" />
                                        </div>
                                    <label class="col-lg-2 control-label">Fax Number </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="fax_number" name="fax_number"  class="form-control" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">State <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="state"  name="state"  class="form-control" />
                                        </div>
                                    <label class="col-lg-2 control-label">Website </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="website" name="website"  class="form-control" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Country <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="state"  name="state"  class="form-control" />
                                        </div>
                                    <label class="col-lg-2 control-label">General Email </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="email" name="email"  class="form-control" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Company GST No <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="company_gst_no"  name="company_gst_no"  class="form-control" />
                                        </div>
                                    <label class="col-lg-2 control-label">Postcode <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="postcode" name="postcode" class="form-control" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Date GST Status Verified <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="gst_status"  name="gst_status"  class="form-control date-pick" />
                                        </div>
                            </div>

                            <div class="form-group">
                             <label class="col-lg-2 control-label">Shipping Address</label>
                                    <div class="col-lg-3">
                                        <a href="javascript:void(0)" id="shipping" class="btn btn-primary green" type="button" >Add Shipping Address</a>
                                    </div>
                            </div>

                            <div id="shipping_detail">


                            </div>

                            <div class="form-group">
                             <label class="col-lg-2 control-label">Key Contact Person(s)</label>
                                    <div class="col-lg-3">
                                        <a href="javascript:void(0)" id="key_contact" class="btn btn-primary green" type="button" >Key Contact Persons</a>
                                    </div>
                            </div>


                            <div class="form-group">
                            <label class="col-lg-5 control-label">&nbsp</label>
                                <div class="col-lg-4">
                                        <div class="form-actions">
                                            <input type="submit" name="submit" class="btn btn-primary" value="Save" />
                                            <button type="reset" class="btn">Cancel</button>
                                        </div>
                            	</div>
                            </div>
                    </div>
                                       
          </form>
          </div>
          </div>
          </div>
</div>
</div>
</div>
<script type="text/javascript">
        var counter = 1;
    $("#shipping").on("click", function () {
         if(counter>5){
                    alert("Only 5 shipping address allowed");
                    return false;
         }   

         var newTextBoxDiv = $(document.createElement('div'))
              .attr("id", 'TextBoxDiv' + counter);

         newTextBoxDiv.html('<div class="form-group">' +
        '<label class="col-lg-2 control-label">Address Line 1 </label>' + 
        '<div class="col-lg-3">' +  
        '<input type="text" name="shipping_address_one' + counter + 
        '" id="shipping_address' + counter + '" class="form-control" value="" ></div>' +
        '<label class="col-lg-2 control-label">City </label>' + 
        '<div class="col-lg-3">' +
        '<input type="text" name="shipping_city' + counter + 
        '" id="shipping_city' + counter + '"  class="form-control" value="" ></div>' +
        '&nbsp;<a href="javascript:void(0)" value="removeButton" class="remove_shipping">Remove</a></div>');

         newTextBoxDiv.appendTo("#shipping_detail");

         counter++;
    });

$(document).on('click',".remove_shipping",function (){   
        if(counter==1){
            alert("No more shipping addresses to remove");
            return false;
        }   

        counter--;

        $("#TextBoxDiv" + counter).remove();

    });

</script>
