<div id="popup">
<span class="button b-close"><span>X</span></span>


 <div class="row" id="other_accounts" style="display:none;">
<h3>Add COA</h3>
<hr/>
 <div class="widget-container col-md-12 col-md-offset-1">
     <form class="form-horizontal" id="add-coa" method="post">
         <div class="form-group">
            <label class="col-lg-3 control-label">Account Name</label>
              <div class="col-lg-7">
                <input type="hidden" name="action" id="action" value="add_coa">
                <input type="hidden" name="oth_acc_type" id="oth_acc_type" value="1" />
                <input type="hidden" name="oth_acc_l1" id="oth_acc_l1" value="1" />
                <input type="hidden" name="oth_acc_l2" id="oth_acc_l2" value="5" />
                <input type="text" name="oth_acc_name" id="oth_acc_name" class="form-control" />
              </div>
        </div>
<!--         <div class="form-group hidden_details">
            <label class="col-lg-3 control-label">Payment / Accruals Account</label>
              <div class="col-lg-7">
               <input type="checkbox" name="pay_account" id="pay_account" value="1" checked />
               &nbsp; This account is for receipt / payment of money (e.g., cash equivalents) or  to record receivables/ payables
              </div>
        </div> -->
        <div class="form-group">
            <label class="col-lg-3 control-label">Currency</label>
                <div class="col-lg-7">
                    <select name="currency" class="form-control">
                            <?php 
                              $logSession = new Zend_Session_Namespace('sess_login');
                               $currencySelect = '';
                                if(isset($this->currencies) && !empty($this->currencies)) {
                                foreach ($this->currencies as $key => $currencies) {
                                 /* if(isset($logSession->currency) && !empty($logSession->currency)  && $key==$logSession->currency ) {
                                            $currencySelect = 'selected';
                                   } 
                                    else */if($key=="SGD"){
                                        $currencySelect = 'selected';
                                    }
                                   else { 
                                        $currencySelect = '';
                                    }
                            ?>
                    <option value="<?php echo $key?>" <?php echo $currencySelect; ?>><?php echo $currencies; ?></option>
                            <?php
                                    }
                                } 
                            ?>
                    </select>  
                 </div>
                </div>


<div class="form-group">
    <label class="col-lg-2 control-label">&nbsp;</label>
    <div class="col-lg-3">
       <div class="form-actions">
          <button type="submit" id="save" class="btn btn-primary">Save</button>
          <button type="reset" class="btn b-close">Close</button>
      </div>
   </div>
  </div>

     </form>
 </div>
</div>



</div>

 <ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."business/customer/"; ?>">Customer</a></li>
   <li class="active">Copy</li>
</ul>
 

  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
<div class="row">
<div class="col-md-12 widget-module">
<div class="box-widget">
          <div class="widget-head clearfix">
             <span class="h-icon"><i class="icon-menu"></i></span>
              <h4 class="pull-left">Copy Customer</h4>
                                    
           </div>
<div class="widget-container">
          <div class="widget-block">
             <div class="widget-content box-padding">
          		<form class="form-horizontal" id="add-customer" method="post">
					<div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Customer / Company Name <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="customer_name"  name="customer_name"  class="form-control"  onchange="checkCustomer(this.value,'<?php echo $this->customer[0]['id']; ?>');"  autocomplete="off" />
                                            <label for="customer_name" generated="true" class="error customer_error" style="display:none;"></label>
                                        </div>
                                    <label class="col-lg-2 control-label">Customer ID</label>
                                        <div class="col-lg-3">
                                            <input type="text" id="customer_id" readonly name="customer_id"  class="form-control"  value="<?php echo $this->customer[0]['customer_id']; ?>"  autocomplete="off" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Address Line 1 <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="address1"  name="address1"  class="form-control" value="<?php echo $this->customer[0]['address1']; ?>" autocomplete="off"  />
                                        </div>
                                    <label class="col-lg-2 control-label">Customer Company Reg No <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="customer_reg_no" name="customer_reg_no"  class="form-control" value="<?php echo $this->customer[0]['company_registration_no']; ?>"  autocomplete="off"/>
                                        </div>
                            </div>

                             <div class="form-group">
                                    <label class="col-lg-2 control-label">Address Line 2 </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="address2"  name="address2"  class="form-control" value="<?php echo $this->customer[0]['address2']; ?>"  autocomplete="off"/>
                                        </div>
                                    <label class="col-lg-2 control-label">Main Office Number <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="office_number" name="office_number"  class="form-control" value="<?php echo $this->customer[0]['office_number']; ?>" autocomplete="off" />
                                        </div>
                            </div>

                             <div class="form-group">
                                    <label class="col-lg-2 control-label">City <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="city"  name="city"  class="form-control" value="<?php echo ucfirst($this->customer[0]['city']); ?>"  autocomplete="off"/>
                                        </div>
                                    <label class="col-lg-2 control-label">Fax Number </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="fax_number" name="fax_number"  class="form-control" value="<?php echo $this->customer[0]['fax_number']; ?>" autocomplete="off" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">State </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="state"  name="state"  class="form-control" value="<?php echo ucfirst($this->customer[0]['state']); ?>"  autocomplete="off"/>
                                        </div>
                                    <label class="col-lg-2 control-label">Website </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="website" name="website"  class="form-control" value="<?php echo $this->customer[0]['website']; ?>" autocomplete="off"/>
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Country <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                             <select name="country" class="form-control">
                                                        <?php 
                                                            $countrySelect = '';
                                                            if(isset($this->countries) && !empty($this->countries)) {
                                                                foreach ($this->countries as $key => $countries) {
                                                                    if(isset($this->customer[0]['country']) && !empty($this->customer[0]['country'])  && $key==$this->customer[0]['country'])
                                                                        $countrySelect = 'selected';
                                                                    else 
                                                                        $countrySelect = '';
                                                        ?>
                    <option value="<?php echo $key?>" <?php echo $countrySelect; ?>><?php echo ucfirst($countries); ?></option>
                                                        <?php
                                                                }
                                                            } 
                                                        ?>
                                                    </select> <br/>
                                                    <label for="country" generated="true" class="error"></label>
                                        </div>
                                    <label class="col-lg-2 control-label">General Email </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="email" name="email"  class="form-control" value="<?php echo $this->customer[0]['email']; ?>" autocomplete="off"/>
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Company GST No </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="company_gst_no"  name="company_gst_no"  class="form-control" value="<?php echo $this->customer[0]['company_gst_no']; ?>" autocomplete="off" />
                                        </div>
                                    <label class="col-lg-2 control-label">Postcode <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="postcode" name="postcode" class="form-control" value="<?php echo $this->customer[0]['postcode']; ?>" autocomplete="off" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-2 control-label">Date GST Status Verified </label>
                                        <div class="col-lg-3">
                                            <input type="text" id="gst_status" readonly name="gst_status"  autocomplete="off" class="form-control date-pick" value="<?php if($this->customer[0]['gst_verified_date']==0) { echo ""; } else { echo date("d-m-Y",strtotime($this->customer[0]['gst_verified_date'])); } ?>" />
                                        </div>
                                        <label class="col-lg-2 control-label">COA <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                             <select name="coa_link" id="coa_link" class="form-control" required>
                                             <?php 
                                                if($this->customer[0]['coa_link']==3) {
                                             ?>
                                                <option value="3" selected>Trade Receivables</option>
                                                <option value="4">Account Receivables - Others</option>
                                             <?php
                                                } else if($this->customer[0]['coa_link']==4) {
                                             ?>
                                                <option value="3">Trade Receivables</option>
                                                <option value="4" selected>Account Receivables - Others</option>
                                             <?php 
                                                } else {
                                            ?>
                                                <option value="3">Trade Receivables</option>
                                                <option value="4">Account Receivables - Others</option>
                                            <?php
                                                }
                                            ?>
                                            <?php
                                                if(isset($this->otherReceivable) && !empty($this->otherReceivable)) {
                                                  foreach ($this->otherReceivable as $receivable) {
                                                    if($this->customer[0]['coa_link']==$receivable['id'])
                                                        $receivable_select = 'selected';
                                                    else
                                                        $receivable_select = '';
                                              ?>
                                                <option value="<?php echo $receivable['id']; ?>" <?php echo $receivable_select; ?>><?php echo ucfirst($receivable['account_name']); ?></option>
                                              <?php
                                                  }
                                                }
                                              ?>
                                              
                                            </select>
                                            <a href="javascript:void(0)" title="Click to add account" data-title="Click to add new account" target="_blank" id="add-account" onclick="addCoa();"><i class="icon-plus-circle-2"></i> Add Account</a>

                                        </div>
                            </div>

                            <!-- <div class="form-group">

                                     <label class="col-lg-2 control-label">Other COA </label>
                                        <div class="col-lg-3">
                                             <select name="other_coa_link[]" id="other_coa_link" class="select2" multiple>
                                              <?php
                                                $receivable_link = explode(",", $this->customer[0]['other_coa_link']);
                                                if(isset($this->otherReceivable) && !empty($this->otherReceivable)) {
                                                  foreach ($this->otherReceivable as $receivable) {
                                                    if(in_array($receivable['id'], $receivable_link))
                                                        $receivable_select = 'selected';
                                                    else
                                                        $receivable_select = '';
                                              ?>
                                                <option value="<?php echo $receivable['id']; ?>" <?php echo $receivable_select; ?>><?php echo $receivable['account_name']; ?></option>
                                              <?php
                                                  }
                                                }
                                              ?>
                                            </select> <br/>
                                            <a href="javascript:void(0)" title="Click to add account" data-title="Click to add new account" target="_blank" id="add-account" onclick="addCoa();"><i class="icon-plus-circle-2"></i> Add Account</a>
                                        </div>
                            </div> -->


                            <div class="form-group">
                             <label class="col-lg-2 control-label">Shipping Address</label>
                                    <div class="col-lg-3">
                                        <a href="javascript:void(0)" id="shipping" class="btn btn-primary green" type="button" >Add Shipping Address</a>
                                    </div>
                            </div>

                            <div id="shipping_detail">
                                <?php
                                    $i=1;
                                    if(isset($this->shipping) && !empty($this->shipping)) {
                                        foreach($this->shipping as $shipping) {
                                ?>
                                    <div id="TextBoxDiv<?php echo $i; ?>">

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label"><h5><b>Shipping Address - <?php echo $i; ?></b></h5> </label>
                                    </div>
                                    <div class="form-group">
                                         <label class="col-lg-2 control-label">Address Line 1<span class="mandatory">*</span> </label>
                                    <div class="col-lg-3"> 
                                        <input type="text" name="shipping_address_one_<?php echo $i; ?>" id="shipping_address_one_<?php echo $i; ?>" autocomplete="off" required class="form-control" value="<?php echo $shipping['shipping_address1'] ?>" >
                                    </div> 
                                        <label class="col-lg-2 control-label">City <span class="mandatory">*</span></label>
                                    <div class="col-lg-3">
                                        <input type="text" name="shipping_city_<?php echo $i; ?>" id="shipping_city_<?php echo $i; ?>" required class="form-control" autocomplete="off" value="<?php echo ucfirst($shipping['shipping_city']) ?>">
                                     </div>
                                    </div>
                                    <div class="form-group">
                                         <label class="col-lg-2 control-label">Address Line 2 </label> 
                                    <div class="col-lg-3">  
                                            <input type="text" name="shipping_address_two_<?php echo $i; ?>" id="shipping_address_two_<?php echo $i; ?>" autocomplete="off" class="form-control" value="<?php echo $shipping['shipping_address2'] ?>" >
                                    </div>
                                        <label class="col-lg-2 control-label">State <span class="mandatory">*</span></label> 
                                    <div class="col-lg-3">
                                            <input type="text" name="shipping_state_<?php echo $i; ?>" id="shipping_state_<?php echo $i; ?>" required  class="form-control" autocomplete="off" value="<?php echo ucfirst($shipping['shipping_state']); ?>">
                                           
                                    </div>
                                    </div>
                                    <div class="form-group">
                                            <label class="col-lg-2 control-label">Country <span class="mandatory">*</span></label> 
                                    <div class="col-lg-3">
                                         <select name="shipping_country_<?php echo $i; ?>" id="shipping_country_<?php echo $i; ?>" class="form-control">
                                                        <?php 
                                                            $countrySelect = '';
                                                            if(isset($this->countries) && !empty($this->countries)) {
                                                                foreach ($this->countries as $key => $countries) {
                                                                    if(isset($shipping['shipping_country']) && !empty($shipping['shipping_country'])  && $key==$shipping['shipping_country'])
                                                                        $countrySelect = 'selected';
                                                                    else 
                                                                        $countrySelect = '';
                                                        ?>
                    <option value="<?php echo $key?>" <?php echo $countrySelect; ?>><?php echo ucfirst($countries); ?></option>
                                                        <?php
                                                                }
                                                            } 
                                                        ?>
                                                    </select>

                                    </div>
                                        <label class="col-lg-2 control-label">Postal Code <span class="mandatory">*</span></label> 
                                    <div class="col-lg-3">
                                         <input type="text" name="shipping_postal_code_<?php echo $i; ?>" id="shipping_postal_code_<?php echo $i; ?>"  autocomplete="off" required class="form-control" value="<?php echo $shipping['shipping_postcode'] ?>" >
                                    </div>
                                     <input type="hidden" name="ship_id_<?php echo $i; ?>" id="ship_id_<?php echo $i; ?>" value="<?php echo $shipping['id']; ?>" />
                                    </div>

                                    </div>
                                <?php
                                       $i++;
                                        }
                                    }
                                ?>

                            </div>

                            <div class="form-group">
                             <label class="col-lg-2 control-label">Key Contact Person(s)</label>
                                    <div class="col-lg-3">
                                        <a href="javascript:void(0)" id="key_contact" class="btn btn-primary green" type="button" >Add Key Contact Person</a>
                                    </div>
                            </div>

							<div id="key_contact_detail">
                                <?php
                                   $j=1;
                                    if(isset($this->contacts) && !empty($this->contacts)) {
                                        foreach($this->contacts as $contact) {
                                ?>
                                    <div id="TextBoxDivs<?php echo $j; ?>">

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label"><h5><b>Key Contact Person - <?php echo $j; ?></b></h5> </label>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label">Contact Person Name<span class="mandatory">*</span> </label>
                                    <div class="col-lg-3">  
                                        <input type="text" autocomplete="off" name="key_contact_person_<?php echo $j; ?>" id="key_contact_person_<?php echo $j; ?>" required class="form-control" value="<?php echo ucfirst($contact['contact_name']); ?>" />
                                    </div>
                                        <label class="col-lg-2 control-label">Designation/Title <span class="mandatory">*</span></label>
                                    <div class="col-lg-3">
                                        <input type="text" autocomplete="off" name="key_designation_<?php echo $j; ?>" id="key_designation_<?php echo $j; ?>" required  class="form-control" value="<?php echo ucfirst($contact['designation']); ?>" />
                                    </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label">Contact Number - Office </label>
                                    <div class="col-lg-3">
                                        <input type="text" autocomplete="off" name="key_contact_office_<?php echo $j; ?>" id="key_contact_office_<?php echo $j; ?>" class="form-control" value="<?php echo $contact['contact_office_number']; ?>" />
                                    </div>
                                    <label class="col-lg-2 control-label">Email </label>
                                    <div class="col-lg-3">
                                        <input type="email" autocomplete="off" name="key_email_<?php echo $j; ?>" id="key_email_<?php echo $j; ?>"  class="form-control" value="<?php echo $contact['contact_email']; ?>" />
                                    </div>
                                    </div>
                                    <div class="form-group">
                                       <label class="col-lg-2 control-label">Contact Number - Mobile </label>
                                    <div class="col-lg-3">
                                        <input type="text" autocomplete="off" name="key_contact_mobile_<?php echo $j; ?>" id="key_contact_office_<?php echo $j; ?>" class="form-control" value="<?php echo $contact['contact_mobile_number']; ?>" />
                                    </div>
                                        <label class="col-lg-2 control-label">Default Key Person to Contact? <span class="mandatory">*</span></label>
                                    <div class="col-lg-3">
                                        <select name="key_default_person_<?php echo $j; ?>" id="key_default_person_<?php echo $j; ?>" required class="form-control" onchange="return key_default(this.value,'<?php echo $j; ?>',this.id);">
                                        <?php 
                                            if($contact['default_key_contact']==1) {
                                        ?>
                                            <option value="1" selected>Yes</option>
                                            <option value="2">No</option>
                                        <?php 
                                            } else if($contact['default_key_contact']==2) {
                                        ?>
                                            <option value="1">Yes</option>
                                            <option value="2" selected>No</option>
                                        <?php 
                                            }
                                        ?>
                                        </select>
                                    </div>
                                     <input type="hidden" name="contact_id_<?php echo $i; ?>" id="contact_id_<?php echo $i; ?>" value="<?php echo $contact['id']; ?>" />
                                    </div>

                                    </div>

                                <?php
                                       $j++;
                                        }
                                    }
                                ?>

                            </div>
                            
                            <div class="form-group">
                            <label class="col-lg-5 control-label">&nbsp;</label>
                                <div class="col-lg-4">
                                        <div class="form-actions">
                                            <input type="hidden" name="update_shipping_counter" id="update_shipping_counter" value="<?php echo --$i; ?>" />
                                            <input type="hidden" name="update_contact_counter" id="update_contact_counter" value="<?php echo --$j; ?>" />
                                            <input type="hidden" name="shipping_counter" id="shipping_counter" value="<?php echo $i; ?>"  />
                                            <input type="hidden" name="contact_counter" id="contact_counter" value="<?php echo $j; ?>" />
                                            <input type="submit" name="submit" class="btn btn-primary" value="Save" />
                                            <button type="button" class="btn" onclick="return back();">Cancel</button>
                                        </div>
                            	</div>
                            </div>
                    </div>
                                       
          </form>
          </div>
          </div>
          </div>
</div>
</div>
</div>
<script type="text/javascript">

$(function() {
            $("#add-coa").validate({
                rules: {
                    oth_acc_name: {
                        required: true
                    }, 
                    currency: {
                        required: true,
                    },
                }, 
                invalidHandler: function(form, validator) {
                    var errors = validator.numberOfInvalids();
                    if (errors) {
                        var message = errors == 1
                        ? 'You missed 1 field. It has been highlighted'
                        : 'You missed ' + errors + ' fields. They have been highlighted';
                        $("#da-ex-val1-error").html(message).show();
                    } else {
                        $("#da-ex-val1-error").hide();
                    }
                },
                submitHandler: function (form) {
                      $.ajax({
                          type: "POST",
                          url: "<?php echo $this->sitePath.'business/customer/ajax-call'; ?>",
                          data: $("#add-coa").serialize(),
                          success: function (html) {
                              if(html=='false') {
                                 alert("Unable to add COA. Kindly try again later");
                                 //return true;
                              } else if(html=='false1') {
                                 alert("Account Name already exists. Kindly try with different name");
                                 //return true;
                              } else  {
                                 var coa = $("#oth_acc_name").val();
                                 $("#coa_link").append('<option value="'+html+'">'+coa+'</option>');
                                 alert("Account Added Successfully");
                                 $("#popup").bPopup().close();
                              }

                          }
                        }); 
                    return false;
                }
            });
});
        var counter = <?php echo $i; ?>;
        counter++;
      //  var shipping_country = new Array();
    $("#shipping").on("click", function () {
         if(counter>5){
                alert("Only 5 shipping address allowed");
                return false;
         }   

        var shipping_country = '<select name="shipping_country_' +counter+ '" id="shipping_country_' +counter+ '"  class="form-control" required><option value="">Select Country</option>';

         <?php
            foreach ($this->countries as $key => $countries) {
         ?>
           // shipping_country['<?php echo $key ?>'] = '<?php echo addslashes($countries); ?>'
           shipping_country += '<option value="<?php echo $key ?>"><?php echo addslashes($countries); ?></option>';
         <?php
            }
         ?>

         shipping_country += '</select>';

         var newTextBoxDiv = $(document.createElement('div'))
              .attr("id", 'TextBoxDiv' + counter);

         newTextBoxDiv.html('<div class="form-group">'+'<label class="col-lg-2 control-label"><h5><b>Shipping Address - ' + counter +'</b>&nbsp;<a href="javascript:void(0)" value="removeButton" title="Remove" class="remove_shipping"><i class="icon-cancel-circle-2"></i></a></h5>  </label>'+'         </div>' + '<div class="form-group">' +
        '<label class="col-lg-2 control-label">Address Line 1<span class="mandatory">*</span> </label>' + 
        '<div class="col-lg-3">' +  
        '<input type="text" autocomplete="off" name="shipping_address_one_' + counter + 
        '" id="shipping_address_one_' + counter + '" required class="form-control" value="" ></div>' +
        '<label class="col-lg-2 control-label">City <span class="mandatory">*</span></label>' + 
        '<div class="col-lg-3">' +
        '<input type="text" autocomplete="off" name="shipping_city_' + counter + 
        '" id="shipping_city_' + counter + '" required class="form-control" value=""></div>'+'</div>' + '<div class="form-group">' +
        '<label class="col-lg-2 control-label">Address Line 2 </label>' + 
        '<div class="col-lg-3">' +  
        '<input type="text" autocomplete="off" name="shipping_address_two_' + counter + 
        '" id="shipping_address_two_' + counter + '" class="form-control" value="" ></div>' +
        '<label class="col-lg-2 control-label">State <span class="mandatory">*</span></label>' + 
        '<div class="col-lg-3">' +
        '<input type="text" autocomplete="off" name="shipping_state_' + counter + 
        '" id="shipping_state_' + counter + '" required  class="form-control" value="" ></div>'+'</div>'+
        '<div class="form-group">' +
        '<label class="col-lg-2 control-label">Country <span class="mandatory">*</span></label>' + 
        '<div class="col-lg-3">' + shipping_country  +
        '</div>' +
        '<label class="col-lg-2 control-label">Postal Code <span class="mandatory">*</span></label>' + 
        '<div class="col-lg-3">' +
        '<input type="text" autocomplete="off" name="shipping_postal_code_' + counter + 
        '" id="shipping_postal_code_' + counter + '" required class="form-control" value="" ></div>'+
        '</div>');

         newTextBoxDiv.appendTo("#shipping_detail");
         $("#shipping_counter").val(counter);
         counter++;
    });

    $(document).on('click',".remove_shipping",function (){   
        if(counter==1){
            alert("No more shipping addresses to remove");
            return false;
        }   

        counter--;

        $("#TextBoxDiv" + counter).remove();

    });
    
    var keycounter = <?php echo $j; ?>;
    keycounter++;
    $("#key_contact").on("click", function () {
         if(keycounter>5){
                alert("Only 5 contact persons allowed");
                return false;
         }   

         var default_contact =  '<select name="key_default_person_' + keycounter + '" id="key_default_person_' + keycounter + '" required class="form-control" onchange="return key_default(this.value,'+keycounter+',this.id);"><option value="">Select</option><option value="1">Yes</option><option value="2">No</option></select>';

         var newTextBoxDiv   = $(document.createElement('div'))
              .attr("id", 'TextBoxDivs' + keycounter);
        
        newTextBoxDiv.html('<div class="form-group">'+'<label class="col-lg-2 control-label"><h5><b>Key Contact Person - ' + keycounter +'</b>&nbsp;<a href="javascript:void(0)" value="removeButton" title="Remove" class="remove_key_contact"><i class="icon-cancel-circle-2"></i></a></h5> </label>'+'       </div>' + '<div class="form-group">' +
        '<label class="col-lg-2 control-label">Contact Person Name<span class="mandatory">*</span> </label>' + 
        '<div class="col-lg-3">' +  
        '<input type="text" autocomplete="off" name="key_contact_person_' + keycounter + 
        '" id="key_contact_person_' + keycounter + '" required class="form-control" value="" ></div>' +
        '<label class="col-lg-2 control-label">Designation/Title <span class="mandatory">*</span></label>' + 
        '<div class="col-lg-3">' +
        '<input type="text" autocomplete="off" name="key_designation_' + keycounter + 
        '" id="key_designation_' + keycounter + '" required  class="form-control" value="" ></div>'+'</div>' + '<div class="form-group">' +
        '<label class="col-lg-2 control-label">Contact Number - Office </label>' + 
        '<div class="col-lg-3">' +  
        '<input type="text" autocomplete="off" name="key_contact_office_' + keycounter + 
        '" id="key_contact_office_' + keycounter + '" class="form-control" value="" ></div>' +
        '<label class="col-lg-2 control-label">Email </label>' + 
        '<div class="col-lg-3">' +
        '<input type="email" autocomplete="off" name="key_email_' + keycounter + 
        '" id="key_email_' + keycounter + '"  class="form-control" value="" ></div>'+'</div>'+
        '<div class="form-group">' +
        '<label class="col-lg-2 control-label">Contact Number - Mobile </label>' + 
        '<div class="col-lg-3">' +  
        '<input type="text" autocomplete="off" name="key_contact_mobile_' + keycounter + 
        '" id="key_contact_office_' + keycounter + '"  class="form-control" value="" ></div>' +
        '<label class="col-lg-2 control-label">Default Key Person to Contact? <span class="mandatory">*</span></label>' + 
        '<div class="col-lg-3">' + default_contact +
        '</div>'+
        '</div>');

         newTextBoxDiv.appendTo("#key_contact_detail");

         $("#contact_counter").val(keycounter);

         keycounter++;
    });

$(document).on('click',".remove_key_contact",function (){   
        if(keycounter==1){
            alert("No more contact persons to remove");
            return false;
        }   

        keycounter--;

        $("#TextBoxDivs" + keycounter).remove();
        $("#contact_counter").val(keycounter-1);

    });

    function key_default(values,counts,ids) {
        if(value==2) {
            for(var i=1; i<=counts.length;i++) {
                if('key_default_person_'+i != ids) {
                    
                }
            }
        }
    }

    function checkCustomer(value) {
        if((value!='')) {
            $.ajax({
              type: "POST",
              url: "<?php echo $this->sitePath.'business/customer/ajax-call'; ?>",
              data: 'action=check_customer&customer_name='+value,
              success: function (html) {
                  if(html=='1') {
                     $(".customer_error").html("");
                     $(".customer_error").hide();
                     return true;
                  } else if(html=='2') {
                     $(".customer_error").html("Customer name "+ value +" already exists");
                     $("#customer_name").val("");
                     $(".customer_error").show();
                  }
              }
            }); 
        } 
   }

    function back() {
        window.location.href='<?php echo $this->sitePath; ?>business/customer';
    }

    function addCoa() {
        $("#other_accounts").show();
        $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', //uses jQuery easing plugin
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], //x, y
        });
    }

</script>
