 <ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li class="active">Customer</li>
</ul>
  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
   <?php
    $logSession = new Zend_Session_Namespace('sess_login');
   ?>
   <?php 
        if($logSession->type!=5 && $logSession->proxy_type!=5) {
   ?>
   <div class="row">
       <div class="col-md-12 grid-spacing">
       <a href="<?php echo $this->sitePath."business/customer/add"; ?>" class="btn btn-primary" type="button" >Add New Customer</a>
            <!-- Element to pop up -->    
       </div>
   </div>
   <?php 
        }
    ?>
 <div class="row">
                        <div class="col-md-12">
                            <div class="box-widget">
                                <table class="table data-tbl-boxy responsive">
                                    <thead>
                                        <tr>
                                            <th>
                                                Customer ID
                                            </th>
                                            <th>
                                                Customer Name
                                            </th>
                                            <th>
                                                Main Office Number
                                            </th>
                                            <th>
                                                Key Contact Person
                                            </th>
                                            <th>
                                                Designation
                                            </th>
                                            <th>
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php 
                                        $i=1;
                                        foreach($this->result as $results) {
                                           
                                    ?>
                                        <tr>
                                        <td><a class="setView" href="<?php echo $this->sitePath."business/customer/edit/id/".base64_encode($results['cid']); ?>"><?php echo $results['customer_id'] ?></a></td>
                                        <td><a class="setView" href="<?php echo $this->sitePath."business/customer/edit/id/".base64_encode($results['cid']); ?>">
                                        <?php 
                                            echo ucfirst($results['customer_name']);
                                        ?>
                                        </a>
                                        </td>
                                        <td><a class="setView" href="<?php echo $this->sitePath."business/customer/edit/id/".base64_encode($results['cid']); ?>"><?php echo $results['office_number']; ?></a></td>
                                        <td><a class="setView" href="<?php echo $this->sitePath."business/customer/edit/id/".base64_encode($results['cid']); ?>"><?php echo ucfirst($results['contact_name']); ?></a></td>
                                        <td><a class="setView" href="<?php echo $this->sitePath."business/customer/edit/id/".base64_encode($results['cid']); ?>"><?php echo $results['designation']; ?></a></td>
                                        <td class="action-bar">

                                        <div class="btn-group col-md-1">
                                    <button data-toggle="dropdown" class="btn btn-small dropdown-toggle"> <span class="caret"></span></button>
                                    <ul class="dropdown-menu" style="min-width:0px !important;">
                                        <li><a href="<?php echo $this->sitePath."business/customer/view/id/".base64_encode($results['cid']); ?>">View</a></li>
                                        <li><a href="<?php echo $this->sitePath."business/customer/print/id/".base64_encode($results['cid']); ?>" target="_blank">Print</a></li>
                                         <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                        <li><a href="<?php echo $this->sitePath."business/customer/edit/id/".base64_encode($results['cid']); ?>">Edit</a></li>
                                        <li><a href="<?php echo $this->sitePath."business/customer/copy/id/".base64_encode($results['cid']); ?>">Copy</a></li>
                                        <li><a href="<?php echo $this->sitePath."transaction/invoice/add/customer/".$results['cid']; ?>">Create Invoice</a></li>
                                        <?php
                                            }
                                        ?>
                                        
                                        <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                        <li><a href="javascript:void(0)" class="widget-remove" onclick="return deleteCustomer('<?php echo base64_encode($results['cid']); ?>','<?php echo $results['customer_name']; ?>')">Delete</a></li>
                                        <?php
                                            }
                                        ?>
                                    </ul>
                                    </div>

                                                             
                                        </td>
                                        </tr>
                                    <?php 
                                        }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
<script type="text/javascript">
function deleteCustomer(Idvalue,Name) {
  var confirmMsg = confirm("Are you sure want to delete this customer? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>business/customer/index/delid/'+Idvalue+'/delname/'+Name;
    }
}
</script>