  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
<div class="row">
<div class="col-md-12 widget-module">
<div class="box-widget">
          <div class="widget-head clearfix">
             <span class="h-icon"><i class="icon-menu"></i></span>
              <h4 class="pull-left">Add Receipt</h4>
                                    
           </div>
<div class="widget-container">
          <div class="widget-block">
             <div class="widget-content box-padding">
          		<form class="form-horizontal" id="add-receipt" method="post" enctype="multipart/form-data">
					<div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                    <label class="col-lg-5 control-label">Receipt Name <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="text" id="receipt_name"  name="receipt_name"  class="form-control" />
                                        </div>
                            </div>

                            <div class="form-group">
                                    <label class="col-lg-5 control-label">Upload Receipts <span class="mandatory">*</span></label>
                                        <div class="col-lg-3">
                                            <input type="file" id="file"  name="file"  class="form-control" />
                                        </div>
                            </div>                         
                            
                            <div class="form-group">
                            <label class="col-lg-5 control-label">&nbsp;</label>
                                <div class="col-lg-4">
                                        <div class="form-actions">
                                            <input type="submit" name="submit" class="btn btn-primary" value="Upload" />
                                            <button type="reset" class="btn">Cancel</button>
                                        </div>
                            	</div>
                            </div>
                    </div>
                                       
          </form>
          </div>
          </div>
          </div>
</div>
</div>
</div>
<script type="text/javascript">


</script>
