<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/"; ?>">Settings</a></li>
   <li class="active">Import</li>
</ul>


<div class="row">
                        <div class="col-md-12 widget-module">
                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Import Data</h4>
                                </div>                                

                                <div class="widget-container col-md-12">
                                   
                                    <div class="col-sm-6 col-md-3">
                                        <div class="board-widget-wrap">
                                            <a href="<?php echo $this->sitePath."import/customers"; ?>"><i class="icon-user"></i><span class="board-widget-label">Customers</span><span class="board-widget-intro"> Import customer contacts, including names, addresses etc </span></a>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 col-md-3">
                                        <div class="board-widget-wrap">
                                            <a href="<?php echo $this->sitePath."import/vendors"; ?>"><i class="icon-user-4"></i><span class="board-widget-label">Vendors</span><span class="board-widget-intro"> Import vendor contacts, including names, addresses etc </span></a>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 col-md-3">
                                        <div class="board-widget-wrap">
                                            <a href="<?php echo $this->sitePath."import/coa"; ?>"><i class="icon-file-8"></i><span class="board-widget-label">Chart of Accounts</span><span class="board-widget-intro"> Import your chart of accounts, including names, types etc </span></a>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 col-md-3">
                                        <div class="board-widget-wrap">
                                            <a href="<?php echo $this->sitePath."import/products"; ?>"><i class="icon-bag"></i><span class="board-widget-label">Products and Services</span><span class="board-widget-intro"> Import your products and services, including names, descriptions, price etc </span></a>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 col-md-3">
                                        <div class="board-widget-wrap">
                                            <a href="<?php echo $this->sitePath."import/income"; ?>"><i class="icon-coin"></i><span class="board-widget-label">Income</span><span class="board-widget-intro"> Import your income transactions </span></a>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 col-md-3">
                                        <div class="board-widget-wrap">
                                            <a href="<?php echo $this->sitePath."import/expense"; ?>"><i class="icon-credit-2"></i><span class="board-widget-label">Expense</span><span class="board-widget-intro"> Import your expense transactions </span></a>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 col-md-3">
                                        <div class="board-widget-wrap">
                                            <a href="<?php echo $this->sitePath."import/invoice"; ?>"><i class="icon-indent-right"></i><span class="board-widget-label">Invoice</span><span class="board-widget-intro"> Import your expense transactions </span></a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>


</div>
</div>