<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."settings/"; ?>">Settings</a></li>
   <li><a href="<?php echo $this->sitePath."import"; ?>">Import</a></li>
   <li class="active">Products</li>
</ul>

<div class="row">

           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
	</div>
</div>

<div class="row">
 <div class="col-md-12 widget-module">
            <div class="square-widget widget-collapsible">
                <div class="widget-head clearfix">
                       <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Import Products and Services</h4>
                                    
                </div>

                <div>
                    <div class="col-md-6">
                        <div class="alert alert-warning" style="color:#000;">
                                <strong>Checklist before import!</strong> <br/><br/>
                                What format is your list? We can import CSV or EXCEL files.  <br/>

                                <a href="<?php echo $this->sitePath.$this->viewpath."ExcelImportProducts_Sample.xls"; ?>">Download a sample file</a> to see what we can import. 
                        </div>  
                    </div>


                    <div class="widget-container col-md-12" style="clear:both;">


                        <form class="form-horizontal" id="import-excel" method="post" enctype="multipart/form-data">

                            <div class="form-group">
                                 <div class="col-lg-3">
                                    <label>Upload your File </label><br/>
                                    <input type="file" name="file" id="file" class="form-control" />
                                 </div>
                            </div>

                            <div class="form-group">
                                <input type="submit" name="upload" class="btn btn-primary upload" id="upload" value="Import" />

                        </form>
                    </div>

                </div>

            </div>

 </div>                   
</div>


</div>
</div>