<?php
  $logSession = new Zend_Session_Namespace('sess_login');
?>

<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="add_receipt" style="display:none;">
<h4>Add Receipts</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-receipt" method="post">
<div class="form-group">
    <label class="control-label col-lg-4">Receipts <span class="mandatory">*</span></label>
      <div class="col-lg-5" id="receipt_add">
            <p>No Receipts Found</p>
      </div>
</div>
   <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="button" name="attach_receipts" class="btn btn-primary " id="attach_receipts" value="Attach Receipt" onclick="return addReceipt();" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>
</form>
</div>
</div>

<div class="row" id="add_payment" style="display:none;">
 <h4>Add Payment</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-payment" method="post">
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Date <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="hidden" name="income_id" id="income_id" />
            <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" value="<?php echo date('d-m-Y'); ?>" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment / Accruals Account <span class="mandatory">*</span></label>
        <div class="col-lg-5">
             <select class="form-control" name="pay_account" id="pay_account">
               <option value="">Select</option>  
                    <?php
                        if(isset($this->payAccount) && !empty($this->payAccount)) {
                            foreach ($this->payAccount as $payAccount) {
                    ?>
                        <option value="<?php echo $payAccount['id']; ?>"><?php echo $payAccount['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>     
                                                                     
              </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="pay_amount" id="pay_amount" class="form-control amount-align" placeholder="Enter Amount"  autocomplete="off"  onchange="return numberWithCommas(this.value,this.id);"  />
            <input type="hidden" name="pending_amount" id="pending_amount" class="form-control" autocomplete="off"   />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Method <span class="mandatory">*</span></label>
        <div class="col-lg-5">
          <select name="pay_method" id="pay_method" class="form-control">
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Bank Cheque / Draft No </label>
        <div class="col-lg-5">
            <input type="text" name="cheque_draft_no" id="cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Prompt Payment Discount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <select class="form-control" name="payment_discount" id="payment_discount" onchange="discountPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Discount Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="discount_payment_amount" id="discount_payment_amount" class="form-control" value="0" disabled  autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Additional Description / Notes </label>
        <div class="col-lg-5">
        <textarea name="description" id="description" class="form-control"></textarea>
        </div>
    </div>

     <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="submit" name="add_payment" class="btn btn-primary " id="add_payment" value="Add Payment" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>

</form>
</div>
</div>
</div>

<div class="row">

           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            <div class="alert alert-danger" id="failure" style="display:none;">
            </div>
            </div>
   </div>

   <?php 
        if($logSession->type!=5) {
   ?>
   <div class="row">
       <div class="col-md-12 grid-spacing">
       <a href="javascript:void(0)" class="btn btn-primary" type="button" onclick="showIncome();">Add Income</a>
            <!-- Element to pop up -->    
       </div>
   </div>

     <div class="row" id="add_income" style="display:none;">


                        <div class="col-md-12 widget-module">

                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> New Income Transaction</h4>

                                </div>

                                <div class="widget-container col-md-12">

                                <form class="form-horizontal" id="add-income" method="post" enctype="multipart/form-data">
                                        <div class="form-group">
                                            <div class="col-lg-3">
                                              <label>Date <span class="mandatory">*</span></label>
                                                <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->date) && !empty($this->date)) { echo $this->date; } else { echo date('d-m-Y'); } ?>" autocomplete="off"/>
                                            </div>
                                             
                                            <div class="col-lg-3">
                                            <label>Receipt No <span class="mandatory">*</span></label>
                                                <input type="text" name="receipt" id="receipt" class="form-control" placeholder="Enter Receipt No" value="<?php if(isset($this->receipt) && !empty($this->receipt)) { echo $this->receipt; } ?>" autocomplete="off">
                                            </div>    
                                            <div class="col-lg-2">
                                             <label>Customer / Payee <span class="mandatory">*</span></label>
                                                <select class="select2" name="customer" id="customer" onchange="return getReceipt(this.value);">
                                                <option value="">Select</option>  
                                                    <?php
                                                       $customerSelect = '';
                                                        if(isset($this->customer) && !empty($this->customer)) {
                                                            foreach ($this->customer as $customer) {
                                                              if(isset($this->customerid) && !empty($this->customerid)) {
                                                                if($this->customerid==$customer['id'])
                                                                  $customerSelect = 'selected';
                                                                else
                                                                  $customerSelect = '';
                                                            }
                                                    ?>
                                                        <option value="<?php echo $customer['id']; ?>" <?php echo $customerSelect; ?>><?php echo $customer['customer_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                    
                                              </select> 
                                                 <?php 
                                                      if($logSession->type!= 5) {
                                                 ?>
                                              <a href="<?php echo $this->sitePath."business/customer/add"; ?>" title="Click to add new customer" data-title="Click to add new customer" target="_blank"><i class="icon-plus-circle-2"></i> Add New Customer</a>
                                                 <?php 
                                                      }
                                                 ?>
                                            </div> 
                                            <div class="col-lg-2">
                                             <label>Payment / Accruals Account <span class="mandatory">*</span></label>
                                                <select class="form-control" name="payment_account" id="payment_account" onchange="triggerPayment();">
                                                <option value="">Select</option>  
                                                     <?php
                                                     $paySelect = '';
                                                        if(isset($this->payAccount) && !empty($this->payAccount)) {
                                                            foreach ($this->payAccount as $pay) {
                                                              if(isset($this->payid) && !empty($this->payid)) {
                                                                if($this->payid==$pay['id'])
                                                                 $paySelect = 'selected';
                                                                else
                                                                  $paySelect = '';
                                                              }
                                                    ?>
                                                        <option value="<?php echo $pay['id']."_".$pay['account_id']."_".$pay['account_type']; ?>" <?php echo $paySelect; ?>><?php echo $pay['account_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                       
                                                </select>
                                            </div>  
                                            <div class="col-lg-2">
                                             <label>Credit Term <span class="mandatory">*</span></label>
                                                <select class="form-control" name="credit_term" id="credit_term" onchange="triggerPayment();">
                                                      <?php
                                                        $days = '';
                                                        $creditSelect = '';
                                                        if(isset($this->creditTerm) && !empty($this->creditTerm)) {
                                                            foreach ($this->creditTerm as $key => $credit) {
                                                                if($key!=1) {
                                                                    $credits = $credit." Days";
                                                                } else {
                                                                    $credits = $credit;
                                                                }
                                                                if(isset($this->credit_term) && !empty($this->credit_term)) {
                                                                  if($this->credit_term==$key) {
                                                                    if($key!=1) {
                                                                        $days = $credit;
                                                                    } 
                                                                    $creditSelect = 'selected';
                                                                  }
                                                                  else {
                                                                    $creditSelect = '';
                                                                  }
                                                                } else if($this->creditSet==$key) {
                                                                    if($key!=1) {
                                                                        $days = $credit;
                                                                    } 
                                                                    $creditSelect = 'selected';
                                                                }
                                                                else {
                                                                    $creditSelect = '';
                                                                }
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $creditSelect; ?>><?php echo $credits; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 
                                        </div>

                                        <div class="form-group">

                                             <div class="col-lg-2">
                                             <label>Currency <span class="mandatory">*</span></label>
                                                <select class="select2" name="currency">
                                                <option value="">Select</option>  
                                                     <?php
                                                     $currencySelect = '';
                                                        if(isset($this->currencies) && !empty($this->currencies)) {
                                                            foreach ($this->currencies as $key => $currency) {
                                                              if(isset($this->currencyid) && !empty($this->currencyid)) {
                                                                if($this->currencyid==$key)
                                                                 $currencySelect = 'selected';
                                                                else
                                                                  $currencySelect = '';
                                                              } else {
                                                                if($key=='SGD') 
                                                                    $currencySelect = "selected";
                                                                else
                                                                    $currencySelect = "";
                                                              }
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $currencySelect; ?>><?php echo $currency; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 

                                            <div class="col-lg-2">
                                             <label>Type of Income <span class="mandatory">*</span></label>
                                                <select class="form-control" name="income_type">
                                                    <?php
                                                       $incomeSelect = '';
                                                        if(isset($this->incomeAccount) && !empty($this->incomeAccount)) {
                                                            foreach ($this->incomeAccount as $income) {
                                                              if(isset($this->income_type) && !empty($this->income_type)) {
                                                                if($this->income_type==$income['id'])
                                                                 $incomeSelect = 'selected';
                                                                else
                                                                  $incomeSelect = '';
                                                              }
                                                    ?>
                                                        <option value="<?php echo $income['id']; ?>" <?php echo $incomeSelect; ?>><?php echo $income['account_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                                <?php 
                                                      if($logSession->type!= 3 && $logSession->type!= 4 && $logSession->type!= 5) {
                                                 ?>
                                                <a href="<?php echo $this->sitePath."settings/account"; ?>" title="Click to add new income" data-title="Click to add new income" target="_blank"><i class="icon-plus-circle-2"></i> Add New Income</a>
                                                <?php
                                                      }
                                                ?>
                                            </div> 

                                            <div class="col-lg-4">
                                            <label>Description <span class="mandatory">*</span></label>
                                                <input type="text" name="description" id="description" class="form-control" placeholder="Enter Description" autocomplete="off" value="<?php if(isset($this->description) && !empty($this->description)) { echo $this->description; } ?>">
                                            </div> 

                                            <div class="col-lg-2">
                                            <label>Amount <span class="mandatory">*</span></label>
                                                <input type="text" name="amount" id="amount" class="form-control amount-align" autocomplete="off"  value="<?php if(isset($this->amount) && !empty($this->amount)) { echo $this->amount; } ?>" onchange="return numberWithCommas(this.value,this.id);" />
                                            </div> 

                                          <div class="col-lg-2">
                                             <label>Tax Code </label>
                                                <select class="form-control" name="tax_code" id="tax_code" title="select">
                                                     <option value="0" title="Not Applicable" selected>NA</option>    
                                                    <?php
                                                     $taxSelect = '';
                                                        if(isset($this->taxCode) && !empty($this->taxCode)) {
                                                            foreach ($this->taxCode as $tax) {
                                                              if(isset($this->tax_code) && !empty($this->tax_code)) {
                                                                if($this->tax_code==$tax['id'])
                                                                 $taxSelect = 'selected';
                                                                else
                                                                  $taxSelect = '';
                                                              }
                                                    ?>
                                                        <option value="<?php echo $tax['id']."_".$tax['tax_percentage']; ?>"  title="<?php echo ucfirst($tax['description']); ?>" <?php echo $taxSelect; ?>><?php echo $tax['tax_code']." - ".$tax['tax_percentage']." %"; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                  
                                                </select>
                                            </div> 

                                        </div>

                            <br/>

                    <div class="form-group">
                     <div class="col-lg-3">
                     <label>Attach Invoice or Receipt </label><br/>
                        <input type="file" name="file" id="file" />
                     </div>
                    </div>

<div class="row" id="trigger_payment" style="display:none;">
 <h4>Add Payment</h4>
    <div class="form-group">
     
        <div class="col-lg-2">
         <label>Payment Date <span class="mandatory">*</span></label>
            <input type="text" name="addpay_date" required id="addpay_date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" value="<?php echo date('d-m-Y'); ?>" />
        </div>
      
        <div class="col-lg-3">
        <label>Payment / Accruals Account <span class="mandatory">*</span></label>
             <select class="form-control" name="addpay_pay_account" id="addpay_pay_account" required>
               <option value="">Select</option>  
                    <?php
                        if(isset($this->payAccount) && !empty($this->payAccount)) {
                            foreach ($this->payAccount as $payAccount) {
                    ?>
                        <option value="<?php echo $payAccount['id']; ?>"><?php echo $payAccount['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>     
                                                                     
              </select>
        </div>
     
        <div class="col-lg-2">
         <label>Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_pay_amount" id="addpay_pay_amount" class="form-control amount-align" required number="true" autocomplete="off"  onchange="return numberWithCommas(this.value,this.id);"  />
            <input type="hidden" name="addpay_pending_amount" id="addpay_pending_amount" class="form-control" autocomplete="off"   />
        </div>

      
        <div class="col-lg-2">
        <label>Payment Method <span class="mandatory">*</span></label>
          <select name="addpay_pay_method" id="addpay_pay_method" class="form-control" required>
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>

        <div class="col-lg-2">
         <label>Bank Cheque / Draft No </label>
            <input type="text" name="addpay_cheque_draft_no" id="addpay_cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
    <div class="form-group">
     
        <div class="col-lg-2">
        <label>Prompt Payment Discount <span class="mandatory">*</span></label>
            <select class="form-control" name="addpay_payment_discount" id="addpay_payment_discount" onchange="discountTriggerPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>

      
        <div class="col-lg-2">
        <label>Discount Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_discount_payment_amount" id="addpay_discount_payment_amount" class="form-control amount-align" value="0" disabled  autocomplete="off"  onchange="return numberWithCommas(this.value,this.id);" />
        </div>

      
        <div class="col-lg-6">
        <label>Additional Description / Notes </label>
        <textarea name="addpay_description" id="addpay_description" class="form-control"></textarea>
        <input type="hidden" name="payment_trigger" id="payment_trigger" value="0" />
        </div>
    </div>


</div>

                                <div class="form-group">
                                    <div class="col-lg-1">
                                         <div class="form-actions">
                                            <input type="hidden" name="action" id="action" value="save_draft_income" />
                                            <input type="button" name="save_draft_income" class="btn btn-primary" id="save_draft_income" value="Save as Draft" onclick="return saveDraft();" /><br/>
                                            <i>Save Draft Income</i>
                                          </div>
                                      </div>
                                       <div class="col-lg-3" style="margin-left:10px;">
                                        <div class="form-actions">
                                            <select class="form-control" name="approval_for" id="approval_for">
                                            <option value="">For Approval</option>
                                                        <?php
                                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                                foreach ($this->approveUser as $approve) {
                                                                  if($approve['account_type']==2) {
                                                                     $account_type = "Super User";
                                                                  } else if($approve['account_type']==3) {
                                                                     $account_type = "Manager";
                                                                  }
                                                        ?>
                                                            <option value="<?php echo $approve['id']; ?>" ><?php echo $approve['username']." - ".$account_type; ?></option>
                                                        <?php
                                                                }
                                                            }
                                                        ?>                                                      
                                                    </select>
                                          </div>
                                          
                                      </div>
                                      <div class="col-lg-1">
                                          <div class="form-actions">
                                            <input type="submit" name="unapprove_save" class="btn btn-primary add_approve_income_transaction" id="unapprove_save" value="For Approval" /><br/>
                                            <i>Save Income for approval</i>
                                          </div>
                                      </div>
                                         <?php 
                                              if($logSession->type!=4) {
                                         ?>
                                       <div class="col-lg-1" style="margin-left:10px;">
                                         <div class="form-actions">
                                            <input type="submit" name="approve_income" class="btn btn-primary add_income_transaction" id="approve_income" value="Approve" /><br/>
                                            <i>Approve Income for account posting</i>
                                            </div>
                                         </div>
                                      <?php
                                            }
                                      ?>

                                         <div class="col-lg-1" style="margin-left:0px;">
                                         <div class="form-actions">
                                            <button type="reset" class="btn" onclick="return hideIncome();">Cancel</button>
                                            </div>
                                         </div>
                                    </div>
                                 


                                </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
      
   <?php 
        }
    ?>
 <div class="row">
                        <div class="col-md-12">
                            <div class="box-widget">
                                <table class="table data-tbl-boxy responsive">
                                    <thead>
                                        <tr>
                                            <th>
                                                Date
                                            </th>
                                            <th>
                                                Receipt No
                                            </th>
                                            <th>
                                                Type of Income
                                            </th>
                                            <th>
                                                Description
                                            </th>
                                            <th>
                                                Payment Account
                                            </th>
                                            <th>
                                                Customer / Payee
                                            </th>
                                            <th>
                                                Amount Due
                                            </th>
                                            <th>
                                                Total Amount
                                            </th>
                                            <th>
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php 
                                        $i=1;
                                        foreach($this->result as $results) {
                                            $pay_amount = 0.00;
                                            $total_amount = 0.00;
                                            $tax_amount = 0.00;
                                            $income_type = '';
                                            if(isset($this->incomeAccount) && !empty($this->incomeAccount)) {
                                                foreach ($this->incomeAccount as $income) {
                                                    if($income['id']==$results['fkincome_type']) {
                                                        $income_type = ucfirst($income['account_name']);
                                                    }
                                                }
                                            }
                                            foreach ($this->payments as $pay) {
                                              if($pay['fkiei_id']==$results['id']) {
                                                  $pay_amount += $pay['payment_amount'];
                                              }
                                            }
                                            $tax_amount     = ($results['amount'] * $results['tax_value'] / 100);
                                            $total_amount   = $results['amount'] + $tax_amount;
                                            $pending_amount =  $total_amount - $pay_amount;
                                    ?>
                                        <tr>
                                       
                                            <td style="width:7%;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo date("d-m-Y",strtotime($results['date'])); ?></a></td>
                                            <td style="width:10%;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo $results['receipt_no']; ?></a></td>
                                            <td style="width:15%;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo $income_type; ?></a></td>
                                            <td style="width:15%;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo $results['transaction_description']; ?></a></td>
                                            <td style="width:12%;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo ucfirst($results['account_name']); ?></a></td>
                                             <td style="width:12%;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo ucfirst($results['customer_name']); ?></a></td>
                                             <td style="width:10%; text-align:right;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo number_format($pending_amount,2,'.',','); ?></a></td>
                                             <td style="width:10%; text-align:right;"><a class="setView <?php if($logSession->type==5) { echo "disabled"; } ?>" href="javascript:void(0)"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')"><?php echo number_format($total_amount,2,'.',','); ?></a></td>
                                        <td class="action-bar" style="width:10%;">

                                    <div class="btn-group col-md-1">
                                    <button data-toggle="dropdown" class="btn btn-small dropdown-toggle"> <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->sitePath."transaction/income/view/id/".base64_encode($results['id']); ?>">View</a></li>
                                         <?php 
                                            if($logSession->type!=5) {
                                         ?>
                                          <?php 
                                            if($results['transaction_status']!=3) {
                                          ?>
                                        <li><a href="javascript:void(0)" onclick="return addPayment('<?php echo $pending_amount; ?>','<?php echo $results['aid']; ?>','<?php echo $results['id']; ?>')">Add Payment</a></li>
                                        <?php 
                                            }
                                        ?>
                                        <li><a href="javascript:void(0)" class="<?php if($results['transaction_status']==1) { echo "disable-indication"; } ?>"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')">Edit</a></li>
                                        <?php 
                                            if($results['transaction_status']!=3) {
                                         ?>
                                        <li><a href="javascript:void(0)" class="widget-remove" onclick="return copyTransaction('<?php echo base64_encode($results['id']); ?>')">Copy</a></li>
                                        <?php 
                                            }
                                        ?>
                                        <?php
                                            }
                                        ?>
                                        <?php 
                                            if($logSession->type!=5) {
                                         ?>
                                        <li><a href="javascript:void(0)" class="widget-remove" onclick="return deleteIncome('<?php echo base64_encode($results['id']); ?>')">Delete</a></li>
                                        <?php
                                            }
                                        ?>
                                    </ul>
                                    </div>

                                        <div class="col-md-3" style="margin-left:20px;">
                                        <?php 
                                          if($results['transaction_status']==1) {
                                        ?>
                                          <a class="btn btn-mini btn-success" href="javascript:void(0)" data-original-title="Unverify"  onclick="<?php if($logSession->id==$results['approval_for']) { ?>changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',2) <?php } ?>"><i class="icon-ok"></i></a>
                                        <?php 
                                          } else if($results['transaction_status']==2) {
                                        ?>
                                          <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Verify"  onclick="<?php if($logSession->id==$results['approval_for']) { ?>changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',1) <?php } ?>"><i class="icon-ok"></i></a>
                                        <?php 
                                          } else if($results['transaction_status']==3) {
                                        ?>
                                         <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Draft"><i class="icon-envelope"></i></a>
                                        <?php 
                                          }
                                        ?>
                                        </div>

                                        </td>
                                        </tr>
                                    <?php 
                                        }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
<script type="text/javascript">
$(document).ready(function(){
  $('#amount').tooltip({'trigger':'hover', 'placement':'right'});
   $("#tax_code").on('mouseover', function(e) {
    console.log("over");
    var $e = $(e.target); 
    console.log($e);
    if ($e.is('option')) {
      console.log("option");
        $('#tax_code').tooltip({'trigger':'hover', 'placement':'right'});
    }
  }); //mouseover
});
function discountPayment(value) {
    if(value==1) {
        $("#discount_payment_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#discount_payment_amount").val("0");
        $("#discount_payment_amount").attr("disabled","true");
    }
}
function discountTriggerPayment(value) {
    if(value==1) {
        $("#addpay_discount_payment_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#addpay_discount_payment_amount").val("0");
        $("#addpay_discount_payment_amount").attr("disabled","true");
    }
}
function changeTransactionStatus(Idvalue,status) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/income/index/verifyid/'+Idvalue+'/status/'+status;
}
function showIncome() {
    $('form').each(function(){
        this.reset();
    });
    $('#add_income').slideToggle(1000);
} 
function hideIncome() {
    $('form').each(function(){
        this.reset();
    });
    $('#add_income').slideToggle(1000);
} 
function deleteIncome(Idvalue) {
  var confirmMsg = confirm("Are you sure want to delete this income transaction? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/income/index/delid/'+Idvalue;
    }
}
function copyTransaction(Idvalue) {
  var confirmMsg = confirm("Are you sure want to copy this income transaction?");
    if(confirmMsg) {
        window.location.href='<?php echo $this->sitePath; ?>transaction/income/copy/id/'+Idvalue;
    }
}

function editTransaction(Idvalue,status) {
  if(status==1) {
    alert("Cannot edit this income because transaction is verified");
  } else {
        window.location.href='<?php echo $this->sitePath; ?>transaction/income/edit/id/'+Idvalue;
    }
}

function addPayment(pendingAmount,accountId,Idvalue) {
  if(pendingAmount==0) {
      alert("Full payment has been received for this income");
      return false;
  } else {
    /*$('form').each(function(){
        this.reset();
    });*/
    $("#income_id").val(Idvalue);
    $("#pending_amount").val(pendingAmount);
    $("#pay_amount").val(numberWithCommasInput(pendingAmount));
    $("#pay_account").find('option').removeAttr("selected");
   // $("#pay_account").val(accountId);
    $("#pay_account option[value='"+accountId+"']").attr("selected", "selected");
    $("#add_receipt").hide();
    $("#add_payment").show();
    $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', 
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], 
    });
  }
}

 function saveDraft() {
  $(".btn").attr("disabled",true);
    $.ajax({
      type: "POST",
      url: "<?php echo $this->sitePath.'transaction/income/ajax-call'; ?>",
      data: $('#add-income').serialize(),
      success: function (html) {
          if(html=='success') {
             $('#add_income').slideToggle(1000);
             $(".btn").attr("disabled",false);
              window.location.href='<?php echo $this->sitePath; ?>transaction/income';
          } else {
             $('#failure').html('<strong>Income cannot be saved as draft</strong>');
             $('#failure').fadeIn(1000);
             $('#failure').fadeOut(9000);
             $(".btn").attr("disabled",false);
          }
      }
    }); 
 }

function getReceipt(value) {
  if(value!='') {
      var i=0;
      var customer_receipt = '<select name="receipts" id="receipts"  class="form-control" required><option value="">Select</option>';

         <?php
            foreach ($this->receipts as $receipt) {
        ?>
          if(value==<?php echo $receipt['fkbusiness_id'] ?>) {
        <?php
                $id   = $receipt['id']."-".$receipt['name']."-".$receipt['receipt'];
                $name = $receipt['name'];
         ?>
           customer_receipt += '<option value="<?php echo $id; ?>"><?php echo $name; ?></option>';
           i++;
          }
         <?php
            }
         ?>
         customer_receipt += '</select>';
         if(i==0) {
           $("#receipt_add").html("<p>No Receipts Found</p>");
         } else {
           $("#receipt_add").html(customer_receipt);
         }
         $("#receipt_id").val("");
         $("#customer_receipts").html("");
         $("#customer_receipts").hide();
         $("#attach").show();

  }
}

 function attachReceipt() {
    var customer = $("#customer").val();
    if(customer=='') {
        alert('Select any customer to attach receipt');
    } else {
        $("#add_payment").hide();
        $("#add_receipt").show();
        $('#popup').bPopup({
                modalClose: false,
                easing: 'easeOutBack', 
                speed: 1000,
                transition: 'slideDown',
                follow: [false, false], 
        });
    }
 }

 function addReceipt() {
    var receipts      = $("#receipts").val();
    var receiptSplit  = receipts.split('-');
    var receiptId     = receiptSplit[0];
    var receiptName   = receiptSplit[1];
    var receiptFile   = receiptSplit[2];
    if(receiptId!='' && receiptName!='' && receiptFile!='') {
      var receipturl = '<a href="<?php echo $this->filepath; ?>'+receiptFile+'" target="_blank"> '+receiptName+' </a>';
      $("#receipt_id").val(receiptId);
      $("#attach").hide();
      $("#customer_receipts").html("Receipt "+ receipturl +" have been attached");
      $("#customer_receipts").show();
    }
    $("#popup").bPopup().close();
 }

 function bPopup_close() {
    $("#popup").bPopup().close();
 }

function numberWithCommas(x,id) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  $("#"+id).val(value);
}

function numberWithCommasInput(x) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  return value;
}

function triggerPayment() {
    var pay_account      = $("#payment_account").val();
    var credits          = $("#credit_term").val();
    var amount           = $("#amount").val();
    var payment_account  = pay_account.split('_');
    $("#addpay_pay_account").find('option').removeAttr("selected");
    $("#addpay_pay_account option[value='"+payment_account[0]+"']").attr("selected", "selected");
    $("#addpay_pay_amount").val(amount);
    if((Number(payment_account[1])<=6 && Number(payment_account[2]==1)) && credits==1) {
      $("#payment_trigger").val("1");
      $("#trigger_payment").show();
    } else {
      $("#trigger_payment").hide();
      $("#payment_trigger").val("0");
    } 
}

</script>