<?php
$logSession = new Zend_Session_Namespace('sess_login');
?>
<div class="main-container">
<div class="container">
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/developer/"; ?>">Developer</a></li>
   <li class="active">Announcements</li>
</ul>
 <div class="row">
     <div class="col-md-6 col-md-offset-3">
        <?php 
            if(isset($this->success) && !empty($this->success)) {
        ?>
        <div class="alert alert-success">
            <strong><?php echo $this->success; ?></strong>
        </div>
            <?php
             } else if(isset($this->error) && !empty($this->error)) {
            ?>
        <div class="alert alert-danger">
                <strong><?php echo $this->error; ?></strong>
        </div>
        <?php 
           }
        ?>
       </div>
     </div>
      <div class="row">
	   <div class="col-md-12 grid-spacing">
	   <a href="<?php echo $this->sitePath."developer/send-announcement"; ?>" class="btn btn-primary">Send Announcement</a>
	   </div>
   </div>
 <div class="row">
                        <div class="col-md-12">
                            <div class="box-widget">
                            
                                <table class="table data-tbl-boxy responsive">
                                    <thead>
                                        <tr>
                                        	<th>
                                              S.No.
                                            </th>
                                            <th>
                                               Company
                                            </th>
                                            <th>
                                               Subject
                                            </th>
                                            <th>
                                                Message
                                            </th>
                                            <th>
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    	$i = 1;
                                        if($logSession->type==0) {
                                    	foreach ($this->announcements as $announce) {
                                    		$aid = base64_encode($announce['id']);
                                    ?>
                                    	<tr>
                                    	<td><?php echo $i++; ?></td>
                                        <td><?php if($announce['company_name']!='') { echo $announce['company_name']; } else { echo "All"; } ?></td>
                                    	<td><?php echo $announce['subject']; ?></td>
                                    	<td><?php echo substr($announce['message'], 0,30)."..."; ?></td>
                                    	<td>
                                          <a href="<?php echo $this->sitePath."developer/view-announcement/aid/".$aid; ?>" data-original-title="View Announcement" title="View Announcement"><i class="icon-file-8"></i></a>
                                            <a href="javascript:void(0)" onclick="getConfirm('<?php echo $aid; ?>')" data-original-title="Delete Announcement" title="Delete Announcement"><i class="icon-remove-2"></i></a>
                                    	</td>
                                    	</tr>

                                    <?php
                                            }
                                    	} else if($logSession->type==1) {
                                        foreach ($this->announcements as $announce) {
                                           if($announce['fkcompany_id']==$logSession->cid) { 
                                           $aid = base64_encode($announce['id']); 
                                    ?>
                                        <tr>
                                        <td><?php echo $i++; ?></td>
                                         <td><?php echo $announce['company_name']; ?></td>
                                        <td><?php echo $announce['subject']; ?></td>
                                        <td><?php echo substr($announce['message'], 0,30)."..."; ?></td>
                                        <td>
                                          <a href="<?php echo $this->sitePath."developer/view-announcement/aid/".$aid; ?>" data-original-title="View Announcement" title="View Announcement"><i class="icon-file-8"></i></a>
                                            <a href="javascript:void(0)" onclick="getConfirm('<?php echo $aid; ?>')" data-original-title="Delete Announcement" title="Delete Announcement"><i class="icon-remove-2"></i></a>
                                        </td>
                                        </tr>
                                    <?php
                                            } if($announce['fkcompany_id']==0) { 
                                                $aid = base64_encode($announce['id']);
                                    ?>
                                         <tr>
                                        <td><?php echo $i++; ?></td>
                                         <td><?php echo "All"; ?></td>
                                        <td><?php echo $announce['subject']; ?></td>
                                        <td><?php echo substr($announce['message'], 0,30)."..."; ?></td>
                                        <td>
                                          <a href="<?php echo $this->sitePath."developer/view-announcement/aid/".$aid; ?>" data-original-title="View Announcement" title="View Announcement"><i class="icon-file-8"></i></a>
                                            <a href="javascript:void(0)" onclick="getConfirm('<?php echo $aid; ?>')" data-original-title="Delete Announcement" title="Delete Announcement"><i class="icon-remove-2"></i></a>
                                        </td>
                                        </tr>
                                    <?php
                                            }
                                          }
                                        }
                                    ?>                                   
                                    </tbody>
                                </table>
                            </div>
                       </div>
    </div>
</div>
</div>
 <script type="text/javascript">
    function getConfirm(Idvalue) {
        var confirmMsg = confirm("Are you sure want to delete this announcement?");
        if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>developer/announcements/delid/'+Idvalue;
        }
    }
 </script>