<?php
$logSession = new Zend_Session_Namespace('sess_login');
?>
<div class="main-container">
<div class="container">
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/developer/"; ?>">Developer</a></li>
   <li class="active">Companies</li>
</ul>

  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>

 <div class="row">
                        <div class="col-md-12">
                            <div class="box-widget">
                            <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Company and Database Settings</h4>
                                    
                                </div>
                                <table class="table responsive">
                                    <thead>
                                        <tr>
                                        	<th>
                                              S.No.
                                            </th>
                                            <th>
                                               Company Name
                                            </th>
                                            <th>
                                                Username
                                            </th>
                                            <th>
                                                Account Type
                                            </th>
                                            <th>
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    	$i = 1;
                                       if($logSession->type==0) {
                                    	foreach ($this->companies as $company) {
                                    		$cid = base64_encode($company['cid']);
                                    ?>
                                    	<tr>
                                    	<td><?php echo $i++; ?></td>
                                    	<td><strong><?php echo $company['company_name']; ?></strong></td>
                                    	<td></td>
                                    	<td></td>
                                    	<td>
                                    		<a href="<?php echo $this->sitePath."developer/configure-database/company/".$cid; ?>" data-original-title="Configure Database" title="Configure Database"><i class="icon-storage"></i></a>
                                    		<a href="<?php echo $this->sitePath."developer/edit/company/".$cid; ?>" data-original-title="Edit Company" title="Edit Company"><i class="icon-pencil-3"></i></a>
                                    		<a href="javascript:void(0)" data-original-title="Delete Company" title="Delete Company" onclick="deleteDatabase('<?php echo $cid ?>');"><i class="icon-remove-2"></i></a>
                                    	</td>
                                    	</tr>
                                    <?php
                                    	  foreach ($this->logins as $login) {
                                    		if($company['cid']==$login['fkcompany_id']) {
                                    ?>
                                    	  <tr>
                                    	  <td></td>
                                    	  <td></td>
                                    	  <td><?php echo $login['username']; ?></td>
                                    	  <td>
                                    	  	<?php
                                    	  		foreach ($this->accTypes as $key => $account) {
                                    	  			if($key == $login['account_type']) {
                                    	  				echo $account;
                                    	  			}
                                    	  		}
                                    	  	?>
                                    	  </td>
                                    	  <td>

                                    	  </td>
                                    	  </tr>
                                    <?php
                                    		}
                                		   }
                                         } 
                                     } else if($logSession->type==1) {
                                        foreach ($this->companies as $company) {
                                           if($company['cid']==$logSession->cid) {  
                                            $cid = base64_encode($company['cid']);

                                    ?>
                                      <tr>
                                        <td><?php echo $i++; ?></td>
                                        <td><strong><?php echo $company['company_name']; ?></strong></td>
                                        <td></td>
                                        <td></td>
                                        <td>
                                            <!-- <a href="<?php echo $this->sitePath."developer/configure-database/company/".$cid; ?>" data-original-title="Configure Database" title="Configure Database"><i class="icon-storage"></i></a> -->
                                            <a href="<?php echo $this->sitePath."developer/edit/company/".$cid; ?>" data-original-title="Edit Company" title="Edit Company"><i class="icon-pencil-3"></i></a>
                                            <a href="javascript:void(0)" data-original-title="Delete Company" title="Delete Company" onclick="deleteDatabase('<?php echo $cid ?>');"><i class="icon-remove-2"></i></a>
                                        </td>
                                        </tr>
                                    <?php
                                          foreach ($this->logins as $login) {
                                            if($company['cid']==$login['fkcompany_id']) {
                                    ?>
                                          <tr>
                                          <td></td>
                                          <td></td>
                                          <td><?php echo $login['username']; ?></td>
                                          <td>
                                            <?php
                                                foreach ($this->accTypes as $key => $account) {
                                                    if($key == $login['account_type']) {
                                                        echo $account;
                                                    }
                                                }
                                            ?>
                                          </td>
                                          <td>

                                          </td>
                                          </tr>

                                    <?php
                                                }
                                               }
                                            }
                                    	}
                                    }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                       </div>
    </div>
</div>
</div>
<script type="text/javascript">
function deleteDatabase(cid) {
  var confirmMsg = confirm('Are you sure want to delete the complete database of this company then you cannot able to access details again?') 
  if(confirmMsg) {
    window.location = '<?php echo $this->sitePath."developer/companies/deleteDb/"; ?>'+cid;
  }
}
</script>