<div class="main-container">
<div class="container">
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li class="active">Update Profile</li>
</ul>

                                <div class="row">
                                       <div class="col-md-6 col-md-offset-3">
                                       <?php 
                                            if(isset($this->success) && !empty($this->success)) {
                                       ?>
                                            <div class="alert alert-success">
                                               <strong><?php echo $this->success; ?></strong>
                                            </div>
                                        <?php
                                            } else if(isset($this->error) && !empty($this->error)) {
                                        ?>
                                            <div class="alert alert-danger">
                                               <strong><?php echo $this->error; ?></strong>
                                            </div>
                                        <?php 
                                            }
                                        ?>
                                        </div>
                                 </div>

<div class="row">
                        <div class="col-md-12 widget-module">
                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Update Profile</h4>
                                    
                                </div>

                                <div class="widget-container col-md-12 col-md-offset-3">
                                    <form class="form-horizontal" id="update-profile" method="post">
                                   

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">Username <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                            <?php
                                                if($this->result[0]['account_type']==0) {
                                                    $readonly = 'readonly'; 
                                                } else {
                                                    $readonly = '';
                                                }
                                            ?>
                                                <input type="email" name="username" id="username" class="form-control" value="<?php echo $this->result[0]['username']; ?>" <?php echo $readonly;  ?>>
                                            </div>
                                        </div>
                                         <div class="form-group">
                                            <label class="col-lg-2 control-label">Account Role <span class="mandatory">*</span></label>
                                            <div class="col-lg-4">
                                                <?php 

                                                    if($this->result[0]['account_type']==0) {
                                                        echo "Developer";
                                                    } else {

                                                        if(isset($this->account_types) && !empty($this->account_types)) {
                                                            foreach($this->account_types as $key => $account) {
                                                                if($this->result[0]['account_type']==$key) {
                                                                    echo $account;
                                                                }
                                                            }
                                                        }
                                                    }
                                                ?>
                                                <input type="hidden" name="account_type" id="account_type" value="<?php echo $this->result[0]['account_type']; ?>" />
                                                <label for="account_type" generated="true" class="error"></label>
                                            </div>
                                        </div>
                                         <div class="form-group">
                                            <label class="col-lg-2 control-label">Change Password <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <input type="checkbox" name="change_password" id="change_password" class="" value="1" onchange="return passwordCheck();" / > &nbsp; Check this to update password
                                            </div>
                                        </div>
                                        <div class="form-group password-display" style="display:none;">
                                            <label class="col-lg-2 control-label">Password <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <input type="password" name="password" id="password" class="form-control" placeholder="Enter password" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" title="Password must contain one uppercase, lowercase, number/special chars and minimum of 8 chars">
                                            </div>
                                        </div>
                                        <div class="form-group password-display" style="display:none;">
                                            <label class="col-lg-2 control-label">Confirm Password <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <input type="password" name="cpassword" id="cpassword" class="form-control" placeholder="Enter confirm password">
                                            </div>
                                        </div>

                                       
                                       
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">&nbsp;</label>
                                            <div class="col-lg-3">
                                                <div class="form-actions">
                                                    <button type="submit" id="create" class="btn btn-primary">Submit</button>
                                                    <button type="reset" class="btn">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
    </div>
</div>
<script type="text/javascript">
function passwordCheck() {
    if($('#change_password').is(':checked')) {
        $('.password-display').fadeIn(500);
    } else {
        $('.password-display').fadeOut(500);
    }
}
</script>