<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="account_add">
 <div class="col-md-12 widget-module">
      <div class="box-widget">
          <div class="widget-head clearfix">
             <span class="h-icon"><i class="icon-menu"></i></span>
              <h4 class="pull-left">Add New Sub-Account</h4>
                                    
           </div>
     <div class="widget-container">
          <div class="widget-block">
             <div class="widget-content box-padding">
                <form class="form-horizontal" id="add-accounts" method="post">
                                                
                     <div class="form-group">
                         <label class="col-lg-3 control-label">Account Type</label>
                              <div class="col-lg-7">
                                  <select class="select2" name="accountType" onclick="return pay_accounts(this.value);">
                                  <option value="">Select</option>
                                  <?php
                                     foreach ($this->systemAccount as  $system) {
                                   ?>
                                        <option value="<?php echo $system['id']; ?>"><?php echo ucfirst($system['account']); ?></option>
                                   <?php 
                                     }
                                   ?>
                                                           
                                  </select>
                               </div>
                      </div>

                      <div class="form-group">
                           <label class="col-lg-3 control-label">Account Name</label>
                             <div class="col-lg-5">
                                 <input type="hidden" name="action" value="add">
                                 <input type="text" name="name" id="name" class="form-control" placeholder="Enter account name">
                             </div>
                     </div>

                     <div class="form-group" id="pay_account" style="display:none;">
                          <label class="col-lg-3 control-label">Payment Account</label>
                             <div class="col-lg-7">
                                 <div class="styled-chekbox">
                                    <input type="checkbox" class="icheck-box" name="payment_account" value="1">
                                  </div>
                                <span class="checkbox-label">I use this account to deposit or spend money (e.g., bank account, credit card, line of credit)</span>
                               </div>
                      </div>

                     <div class="form-group">
                        <label class="col-lg-2 control-label">&nbsp;</label>
                             <div class="col-lg-10">
                                 <div class="form-actions">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                       <button type="reset" class="btn">Cancel</button>
                                  </div>
                            </div>
                      </div>
                 </form>
               </div>
          </div>
     </div>
                            </div>
                        </div>
</div>

<div class="row" id="account_edit">

<div class="col-md-12 widget-module">
      <div class="box-widget">
          <div class="widget-head clearfix">
             <span class="h-icon"><i class="icon-menu"></i></span>
              <h4 class="pull-left">Edit Sub-Account</h4>
                                    
           </div>
     <div class="widget-container">
          <div class="widget-block">
             <div class="widget-content box-padding">
                <form class="form-horizontal" id="edit-accounts" method="post">
                <div  id="account_details">                                
                <input type="hidden" name="action" value="edit">
                      
                </div>

                     <div class="form-group">
                        <label class="col-lg-2 control-label">&nbsp;</label>
                             <div class="col-lg-10">
                                 <div class="form-actions">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                       <button type="reset" class="btn">Cancel</button>
                                  </div>
                            </div>
                      </div>
                 </form>
               </div>
          </div>
     </div>
                            </div>
                        </div>

</div>




</div>
 <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
   <div class="row">
	   <div class="col-md-12 grid-spacing">
	   <button class="btn btn-primary" type="button" id="add-account">Add Account</button>
            <!-- Element to pop up -->    
	   </div>
   </div>
 <div class="row">


                        <div class="col-md-12">
                            
                            <div class="box-widget">
                                <div class="widget-head clearfix">
                                    <span class="h-icon"><i class="icon-power-cord"></i></span>
                                    <h4 class="pull-left">List of Accounts</h4>
                                </div>
                                <div class="widget-container">
                                    <div class="widget-block">
                                        <div class="widget-content">
                                            <table class="table responsive">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            Accounts
                                                        </th>
                                                        <th>
                                                            Actions
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
														foreach ($this->systemAccount as  $system) {
													?>
													<tr>
														<td colspan="2"><strong><?php echo ucfirst($system['account']); ?></strong></td>
													</tr>
                          <?php 
                            if($system['id']==1) {
                          ?>
                            <tr>
                            <td>Account Receivable</td>
                            <td><i>System Account</i></td>
                            </tr>
                          <?php 
                            } else if($system['id']==2) {
                          ?>
                            <tr>
                            <td>Account Payable</td>
                            <td><i>System Account</i></td>
                            </tr>
                          <?php
                            }
                          ?>
													<?php 
														$i=1;
														foreach ($this->subAccount as $sub) {
															if($system['id'] == $sub['fksys_id']) {
																if($i%2==0) {
																	$rowStyle = "odd gradeA";
																} else {
																	$rowStyle = "even gradeA";
																}

													?>
													<tr>
															<td><p><?php echo ucfirst($sub['name']); ?></p></td>
															<td class="action-bar">

															<a  class="edit-account" href="javascript:void(0)" data-index="<?php echo base64_encode($sub['id']);   ?>" data-name="<?php echo base64_encode($sub['name']); ?>" data-check="<?php echo $sub['payment_status']; ?>" data-systype="<?php echo $system['id']; ?>" data-original-title="Edit"><i class="icon-pencil-2"></i></a>

                              <?php 
                                if($sub['delete_status']==1) {
                              ?>
                                <a class="btn btn-mini btn-success" href="javascript:void(0)" data-original-title="Enabled"  onclick="disable('<?php echo base64_encode($sub['id']); ?>')"><i class="icon-ok"></i></a>
                              <?php 
                                } else if($sub['delete_status']==2) {
                              ?>
                                <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Disabled"  onclick="enable('<?php echo base64_encode($sub['id']); ?>')"><i class="icon-ok"></i></a>
                              <?php 
                                }
                              ?>
				                                             
				                        </td>
													</tr>
													<?php
															} 
														}
														}
													?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>



</div>
</div>
 <script type="text/javascript">

 $(function() {

            // Binding a click event
            // From jQuery v.1.7.0 use .on() instead of .bind()
            $('#add-account').bind('click', function(e) {

                // Prevents the default action to be triggered. 
                e.preventDefault();
                $("#account_add").show();
                $("#account_edit").hide();
                // Triggering bPopup when click event is fired
                $('#popup').bPopup({
                    easing: 'easeOutBack', //uses jQuery easing plugin
                    speed: 1500,
                    transition: 'slideDown'
                });

            });

              $('.edit-account').bind('click', function(e) {
                e.preventDefault();
                $("#account_add").hide();
                $("#account_edit").show();
                var index   = $(this).attr('data-index');
                var subname = $(this).attr('data-name');
                var status  = $(this).attr('data-check');
                var type    = $(this).attr('data-systype');
                    $('#popup').bPopup({
                        contentContainer:'#account_details',
                        loadUrl: '<?php echo $this->sitePath; ?>default/accounts/ajax-call/ajaxAction/subAccount/id/'+index+'/name/'+subname+'/status/'+status+'/type/'+type 
                     });
             });

  });


    function enable(Idvalue) {
       var confirmMsg = confirm("Are you sure want to enable this account?");
        if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>default/accounts/index/actid/'+Idvalue;
        }
    }
    function disable(Idvalue) {
       var confirmMsg = confirm("Are you sure want to disable this account?");
        if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>default/accounts/index/delid/'+Idvalue;
        }
    }
    function redirect() {
        window.location.href='<?php echo $this->sitePath."default/accounts/add"; ?>';
    }

    function pay_accounts(value) {
      if(value==4 || value==5 ) {
        $("#pay_account").fadeOut(1000);
      } else {
        $("#pay_account").fadeIn(1000);
      }
    }

  </script>