<?php
$logSession = new Zend_Session_Namespace('sess_login');
if(isset($logSession->proxy_name) && !empty($logSession->proxy_name)) {
  $company_name = ucfirst($logSession->proxy_name);
} else {
  $company_name = ucfirst($logSession->name);
}
?>
<div class="main-container">
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <form class="form-horizontal" id="report-period" method="post">

         <div class="form-group">

          <label class="col-lg-5 control-label">Account <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <select name="account" id="account" class="form-control">
                   <option value="">Select Account</option>
                       <?php 
                          $accountSelect = '';
                          $accountName = '';
                          $accountType = array();
                          if(isset($this->getAccount) && !empty($this->getAccount)) {
                              foreach ($this->getAccount as $account) {

                       ?>

                       <?php 
                          if(!in_array($account['account_type'], $accountType)) {
                            if($account['account_type']==1) {
                              echo '<optgroup label="Assets">';
                              if($this->generalAccount=='accountReceivables') {
                                    $accountSelect = 'selected';
                                    $accountId = 1;
                                    $accountName = 'Account Receivables';
                                } else { 
                                    $accountSelect = '';
                                }
                              echo '<option value="accountReceivables" '.$accountSelect.'>Account Receivables</option>';
                            } else if($account['account_type']==2) {
                             echo '<optgroup label="Liability / Credit Card">';
                             if($this->generalAccount=='accountPayables') {
                                    $accountSelect = 'selected';
                                    $accountName = 'Account Payables';
                                    $accountId = 2;
                                } else { 
                                    $accountSelect = '';
                                }
                             echo '<option value="accountPayables" '.$accountSelect.'>Account Payables</option>';
                             if($this->generalAccount=='gstPayables') {
                                    $accountSelect = 'selected';
                                    $accountName = 'GST Payables';
                                    $accountId = 2;
                                } else { 
                                    $accountSelect = '';
                                }
                             echo '<option value="gstPayables" '.$accountSelect.'>GST Payables</option>';
                            } else if($account['account_type']==3) {
                             echo '<optgroup label="Income">';
                            } else if($account['account_type']==4) {
                             echo '<optgroup label="Expense">';
                            } else if($account['account_type']==5) {
                             echo '<optgroup label="Equity">';
                            }
                            $accountType[] = $account['account_type'];
                          }
                                if(isset($this->generalAccount) && !empty($this->generalAccount)  && $account['id']==$this->generalAccount ) {
                                    $accountSelect = 'selected';
                                    $accountName = $account['account_name'];
                                    $accountId = $account['account_type'];
                                } else { 
                                    $accountSelect = '';
                                }
                       ?>
                    <option value="<?php echo $account['id']; ?>" <?php echo $accountSelect; ?>><?php echo ucfirst($account['account_name']); ?></option>
                      <?php
                                 }
                           } 
                        ?>
                </select> 
          </div>

        </div>

        <div class="form-group">

          <label class="col-lg-5 control-label">From Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="from_date" id="from_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->from) && !empty($this->from)) { echo $this->from; } else { echo date('01-01-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">

          <label class="col-lg-5 control-label">To Date <span class="mandatory">*</span></label>
          <div class="col-lg-2">
              <input type="text" name="to_date" id="to_date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->to) && !empty($this->to)) { echo $this->to; } else { echo date('d-m-Y'); } ?>" autocomplete="off"/>
          </div>

        </div>

        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Update</button>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>

<?php 
  if(isset($this->generalAccount) && !empty($this->generalAccount)) {
?>

    <div class="row">
      <div class="col-md-2 pull-right">
          <button class="print btn btn-inverse" type="button" rel="content"><i class="icon-print"></i> Print</button>
          <button class="btn btn-inverse" type="button"  onclick="tableToExcel('content', 'Account Transactions')"><i class="icon-file-excel"></i> Excel</button>
      </div>
    </div>

  <div class="row">
    <div class="col-md-12">

     <h4 align="center"><?php echo $company_name; ?> Company</h4> 
     <h4 align="center"><?php echo $accountName; ?> Transactions</h4> 
     <h4 align="center">Dated From <?php echo $this->from; ?> To <?php echo $this->to; ?></h4> 

     <div class="box-widget">
        <div class="widget-head clearfix">
            <span class="h-icon"><i class="icon-power-cord"></i></span>
            <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">Account Transactions</a></h4>
        </div>
        <div class="widget-container">
        <div class="widget-block">
        <div class="widget-content">
        <table class="table responsive">
            <thead>
              <tr>
                 <th>
                    Date
                 </th>
                 <th>
                    Transaction
                 </th>
                 <th>
                    Debit
                 </th>
                 <th>
                    Credit
                 </th>
                 <?php
                  if(isset($accountId) && !empty($accountId) && ($accountId==1 || $accountId==2 || $accountId==5)) {
                 ?>
                 <th>
                    Balance
                 </th>
                 <?php
                  }
                 ?>
              </tr>
            </thead>
            <tbody>
              <?php
                  $balance = 0.00;
                  $total_debit = 0.00;
                  $total_credit = 0.00;
                  if(isset($this->generalAccount) && !empty($this->generalAccount)) {
                    if(isset($this->generalTransaction) && !empty($this->generalTransaction)) {
                      foreach ($this->generalTransaction as $general) {
                        if($this->generalAccount==$general['account_type']) {
                          $total_debit += $general['debit_amount'];
                          $total_credit += $general['credit_amount'];
                          if($accountId==1) {
                            $balance += $general['debit_amount'] - $general['credit_amount'];
                          } else if ($accountId==2 || $accountId==5){
                            $balance += $general['credit_amount'] - $general['debit_amount'];
                          }
              ?>
                    <tr>
                      <td><?php echo $general['date']; ?></td>
                      <td><?php echo $general['transaction']; ?></td>
                       <td><?php echo number_format($general['debit_amount'],2,'.',','); ?></td>
                      <td><?php echo number_format($general['credit_amount'],2,'.',','); ?></td>
                      <?php 
                        if(($accountId==1 || $accountId==2 || $accountId==5)) {
                      ?>
                           <td>
                           <?php
                            if($balance<0) {
                                $negative_format = "(".number_format(abs($balance),2,'.',',').")";
                                echo $negative_format;
                             } else {
                                echo number_format($balance,2,'.',',');
                             }
                           ?></td>
                      <?php
                        }
                      ?>
                    </tr>

              <?php   
                        }
                      }
                    }
                  }
              ?>
              <tr>
                  <td><strong>Total</strong></td>
                  <td></td>
                  <td><strong><?php echo number_format($total_debit,2,'.',','); ?></strong></td>
                  <td><strong><?php echo number_format($total_credit,2,'.',','); ?></strong></td>
                   <?php 
                      if(isset($accountId) && !empty($accountId) && ($accountId==1 || $accountId==2 || $accountId==5)) {
                   ?>
                  <td></td>
                  <?php
                      }
                  ?>
              </tr>
            </tbody>
        </table>
        </div>
        </div>
        </div>
        </div>
    </div>

</div>
</div>

<div id="content" style="display:none;">
     <h4 align="center"><?php echo $company_name; ?> Company</h4> 
     <h4 align="center"><?php echo $accountName; ?> Transactions</h4> 
     <h4 align="center">Dated From <?php echo $this->from; ?> To <?php echo $this->to; ?></h4> 

      <table border="0" align="center" cellpadding="7" cellspacing="7">
            <thead>
              <tr>
                 <th>
                    Date
                 </th>
                 <th>
                    Transaction
                 </th>
                 <th>
                    Debit
                 </th>
                 <th>
                    Credit
                 </th>
                 <?php
                  if(isset($accountId) && !empty($accountId) && ($accountId==1 || $accountId==2 || $accountId==5)) {
                 ?>
                 <th>
                    Balance
                 </th>
                 <?php
                  }
                 ?>
              </tr>
            </thead>
            <tbody>
              <?php
                  $balance = 0.00;
                  $total_debit = 0.00;
                  $total_credit = 0.00;
                  if(isset($this->generalAccount) && !empty($this->generalAccount)) {
                    if(isset($this->generalTransaction) && !empty($this->generalTransaction)) {
                      foreach ($this->generalTransaction as $general) {
                        if($this->generalAccount==$general['account_type']) {
                          $total_debit += $general['debit_amount'];
                          $total_credit += $general['credit_amount'];
                          if($accountId==1) {
                            $balance += $general['debit_amount'] - $general['credit_amount'];
                          } else if ($accountId==2 || $accountId==5){
                            $balance += $general['credit_amount'] - $general['debit_amount'];
                          }
              ?>
                    <tr>
                      <td><?php echo $general['date']; ?></td>
                      <td><?php echo $general['transaction']; ?></td>
                       <td><?php echo number_format($general['debit_amount'],2,'.',','); ?></td>
                      <td><?php echo number_format($general['credit_amount'],2,'.',','); ?></td>
                      <?php 
                        if(($accountId==1 || $accountId==2 || $accountId==5)) {
                      ?>
                           <td>
                           <?php
                            if($balance<0) {
                                $negative_format = "(".number_format(abs($balance),2,'.',',').")";
                                echo $negative_format;
                             } else {
                                echo number_format($balance,2,'.',',');
                             }
                           ?></td>
                      <?php
                        }
                      ?>
                    </tr>

              <?php   
                        }
                      }
                    }
                  }
              ?>
              <tr>
                  <td><strong>Total</strong></td>
                  <td></td>
                  <td><strong><?php echo number_format($total_debit,2,'.',','); ?></strong></td>
                  <td><strong><?php echo number_format($total_credit,2,'.',','); ?></strong></td>
                   <?php 
                      if(isset($accountId) && !empty($accountId) && ($accountId==1 || $accountId==2 || $accountId==5)) {
                   ?>
                  <td></td>
                  <?php
                      }
                  ?>
              </tr>
            </tbody>
        </table>

</div>

<?php
  }
?>
<script type="text/javascript">
  (function ($) {
  var rules = document.styleSheets[document.styleSheets.length-1].cssRules;
  for (var idx = 0, len = rules.length; idx < len; idx++) {
    $(rules[idx].selectorText).each(function (i, elem) {
      elem.style.cssText += rules[idx].style.cssText;
    });
  }
  $('style').remove();
})(jQuery);

var tableToExcel = (function() {
  var uri = 'data:application/vnd.ms-excel;base64,'
    , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
    , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
    , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
  return function(table, name) {
    if (!table.nodeType) table = document.getElementById(table)
    var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML}
    window.location.href = uri + base64(format(template, ctx))
  }
})()
</script>