<?php
  function convertCurrency($amount, $from){
    $to   = 'SGD';
      $url  = "https://www.google.com/finance/converter?a=$amount&from=$from&to=$to";
      $data = file_get_contents($url);
      preg_match("/<span class=bld>(.*)<\/span>/",$data, $converted);
      $converted = preg_replace("/[^0-9.]/", "", $converted[1]);
      return round($converted, 3);
  }
?>
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li class="active">Credit Note</li>
</ul>
   <div class="row">
       <div class="col-md-12">
            <p>
              <a href="<?php echo $this->sitePath."transaction/invoice"; ?>" class="btn btn-default border-none">Invoice</a><a href="<?php echo $this->sitePath."transaction/credit"; ?>" class="btn btn-danger border-none">Credit Note</a>
            </p>
       </div>
   </div>




<div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
   <?php
    $logSession = new Zend_Session_Namespace('sess_login');
   ?>
   <?php 
        if($logSession->type!=5 && $logSession->proxy_type!=5) {
   ?>
   <div class="row">
       <div class="col-md-12 grid-spacing">
       <a href="<?php echo $this->sitePath."transaction/credit/add"; ?>" class="btn btn-primary" type="button">Add Credit Note</a>
            <!-- Element to pop up -->    
       </div>
   </div>
      
   <?php 
        }
    ?>
 <div class="row">
                  <div class="col-md-12">
                          <h5 style="text-align:right;">
                            <strong>Sort By:</strong>
                            <a href="<?php echo $this->sitePath."transaction/credit" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort=='') { ?><i class="icon-ok"><?php } ?></i> All</a>
                            <a href="<?php echo $this->sitePath."transaction/credit/index/sort/1" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort==1) { ?><i class="icon-ok"><?php } ?></i> Verified</a>
                             <a href="<?php echo $this->sitePath."transaction/credit/index/sort/2" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort==2) { ?><i class="icon-ok"><?php } ?></i> Unverified</a>
                             </h5>
                        </div>

                        <div class="col-md-12">
                            <div class="box-widget">
                                <table class="table responsive" id="credit-table">
                                    <thead>
                                        <tr>
                                            <th>
                                                Date
                                            </th>
                                            <th style="display:none;">Sortable Date</th>
                                            <th>
                                                Credit Note No
                                            </th>
                                            <th>
                                                Customer
                                            </th>
                                            <th>
                                               Description
                                            </th>
                                            <th>
                                               Ref Invoice no
                                            </th>
                                            <th style="text-align:center;">
                                               Total Amount
                                            </th>
                                             <th>
                                                Status
                                            </th>
                                            <th style="text-align:center;">
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php 
                                        if(isset($logSession->proxy_type) && !empty($logSession->proxy_type)) {
                                          $user_type = $logSession->proxy_type;
                                        } else {
                                          $user_type = $logSession->type;
                                        }
                                        $i=1;
                                        foreach($this->result as $results) {
                                            $total_amount   = $results['amount'] + $results['tax_amount'];
                                            if($results['transaction_currency']!='SGD') {
                                               $converted_amount = $results['exchange_rate']*$total_amount;
                                            } else {
                                              $converted_amount = $total_amount;
                                            }
                                    ?>
                                        <tr>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo date("d-m-Y",strtotime($results['date'])); ?></a></td>
                                        <td style="display:none;"><?php echo date("Ymd",strtotime($results['date'])); ?></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo $results['credit_no']; ?></a></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo ucfirst($results['customer_name']); ?></a></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo ucfirst($results['memo']); ?></a></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo $results['invoice_no']; ?></a></td>
                                        <td style="text-align:right;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')" style="margin-right:20px;"><?php echo number_format($converted_amount,2,'.',','); ?></a></td>
                                        <td>
                                        <a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')">
                                        <?php
                                         if($results['credit_status']==1) {
                                            $status = "Approved";
                                         } else if($results['credit_status']==2) {
                                            $status = "Pending Approval";
                                         } else if($results['credit_status']==3) {
                                            $status = "Draft";
                                         } 
                                         if($results['sent_status']==1) {
                                            $status .= " & Sent";
                                         }
                                         echo $status;
                                        ?>
                                        </a>
                                        </td>
                                        <td class="action-bar" style=" ">



                                  <div class="btn-group col-md-2 col-md-offset-3">
                                    <button data-toggle="dropdown" class="btn btn-small dropdown-toggle"> <span class="caret"></span></button>
                                    <ul class="dropdown-menu" style="min-width:0px !important;">
                                        <li><a href="<?php echo $this->sitePath."transaction/credit/view/id/".base64_encode($results['id']); ?>">View</a></li>
                                         <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                       <li><a href="javascript:void(0)" class="<?php if($results['credit_status']==1) { echo "disable-indication disabled"; } ?>"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>')">Edit</a></li>
                                        <?php 
                                            if($results['credit_status']!=3) {
                                         ?>
                                        <li><a href="javascript:void(0)" onclick="return copyCredit('<?php echo base64_encode($results['id']); ?>')">Copy</a></li>
                                        <?php
                                            }
                                        ?>
                                        <?php
                                            }
                                        ?>
                                        <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                         <?php 
                                            if($results['credit_status']!=3) {
                                         ?>
                                         <!-- <li><a href="" class="widget-remove" onclick="return markSent('<?php echo base64_encode($results['id']); ?>')">Mark as sent</a></li> -->
                                         <?php
                                            }
                                        ?>
                                        <li><a href="" class="widget-remove" onclick="return deleteCredit('<?php echo base64_encode($results['id']); ?>')">Delete</a></li>
                                        <?php
                                            }
                                        ?>
                                    </ul>
                                    </div>


                                    <div class="col-md-2" style="margin-left:10px;">
                                        <?php 
                                          if(($logSession->proxy_type==2 || $logSession->type==2)) {
                                              $authorised = 1;
                                          } else if (($logSession->type==3 && $logSession->id==$results['approval_for']) || ($logSession->proxy_type==3 && $logSession->proxy_id==$results['approval_for'])) {
                                             $authorised = 1;
                                          }  else {
                                             $authorised = 2;
                                          }
                                          if($results['credit_status']==1) {
                                        ?>
                                          <a class="btn btn-mini btn-success" href="javascript:void(0)" data-original-title="Unverify"  onclick="changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',2,'<?php echo $authorised; ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          } else if($results['credit_status']==2) {
                                        ?>
                                          <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Verify"  onclick="changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',1,'<?php echo $authorised; ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          } 
                                           if($results['credit_status']==3) {
                                        ?>
                                         <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Draft"><i class="icon-envelope"></i></a>
                                        <?php 
                                          }
                                        ?>
                                        </div>
                                                             
                                        </td>
                                        </tr>
                                    <?php 
                                        }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
<script type="text/javascript">

function changeTransactionStatus(Idvalue,status,auth) {
  if(auth==1) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/credit/index/verifyid/'+Idvalue+'/status/'+status;
    } else if(auth==2) {
        if(status==1) {
          alert('You are not authorized to verify this transaction');
        } else if(status==2) {
          alert('You are not authorized to unverify this transaction');
        }
    }
}

function copyCredit(Idvalue) {
  var confirmMsg = confirm("Are you sure want to copy this credit note? ");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/credit/copy/id/'+Idvalue;
    }
}
 
function markSent(Idvalue) {
  var confirmMsg = confirm("Are you sure want to mark this credit note as sent?");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/credit/index/sentid/'+Idvalue;
    }
}

function deleteCredit(Idvalue) {
  var confirmMsg = confirm("Are you sure want to delete this credit note? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/credit/index/delid/'+Idvalue;
    }
}

function editTransaction(Idvalue,status,type) {
  if(type==5) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/credit/view/id/'+Idvalue;
   // alert("Cannot edit this credit note because transaction is verified");
  } else if(status==1) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/credit/view/id/'+Idvalue;
   // alert("Cannot edit this credit note because transaction is verified");
  } else {
        window.location.href='<?php echo $this->sitePath; ?>transaction/credit/edit/id/'+Idvalue;
    }
}

</script>