<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="account_all">
<?php
$accountArray = array();
 foreach ($this->getAccount as $account) {
    $accountArray[$account['account_type']][$account['account_name']] = $account['account_name'];
 }
// echo '<pre>'; print_r($accountArray); echo '</pre>';
?>
 <h3>Select an account</h3>
                            <div>
                                <ul class="nav nav-tabs" id="myTab">
                                    <li class="active"><a data-toggle="tab" href="#asset">Assets</a></li>
                                    <li class=""><a data-toggle="tab" href="#liability">Liabilities</a></li>
                                    <li class=""><a data-toggle="tab" href="#income">Income</a></li>
                                    <li class=""><a data-toggle="tab" href="#expenses">Expense</a></li>
                                    <li class=""><a data-toggle="tab" href="#equity">Equity</a></li>
                                </ul>
                                <div class="tab-content" id="myTabContent">
                                    <div id="asset" class="tab-pane fade active in">
                                    <ul class="filetree treeview-famfamfam">
                                    <?php
                                        $ass_level1 = 1;
                                        foreach ($this->asset as $levelOne => $listOne) {
                                    ?>
                                        <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelOne; ?></span> 
                                        <ul>
                                            <?php
                                                $ass_level2 = 1;
                                                foreach ($listOne as $levelTwo => $listTwo) {
                                            ?>
                                                <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelTwo; ?></span>
                                                <ul>
                                                    <?php
                                                        foreach ($listTwo as $levelThree => $listThree) {
                                                            if((isset($accountArray[1][$listThree]) && $accountArray[1][$listThree]!=$listThree) || (!isset($accountArray[1][$listThree]))) {
                                                    ?>
                                                        <li><span class="file"><a href="javascript:void(0)" onclick="return accountSelect('1','<?php echo $ass_level1; ?>','<?php echo $ass_level2; ?>','<?php echo $listThree; ?>');"><?php echo "&nbsp;".$listThree; ?></a></span></li>
                                                    <?php
                                                            }
                                                        }
                                                    ?>
                                                </li>
                                                </ul>
                                            <?php
                                                    $ass_level2++;
                                                }
                                            ?>
                                        </ul>
                                    <?php
                                        $ass_level1++;
                                        }
                                    ?>
                                    </ul>
                                    </div>

                                     <div id="liability" class="tab-pane fade">
                                    <ul class="filetree treeview-famfamfam">
                                    <?php
                                        $lia_level1 = 1;
                                        foreach ($this->liability as $levelOne => $listOne) {
                                    ?>
                                        <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelOne; ?></span> 
                                        <ul>
                                            <?php
                                                $lia_level2 = 1;
                                                foreach ($listOne as $levelTwo => $listTwo) {
                                            ?>
                                                <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelTwo; ?></span>
                                                <ul>
                                                    <?php
                                                        foreach ($listTwo as $levelThree => $listThree) {
                                                               if((isset($accountArray[2][$listThree]) && $accountArray[2][$listThree]!=$listThree) || (!isset($accountArray[2][$listThree]))) {
                                                    ?>
                                                        <li><span class="file"><a href="javascript:void(0)" onclick="return accountSelect('2','<?php echo $lia_level1; ?>','<?php echo $lia_level2; ?>','<?php echo $listThree; ?>');"><?php echo "&nbsp;".$listThree; ?></a></span></li>
                                                    <?php
                                                                }
                                                        }
                                                    ?>
                                                </li>
                                                </ul>
                                            <?php
                                                $lia_level2++;
                                                }
                                            ?>
                                        </ul>
                                    <?php
                                         $lia_level1++;
                                        }
                                    ?>
                                    </ul>
                                    </div>

                                    <div id="income" class="tab-pane fade">
                                    <ul class="filetree treeview-famfamfam">
                                    <?php
                                        $inc_level1 = 1;
                                        foreach ($this->income as $levelOne => $listOne) {
                                    ?>
                                        <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelOne; ?></span> 
                                        <ul>
                                            <?php
                                                $inc_level2 = 1;
                                                foreach ($listOne as $levelTwo => $listTwo) {
                                            ?>
                                                <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelTwo; ?></span>
                                                <ul>
                                                    <?php
                                                        foreach ($listTwo as $levelThree => $listThree) {
                                                           if((isset($accountArray[3][$listThree]) && $accountArray[3][$listThree]!=$listThree) || (!isset($accountArray[3][$listThree]))) {
                                                    ?>
                                                        <li><span class="file"><a href="javascript:void(0)" onclick="return accountSelect('3','<?php echo $inc_level1; ?>','<?php echo $inc_level2; ?>','<?php echo $listThree; ?>');"><?php echo "&nbsp;".$listThree; ?></a></span></li>
                                                    <?php
                                                            }
                                                        }
                                                    ?>
                                                </li>
                                                </ul>
                                            <?php
                                                $inc_level2++;
                                                }
                                            ?>
                                        </ul>
                                    <?php
                                         $inc_level1++;
                                        }
                                    ?>
                                    </ul>
                                    </div>

                                    <div id="expenses" class="tab-pane fade">
                                    <ul class="filetree treeview-famfamfam">
                                    <?php
                                        $exp_level1 = 1;
                                        foreach ($this->expense as $levelOne => $listOne) {
                                    ?>
                                        <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelOne; ?></span> 
                                        <ul>
                                            <?php
                                                $exp_level2 = 1;
                                                foreach ($listOne as $levelTwo => $listTwo) {
                                            ?>
                                                <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelTwo; ?></span>
                                                <ul>
                                                    <?php
                                                        foreach ($listTwo as $levelThree => $listThree) {
                                                            if((isset($accountArray[4][$listThree]) && $accountArray[4][$listThree]!=$listThree) || (!isset($accountArray[4][$listThree]))) {
                                                    ?>
                                                        <li><span class="file"><a href="javascript:void(0)" onclick="return accountSelect('4','<?php echo $exp_level1; ?>','<?php echo $exp_level2; ?>','<?php echo $listThree; ?>');"><?php echo "&nbsp;".$listThree; ?></a></span></li>
                                                    <?php
                                                            }
                                                        }
                                                    ?>
                                                </li>
                                                </ul>
                                            <?php
                                                $exp_level2++;
                                                }
                                            ?>
                                        </ul>
                                    <?php
                                        $exp_level1++;
                                        }
                                    ?>
                                    </ul>
                                    </div>

                                    <div id="equity" class="tab-pane fade">
                                    <ul class="filetree treeview-famfamfam">
                                    <?php
                                        $equ_level1 = 1;
                                        foreach ($this->equity as $levelOne => $listOne) {
                                    ?>
                                        <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelOne; ?></span> 
                                        <ul>
                                            <?php
                                                $equ_level2 = 1;
                                                foreach ($listOne as $levelTwo => $listTwo) {
                                            ?>
                                                <li class="closed"><span class="folder"><?php echo "&nbsp;".$levelTwo; ?></span>
                                                <ul>
                                                    <?php
                                                        foreach ($listTwo as $levelThree => $listThree) {
                                                          if((isset($accountArray[5][$listThree]) && $accountArray[5][$listThree]!=$listThree) || (!isset($accountArray[5][$listThree]))) {
                                                    ?>
                                                        <li><span class="file"><a href="javascript:void(0)" onclick="return accountSelect('5','<?php echo $equ_level1; ?>','<?php echo $equ_level2; ?>','<?php echo $listThree; ?>');"><?php echo "&nbsp;".$listThree; ?></a></span></li>
                                                    <?php
                                                           }
                                                        }
                                                    ?>
                                                </li>
                                                </ul>
                                            <?php
                                                $equ_level2++;
                                                }
                                            ?>
                                        </ul>
                                    <?php
                                        $equ_level1++;
                                        }
                                    ?>
                                    </ul>
                                    </div>
                                    
                                </div>
                            </div>
</div>
<!-- <div class="row" id="income_expense" style="display:none;">

 <h3>Edit Account</h3>
<form class="form-horizontal" name="inc_exp" id="inc_exp" method="post">
<div class="form-group">
    <label class="col-lg-8 control-label">None of the fields for this account are editable. Are you sure you want to add this account?</label>
    <input type="hidden" name="action" id="action" value="inc_exp">
    <input type="hidden" name="inc_exp_acc_type" id="inc_exp_acc_type" />
    <input type="hidden" name="inc_exp_acc_val" id="inc_exp_acc_val" />
    <input type="hidden" name="inc_exp_acc_name" id="inc_exp_acc_name" />
 </div>

<div class="form-group">
    <label class="col-lg-2 control-label">&nbsp;</label>
    <div class="col-lg-3">
       <div class="form-actions">
          <button type="submit" id="save" class="btn btn-primary">Save</button>
          <button type="reset" class="btn b-close">Close</button>
      </div>
   </div>
  </div>

</form>
 </div>
 -->

 <div class="row" id="other_accounts" style="display:none;">
<h3>Edit Account</h3>
<hr/>
 <div class="widget-container col-md-12 col-md-offset-1">
     <form class="form-horizontal" id="oth_acc" method="post">
         <div class="form-group">
            <label class="col-lg-3 control-label">Account Name</label>
              <div class="col-lg-7">
                <input type="hidden" name="action" id="action" value="others">
                <input type="hidden" name="oth_acc_type" id="oth_acc_type" />
                <input type="hidden" name="oth_acc_l1" id="oth_acc_l1" />
                <input type="hidden" name="oth_acc_l2" id="oth_acc_l2" />
                <input type="text" name="oth_acc_name" id="oth_acc_name" class="form-control" />
              </div>
        </div>
<!--         <div class="form-group hidden_details">
            <label class="col-lg-3 control-label">Payment / Accruals Account</label>
              <div class="col-lg-7">
               <input type="checkbox" name="pay_account" id="pay_account" value="1" checked />
               &nbsp; This account is for receipt / payment of money (e.g., cash equivalents) or  to record receivables/ payables
              </div>
        </div> -->
        <div class="form-group">
            <label class="col-lg-3 control-label">Currency</label>
                <div class="col-lg-3">
                    <select name="currency" class="select2">
                            <?php 
                              $logSession = new Zend_Session_Namespace('sess_login');
                               $currencySelect = '';
                                if(isset($this->currencies) && !empty($this->currencies)) {
                                foreach ($this->currencies as $key => $currencies) {
                                 /* if(isset($logSession->currency) && !empty($logSession->currency)  && $key==$logSession->currency ) {
                                            $currencySelect = 'selected';
                                   } 
                                    else */if($key=="SGD"){
                                        $currencySelect = 'selected';
                                    }
                                   else{ 
                                        $currencySelect = '';
                                    }
                            ?>
                    <option value="<?php echo $key?>" <?php echo $currencySelect; ?>><?php echo $currencies; ?></option>
                            <?php
                                    }
                                } 
                            ?>
                    </select>  
                 </div>
                </div>


<div class="form-group">
    <label class="col-lg-2 control-label">&nbsp;</label>
    <div class="col-lg-3">
       <div class="form-actions">
          <button type="submit" id="save" class="btn btn-primary">Save</button>
          <button type="reset" class="btn b-close">Close</button>
      </div>
   </div>
  </div>

     </form>
 </div>
</div>


<div class="row" id="edit_other_account" style="display:none;">
<h3>Edit Account</h3>
<hr/>
 <div class="widget-container col-md-12 col-md-offset-1">
     <form class="form-horizontal" id="oth_edit_acc" method="post">
        
     </form>
 </div>
</div>

<div class="row" id="edit_levels" style="display:none;">
<h3>Edit Account Levels</h3>
<hr/>
 <div class="widget-container col-md-12 col-md-offset-1">
     <form class="form-horizontal" id="lev_edit_acc" method="post">
        <div class="form-group">
            <label class="col-lg-2 control-label">Account Level Name</label>
              <div class="col-lg-5">
                <input type="hidden" name="action" id="action" value="account_level">
                <input type="hidden" name="acc_level_type" id="acc_level_type" />
                <input type="hidden" name="original_acc_name" id="original_acc_name" />
                <input type="hidden" name="acc_level_hierarchy" id="acc_level_hierarchy" />
                <input type="text" name="acc_level_name" id="acc_level_name" class="form-control" />
              </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label">&nbsp;</label>
            <div class="col-lg-3">
               <div class="form-actions">
                  <button type="submit" id="save" class="btn btn-primary">Save</button>
                  <button type="reset" class="btn b-close">Close</button>
              </div>
           </div>
        </div>
     </form>
 </div>
</div>


<div class="row" id="opening_balance" style="display:none;">
<h3>Opening Balance</h3>
<hr/>
 <div class="widget-container col-md-12 col-md-offset-1">
     <form class="form-horizontal" id="opening_balance_account" method="post">
        <div class="form-group">
            <label class="col-lg-3 control-label">Account Name</label>
              <div class="col-lg-5">
                <input type="hidden" name="action" id="action" value="opening_balance">
                <input type="hidden" name="balance_account_id" id="balance_account_id" />
                <input type="text" name="balance_account_name" id="balance_account_name" class="form-control" readonly="" />
              </div>
        </div>
         <div class="form-group">
            <label class="col-lg-3 control-label">Opening Debit Balance</label>
              <div class="col-lg-5">
                <input type="text" name="balance_debit" id="balance_debit" class="form-control"  onchange="return numberWithCommas(this.value,this.id);"  />
              </div>
        </div>
         <div class="form-group">
            <label class="col-lg-3 control-label">Opening Credit Balance</label>
              <div class="col-lg-5">
                <input type="text" name="balance_credit" id="balance_credit" class="form-control"  onchange="return numberWithCommas(this.value,this.id);"  />
              </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label">&nbsp;</label>
            <div class="col-lg-3">
               <div class="form-actions">
                  <button type="submit" id="save" class="btn btn-primary">Save</button>
                  <button type="reset" class="btn b-close">Close</button>
              </div>
           </div>
        </div>
     </form>
 </div>
</div>


</div> 

<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/"; ?>">Settings</a></li>
   <li class="active">Chart Of Accounts</li>
</ul>

 <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            </div>
 </div>

  <div class="row">
     <div class="col-md-1 grid-spacing">
        <button class="btn btn-primary" id="add-account" type="button">Add an account</button>
     </div>
     <div class="col-md-1 grid-spacing" style="margin-left:30px;">
        <a class="btn btn-primary" href="<?php echo $this->sitePath."settings/opening-balance"; ?>">Opening Balance</a>
     </div>
  </div>


   <div class="row">


                        <div class="col-md-12">
                            
                            <div class="box-widget">
                                <div class="widget-head clearfix">
                                    <span class="h-icon"><i class="icon-power-cord"></i></span>
                                    <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">List of Accounts</a></h4>
                                    <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(2);" style="color:#fff;">Balance Sheet</a></h4>
                                    <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(3);" style="color:#fff;">Income & Expenses</a></h4>
                                </div>
                                <div class="widget-container">
                                    <div class="widget-block">
                                        <div class="widget-content">
                                            <table class="table responsive">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            GL Number
                                                        </th>
                                                        <th>
                                                            Chart of Accounts
                                                        </th>
                                                        <th>
                                                            Actions
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                    $l=1;
                                                    $active = array();
                                                    $asset_level1 = 1;
                                                    $asset_level2 = 2;
                                                ?>
                                                   <tr class="balance_account assets_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px; cursor: pointer;">Assets</span></td>
                                                    <td></td>
                                                   </tr>


                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->asset as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account assets_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelOne; ?>','2','assets')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>
                                                        </tr>
                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account assets_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(1,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelTwo; ?>','3','assets')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                               //  foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 1 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "assets_".$l2."_".$l3;
                                            ?>
                                                 <tr class="balance_account success assets_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                       <!--  <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','1','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','1')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>

                                                            <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(1); ?>')"  data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                               // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                             <?php 
                                                $l = 2;
                                             ?>
                                             <tr class="balance_account liability_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;  cursor:pointer;">Liability/Credit Card</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->liability as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account liability_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelOne; ?>','2','liabilities')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>
                                                        </tr>


                                             <?php
                                               //  foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 2 && $account['level1']==$l2 && $account['level2']==0) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "liability_".$l2."_".$l3;
                                            ?>
                                                 <tr class="balance_account success liability_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                       <!--  <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','2','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','2')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                            <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(2); ?>')"  data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                        }
                                                    }
                                            ?>

                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account liability_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(2,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelTwo; ?>','3','liabilities')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>

                                                    </tr>

<!--                                                      <?php
                                                             $l4 = "1";
                                                            foreach ($this->taxes as $tax) {
                                                                if($l2==1 && $l3==4) {
                                                                   if($l4<=9) {
                                                                        $l4 = "0".$l4;
                                                                    }
                                                                    $active[] = "liability_".$l2."_".$l3;
                                                        ?>

                                                     <tr class="balance_account success liability_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php 
                                                                if($tax['tax_type']==1) {
                                                                    foreach ($this->purchase as $key => $purchase) {
                                                                      if($tax['tax_code']==$key) {
                                                                        echo $purchase['name'];
                                                                      }
                                                                    }
                                                                  } else if($tax['tax_type']==2) {
                                                                    foreach ($this->supply as $key => $supply) {
                                                                      if($tax['tax_code']==$key) {
                                                                        echo $supply['name'];
                                                                      }
                                                                    }
                                                                  } 
                                                             ?></span></td>
                                                        <td></td>
                                                    </tr>
                                                    <?php 
                                                $l4++;
                                                        }
                                                    }
                                             ?> -->
                                             
                                            <?php
                                               //  foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 2 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "liability_".$l2."_".$l3;
                                            ?>
                                                 <tr class="balance_account success liability_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                        <!-- <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','2','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','2')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                            <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(2); ?>')"  data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                               // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>


                                             <?php 
                                                $l = 3;
                                             ?>
                                             <tr class="other_account income_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;">Income</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->income as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="other_account income_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelOne; ?>','2','income')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>
                                                        </tr>

                                                 <?php
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 3 && $account['level1']==$l2 && $account['level2']==0) {
                                                       /*if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }*/
                                                        $active[] = "income_".$l2."_0";
                                            ?>
                                                 <tr class="other_account success income_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                       <!--  <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','3','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','3')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                        <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(3); ?>')"  data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                       
                                                    }
                                                }
                                            ?>

                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="other_account income_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(3,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td>

                                                       <!--  <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelTwo; ?>','3','income')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                 //foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 3 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "income_".$l2."_".$l3;
                                            ?>
                                                 <tr class="other_account success income_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                        <!-- <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','3','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','3')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                        <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(3); ?>')"  data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                       
                                                    }
                                                }
                                             // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>


                                            <?php 
                                                $l = 4;
                                             ?>
                                             <tr class="other_account expense_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;">Expense</span></td>
                                                    <td></td>
                                                   </tr>

                                            <?php
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 4 && $account['level1']==0 && $account['level2']==0) {
                                                      /* if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }*/
                                                        $active[] = "expense_".$l2."_0";
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>"  style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                        <!-- <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','4','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','4')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                        <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(4); ?>')" data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                        }
                                                    }
                                            ?>





                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->expense as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="other_account expense_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelOne; ?>','2','expense')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>
                                                        </tr>

                                           <?php
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 4 && $account['level1']==$l2 && $account['level2']==0) {
                                                      /* if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }*/
                                                        $active[] = "expense_".$l2."_0";
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>"  style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                        <!-- <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','4','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','4')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                        <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(4); ?>')" data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                        }
                                                    }
                                            ?>

                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="other_account expense_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(4,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelTwo; ?>','3','expense')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                // foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 4 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "expense_".$l2."_".$l3;
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>"  style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                        <!-- <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','4','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','4')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                        <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(4); ?>')" data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                               // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>
                                             

                                             <?php 
                                                $l = 5;
                                             ?>
                                             <tr class="balance_account equity_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;">Equity</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->equity as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account equity_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelOne; ?>','2','equity')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>
                                                        </tr>
                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account equity_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(5,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                         <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelTwo; ?>','3','equity')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                           //      foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 5 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                         $active[] = "equity_".$l2."_".$l3;
                                            ?>
                                                 <tr class="balance_account success equity_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                        <!-- <a href="javascript:void(0)" onclick="editOpeningBalance('<?php echo $account['id']; ?>','<?php echo $account['account_name']; ?>','5','<?php echo $account['debit_opening_balance']; ?>','<?php echo $account['credit_opening_balance']; ?>')" data-original-title="Opening Balance" title="Opening Balance"><i class="icon-notebook"></i></a> -->
                                                        <?php 
                                                            if($account['edit_status']==1) {
                                                        ?>
                                                        <a href="javascript:void(0)" onclick="editAccount('<?php echo base64_encode($account['id']); ?>','edit','5')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a>
                                                            <a href="javascript:void(0)" onclick="getConfirm('<?php echo base64_encode($account['id']); ?>','<?php echo base64_encode($account['account_name']); ?>','<?php echo base64_encode(5); ?>')"  data-original-title="Delete" title="Delete"><i class="icon-remove-2"></i></a>
                                                        <?php
                                                            }
                                                        ?>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                              //  }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


</div>
</div>
<?php
    //print_r($active);
?>
<script type="text/javascript">

$(document).ready(function() {
    <?php 
        foreach ($active as $act) {
           $levels = explode("_", $act);
    ?>
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").show();
        $("<?php echo ".".$act; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$act; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
    <?php
        }
    ?>
});

/*function accountSelect(accountType,accountValue,accountName) {
    if(accountType==3 || accountType==4) {
        $("#account_all").hide();
        $("#income_expense").hide();
        $(".hidden_details").hide();
        $("#oth_acc_type").val(accountType);
        $("#oth_acc_val").val(accountValue);
        $("#oth_acc_name").val(accountName);
        $("#other_accounts").show();
    } else if(accountType==1 || accountType==2 || accountType==5) {
        $("#account_all").hide();
        $("#income_expense").hide();
        $(".hidden_details").show();
        $("#oth_acc_type").val(accountType);
        $("#oth_acc_val").val(accountValue);
        $("#oth_acc_name").val(accountName);
        $("#other_accounts").show();
    }
}*/

function accountSelect(accountType,level1,level2,accountName) {
        $("#account_all").hide();
     //   $("#income_expense").hide();
        $(".hidden_details").hide();
        $("#oth_acc_type").val(accountType);
        $("#oth_acc_l1").val(level1);
        $("#oth_acc_l2").val(level2);
        $("#oth_acc_name").val(accountName);
        $("#other_accounts").show();
}


 $("#add-account").click(function() {
    $("#account_all").show();
    $("#edit_levels").hide();
    $("#opening_balance").hide();
    $("#edit_other_account").hide();
    $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', //uses jQuery easing plugin
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], //x, y
         //   position: [150, 400] //x, y
    });
 });
 $(".b-close").click(function() {
    $(".filetree").treeview();
    $("#income_expense").hide();
    $("#other_accounts").hide();
    $("#edit_other_account").hide();
    $("#account_all").hide();
    $("#opening_balance").hide();
 });

function getConfirm(Idvalue,Accname,Acctype) {
        var confirmMsg = confirm("Are you sure want to delete this account?");
        if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>settings/account/delid/'+Idvalue+'/delname/'+Accname+'/deltype/'+Acctype;
        }
}

function editAccount(Idvalue,action,accType) {
    $("#account_all").hide();
    $("#edit_levels").hide();
    $("#opening_balance").hide();
    $("#edit_other_account").show();
    $('#popup').bPopup({
        contentContainer:'#oth_edit_acc',
        loadUrl: '<?php echo $this->sitePath."settings/"; ?>ajax-display/ajaxAction/edit-account/id/'+Idvalue+'/action/'+action+'/acc_type/'+accType
    });
}

function editOpeningBalance(Idvalue,name,accType,debit,credit) {
    $("#balance_account_id").val(Idvalue);
    $("#balance_account_name").val(name);
    $("#action").val(action);
    $("#balance_debit").val(debit);
    $("#balance_credit").val(credit);
    $("#account_all").hide();
    $("#edit_levels").hide();
    $("#edit_other_account").hide();
    $("#opening_balance").show();
    $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', //uses jQuery easing plugin
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], //x, y
    });
}

function editLevels(value,level,type) {
    $("#account_all").hide();
    $("#opening_balance").hide();
    $("#acc_level_type").val(type);
    $("#acc_level_hierarchy").val(level);
    $("#acc_level_name").val(value);
    $("#original_acc_name").val(value);
    $("#edit_levels").show();
    $("#edit_other_account").hide();
    $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', //uses jQuery easing plugin
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], //x, y
         //   position: [150, 400] //x, y
    });
}

function show(value,location1,location2) {
  /*  if(location1<=9) {
       location1 = "0"+location1;
    }
    if(location2<=9) {
       location2 = "0"+location2;
    }
    if(value==1) {
        $(".assets_"+location1+"_"+location2).slideToggle(1000);
    } else if(value==2) {
        $(".liabilities_"+location1+"_"+location2).slideToggle(1000);
    } else if(value==3) {
        $(".incomes_"+location1+"_"+location2).slideToggle(1000);
    } else if(value==4) {
        $(".expenses_"+location1+"_"+location2).slideToggle(1000);
    } else if(value==5) {
        $(".equities_"+location1+"_"+location2).slideToggle(1000);
    } */
} 

function account(value) {
    if(value==1) {
        $(".assets_active").show();
        $(".liability_active").show();
        $(".income_active").show();
        $(".expense_active").show();
        $(".equity_active").show();
    } else if(value==2) {
        $(".assets_active").show();
        $(".liability_active").show();
        $(".income_active").hide();
        $(".expense_active").hide();
        $(".equity_active").show();
    }  else if(value==3) {
        $(".assets_active").hide();
        $(".liability_active").hide();
        $(".income_active").show();
        $(".expense_active").show();
        $(".equity_active").hide();
    }
}

function show_level(level,value) {
    if(level==2) {
        if(value=='assets') {
            $(".assets_l"+level).slideToggle();
        }
    } 
}


function show_next_level(level,value) {
    if(value=='assets') {
        $(".assets_l3"+level).slideToggle();
    }
}

function numberWithCommas(x,id) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  $("#"+id).val(value);
}

function numberWithCommasInput(x) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  return value;
}

</script>