<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/"; ?>">Settings</a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/user-profiles"; ?>">User Profile</a></li>
   <li class="active">Add</li>
</ul>

                                <div class="row">
                                       <div class="col-md-6 col-md-offset-3">
                                       <?php 
                                            if(isset($this->success) && !empty($this->success)) {
                                       ?>
                                            <div class="alert alert-success">
                                               <strong><?php echo $this->success; ?></strong>
                                            </div>
                                        <?php
                                            } else if(isset($this->error) && !empty($this->error)) {
                                        ?>
                                            <div class="alert alert-danger">
                                               <strong><?php echo $this->error; ?></strong>
                                            </div>
                                        <?php 
                                            }
                                        ?>
                                        </div>
                                 </div>

<div class="row">
                        <div class="col-md-12 widget-module">
                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> User Creation</h4>
                                    
                                </div>

                                <div class="widget-container col-md-12 col-md-offset-3">
                                    <form class="form-horizontal" id="add-user" method="post">
                                   

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">Username <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <input type="email" name="username" id="username" class="form-control" placeholder="Enter Email ID">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">Password <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <input type="password" name="password" id="password" class="form-control" placeholder="Enter password" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" title="Password must contain one uppercase, lowercase, number/special chars and minimum of 8 chars">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">Confirm Password <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <input type="password" name="cpassword" id="cpassword" class="form-control" placeholder="Enter confirm password">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">Account Type <span class="mandatory">*</span></label>
                                            <div class="col-lg-4">
                                                <?php 
                                                    if(isset($this->accTypes) && !empty($this->accTypes)) {
                                                        foreach($this->accTypes as $key => $account) {
                                                            if($key!=1) {
                                                ?>
                                                <input type="radio" id="account_type" name="account_type" value="<?php  echo $key;?>" /> <?php echo $account; ?>
                                                <?php
                                                            }
                                                        }
                                                    }
                                                ?>
                                                <label for="account_type" generated="true" class="error"></label>
                                            </div>
                                        </div>
                                       
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">&nbsp;</label>
                                            <div class="col-lg-3">
                                                <div class="form-actions">
                                                    <button type="submit" id="create" class="btn btn-primary">Submit</button>
                                                    <a href="<?php echo $this->sitePath."settings/user-profiles"; ?>" class="btn btn-default">Cancel</a>

                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
    </div>
</div>
