<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/"; ?>">Settings</a></li>
   <li class="active">Audit Trail</li>
</ul>
  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
   <?php
    $logSession = new Zend_Session_Namespace('sess_login');
   ?>
 <div class="row" style="margin-bottom:20px;">
    <div class="col-md-12">
      <form class="form-horizontal" name="filter-audit" id="filter-audit" method="post">
        <div class="form-group">
          <div class="col-lg-2">
          <label>Filter Type :</label>
            <select class="form-control" id="filter_type" name="filter_type">
            <?php 
              $allselect = '';
              $crselect  = '';
              $mdselect  = '';
              $deselect  = '';
              if($this->filter==1) {
                $allselect = 'selected';
              } else if($this->filter==2) {
                $crselect = 'selected';
              } else if($this->filter==3) {
                $mdselect = 'selected';
              } else if($this->filter==4) {
                $deselect = 'selected';
              } else {
                $allselect = 'selected';
              }
            ?>
                <option value="1" <?php echo $allselect; ?>>All</option>
                <option value="2" <?php echo $crselect; ?>>Created</option>
                <option value="3" <?php echo $mdselect; ?>>Modified</option>
                <option value="4" <?php echo $deselect; ?>>Deleted</option>
            </select>
          </div>
          
        </div>
        <div class="form-group">
          <div class="col-lg-3">
            <button type="submit" id="sytem_log" name="system_log" class="btn btn-info">System Log</button>
            <button type="submit" id="transaction_log" name="transaction_log" class="btn btn-info">Transaction Log</button>
          </div>
        </div>
      </form>
    </div>
</div>


    <div class="row">
      <div class="col-md-2 pull-right">
          <button class="print btn btn-inverse" type="button" rel="content"><i class="icon-print"></i> Print</button>
          <button class="btn btn-inverse" type="button"  onclick="tableToExcel('content', 'Audit Log')"><i class="icon-file-excel"></i> Excel</button>
      </div>
    </div>
                        <h4 align="center">
                          <?php 
                            if(isset($this->type) && $this->type==1) {
                              echo "System Logs";
                            } else if(isset($this->type) && $this->type==2) {
                              echo "Transaction Logs";
                            } 
                          ?>
                        </h4>
 <div class="row" id="content">

                        <div class="col-md-12">


                            <div class="box-widget">
                                <table cellpadding="7" cellspacing="7" class="table paper-tbl-theme table-bordered responsive  table-paper" width="100%">
                                    <thead>
                                        <tr>
                                            <th>
                                                Updated On
                                            </th>
                                            <th>
                                                User
                                            </th>
                                            <th>
                                                Event
                                            </th>
                                            <th>
                                                Name
                                            </th>
                                            <!-- <th>
                                                History
                                            </th> -->
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                      foreach($this->audit as $result) {
                                    ?>
                                      <tr>
                                          <td><?php echo date('d-m-Y H:i:s',strtotime($result['timestamp'])); ?></td>
                                          <td>
                                          <?php
                                            foreach ($this->users as $user) {
                                              if($user['id']==$result['fkuser_id']) {
                                                if($user['account_type']==0 || $user['account_type']==1) {
                                                  $account_type = 'Developer';
                                                } else if($user['account_type']==2) {
                                                  $account_type = 'Super User';
                                                } else if($user['account_type']==3) {
                                                  $account_type = 'Manager';
                                                } else if($user['account_type']==4) {
                                                  $account_type = 'User';
                                                } else if($user['account_type']==5) {
                                                  $account_type = 'Viewer';
                                                }
                                                echo $user['username']." (".$account_type.")";
                                              }
                                            }
                                          ?>
                                          </td>
                                          <?php 
                                            if($result['source']==1) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/audit-income/id/".base64_encode($result['reference']).'" target="_blank">Income</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/audit-income/id/".base64_encode($result['reference']).'" target="_blank">Income</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : <a href="'.$this->sitePath."transaction/income/view/id/".base64_encode($result['reference']).'" target="_blank">Income</a></td>';
                                              } else if($result['event']==6) {
                                                echo '<td>Verified : <a href="'.$this->sitePath."transaction/income/view/id/".base64_encode($result['reference']).'" target="_blank">Income Transaction</a></td>';
                                              } else if($result['event']==7) {
                                                echo '<td>Unverified : <a href="'.$this->sitePath."transaction/income/view/id/".base64_encode($result['reference']).'" target="_blank">Income Transaction</a></td>';
                                              }  else if($result['event']==8) {
                                                echo '<td>Draft : <a href="'.$this->sitePath."settings/audit-income/id/".base64_encode($result['reference']).'" target="_blank">Income Transaction</a></td>';
                                              } 
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/1/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==2) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/audit-expense/id/".base64_encode($result['reference']).'" target="_blank">Expense</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/audit-expense/id/".base64_encode($result['reference']).'" target="_blank">Expense</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : <a href="'.$this->sitePath."transaction/expense/view/id/".base64_encode($result['reference']).'" target="_blank">Expense</a></td>';
                                              } else if($result['event']==6) {
                                                echo '<td>Verified : <a href="'.$this->sitePath."transaction/expense/view/id/".base64_encode($result['reference']).'" target="_blank">Expense Transaction</a></td>';
                                              } else if($result['event']==7) {
                                                echo '<td>Unverified : <a href="'.$this->sitePath."transaction/expense/view/id/".base64_encode($result['reference']).'" target="_blank">Expense Transaction</a></td>';
                                              }  else if($result['event']==8) {
                                                echo '<td>Draft : <a href="'.$this->sitePath."settings/audit-expense/id/".base64_encode($result['reference']).'" target="_blank">Expense Transaction</a></td>';
                                              } 
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/2/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==3) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/audit-invoice/id/".base64_encode($result['reference']).'" target="_blank">Invoice</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/audit-invoice/id/".base64_encode($result['reference']).'" target="_blank">Invoice</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : <a href="'.$this->sitePath."transaction/invoice/view/id/".base64_encode($result['reference']).'" target="_blank">Invoice</a></td>';
                                              } else if($result['event']==6) {
                                                echo '<td>Verified : <a href="'.$this->sitePath."transaction/invoice/view/id/".base64_encode($result['reference']).'" target="_blank">Invoice Transaction</a></td>';
                                              } else if($result['event']==7) {
                                                echo '<td>Unverified : <a href="'.$this->sitePath."transaction/invoice/view/id/".base64_encode($result['reference']).'" target="_blank">Invoice Transaction</a></td>';
                                              }  else if($result['event']==8) {
                                                echo '<td>Draft : <a href="'.$this->sitePath."settings/audit-invoice/id/".base64_encode($result['reference']).'" target="_blank">Invoice Transaction</a></td>';
                                              } 
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/3/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==4) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/audit-credit/id/".base64_encode($result['reference']).'" target="_blank">Credit Note</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/audit-credit/id/".base64_encode($result['reference']).'" target="_blank">Credit Note</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : <a href="'.$this->sitePath."transaction/credit/view/id/".base64_encode($result['reference']).'" target="_blank">Credit Note</a></td>';
                                              } else if($result['event']==6) {
                                                echo '<td>Verified : <a href="'.$this->sitePath."transaction/credit/view/id/".base64_encode($result['reference']).'" target="_blank">Credit Note Transaction</a></td>';
                                              } else if($result['event']==7) {
                                                echo '<td>Unverified : <a href="'.$this->sitePath."transaction/credit/view/id/".base64_encode($result['reference']).'" target="_blank">Credit Note Transaction</a></td>';
                                              }  else if($result['event']==8) {
                                                echo '<td>Draft : <a href="'.$this->sitePath."settings/audit-credit/id/".base64_encode($result['reference']).'" target="_blank">Credit Note Transaction</a></td>';
                                              } 
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/4/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==5) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/audit-journal/id/".base64_encode($result['reference']).'" target="_blank">Journal Entry</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/audit-journal/view/id/".base64_encode($result['reference']).'" target="_blank">Journal Entry</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : <a href="'.$this->sitePath."transaction/journal/view/id/".base64_encode($result['reference']).'" target="_blank">Journal Entry</a></td>';
                                              } else if($result['event']==6) {
                                                echo '<td>Verified : <a href="'.$this->sitePath."transaction/journal/view/id/".base64_encode($result['reference']).'" target="_blank">Journal Entry Transaction</a></td>';
                                              } else if($result['event']==7) {
                                                echo '<td>Unverified : <a href="'.$this->sitePath."transaction/journal/view/id/".base64_encode($result['reference']).'" target="_blank">Journal Entry Transaction</a></td>';
                                              }  else if($result['event']==8) {
                                                echo '<td>Draft : <a href="'.$this->sitePath."settings/audit-journal/id/".base64_encode($result['reference']).'" target="_blank">Journal Entry Transaction</a></td>';
                                              } 
                                              echo '<td></td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/5/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==6) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."business/customer/view/id/".base64_encode($result['reference']).'" target="_blank">Customer</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."business/customer/view/id/".base64_encode($result['reference']).'" target="_blank">Customer</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : <a href="'.$this->sitePath."business/customer/view/id/".base64_encode($result['reference']).'" target="_blank">Customer</a></td>';
                                              }
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/6/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==7) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."business/vendor/view/id/".base64_encode($result['reference']).'" target="_blank">Vendor</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."business/vendor/view/id/".base64_encode($result['reference']).'" target="_blank">Vendor</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : <a href="'.$this->sitePath."business/vendor/view/id/".base64_encode($result['reference']).'" target="_blank">Vendor</a></td>';
                                              }
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/7/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==8) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/account".'" target="_blank">Account</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/account".'" target="_blank">Account</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : Account</td>';
                                              }
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/8/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==9) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/edit-tax/id/".base64_encode($result['reference']).'" target="_blank">Tax</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/edit-tax/id/".base64_encode($result['reference']).'" target="_blank">Tax</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : Tax</td>';
                                              }
                                               else if($result['event']==4) {
                                                echo '<td><a href="'.$this->sitePath."settings/edit-tax/id/".base64_encode($result['reference']).'" target="_blank">Tax set as active</a></td>';
                                              }
                                               else if($result['event']==5) {
                                                echo '<td><a href="'.$this->sitePath."settings/edit-tax/id/".base64_encode($result['reference']).'" target="_blank">Tax set as inactive</a></td>';
                                              }
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/9/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==10) {
                                              if($result['event']==1) {
                                                echo '<td>Added : <a href="'.$this->sitePath."settings/edit-product/id/".base64_encode($result['reference']).'" target="_blank">Product</a></td>';
                                              } else if($result['event']==2) {
                                                echo '<td>Edited : <a href="'.$this->sitePath."settings/edit-product/id/".base64_encode($result['reference']).'" target="_blank">Product</a></td>';
                                              } else if($result['event']==3) {
                                                echo '<td>Deleted : Product</td>';
                                              }
                                              echo '<td>'.ucfirst($result['name_number']).'</td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/10/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                            } else if($result['source']==11) {
                                              if($result['event']==1) {
                                                if($result['name_number']=='Income') {
                                                   echo '<td>Added Payment : <a href="'.$this->sitePath."settings/audit-payment/id/".base64_encode($result['reference']).'" target="_blank">Income</a></td>';
                                                } else if($result['name_number']=='Expense') {
                                                   echo '<td>Added Payment : <a href="'.$this->sitePath."settings/audit-payment/id/".base64_encode($result['reference']).'" target="_blank">Expense</a></td>';
                                                } else if($result['name_number']=='Invoice') {
                                                   echo '<td>Added Payment : <a href="'.$this->sitePath."settings/audit-payment/id/".base64_encode($result['reference']).'" target="_blank">Invoice</a></td>';
                                                }

                                                echo '<td></td>';
                                                /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/1/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                              } else if($result['event']==2) {
                                                if($result['name_number']=='Income') {
                                                   echo '<td>Updated Payment : <a href="'.$this->sitePath."settings/audit-payment/id/".base64_encode($result['reference']).'" target="_blank">Income</a></td>';
                                                } else if($result['name_number']=='Expense') {
                                                   echo '<td>Updated Payment : <a href="'.$this->sitePath."settings/audit-payment/id/".base64_encode($result['reference']).'" target="_blank">Expense</a></td>';
                                                } else if($result['name_number']=='Invoice') {
                                                   echo '<td>Updated Payment : <a href="'.$this->sitePath."settings/audit-payment/id/".base64_encode($result['reference']).'" target="_blank">Invoice</a></td>';
                                                }
                                                echo '<td></td>';
                                                /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/1/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                              } else if($result['event']==3) {
                                                if($result['name_number']=='Income') {
                                                   echo '<td>Deleted Payment : Income</td>';
                                                } else if($result['name_number']=='Expense') {
                                                   echo '<td>Deleted Payment : Expense</td>';
                                                } else if($result['name_number']=='Invoice') {
                                                   echo '<td>Deleted Payment : Invoice</td>';
                                                }
                                                echo '<td></td>';
                                                /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/1/id/".$result['reference'].'" target="_blank">View</a></td>';*/
                                              }
                                            }  else if($result['source']==12) {
                                              echo '<td>Logged In</td>';
                                              echo '<td></td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/12/id/".$result['fkuser_id'].'" target="_blank">View</a></td>';*/
                                            }   else if($result['source']==13) {
                                              echo '<td>Logged Out</td>';
                                              echo '<td></td>';
                                              /*echo '<td><a href="'.$this->sitePath."settings/audit-history/type/13/id/".$result['fkuser_id'].'" target="_blank">View</a></td>';*/
                                            } 
                                          ?>
                                      </tr>
                                    <?php
                                      }
                                    ?>                                  
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
<script type="text/javascript">
  (function ($) {
  var rules = document.styleSheets[document.styleSheets.length-1].cssRules;
  for (var idx = 0, len = rules.length; idx < len; idx++) {
    $(rules[idx].selectorText).each(function (i, elem) {
      elem.style.cssText += rules[idx].style.cssText;
    });
  }
  $('style').remove();
})(jQuery);

var tableToExcel = (function() {
  var uri = 'data:application/vnd.ms-excel;base64,'
    , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
    , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
    , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
  return function(table, name) {
    if (!table.nodeType) table = document.getElementById(table)
    var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML}
    window.location.href = uri + base64(format(template, ctx))
  }
})()
</script>