<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/"; ?>">Settings</a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/tax"; ?>">Sales Tax</a></li>
   <li class="active">Edit</li>
</ul>


                                <div class="row">
                                       <div class="col-md-6 col-md-offset-3">
                                       <?php 
                                            if(isset($this->success) && !empty($this->success)) {
                                       ?>
                                            <div class="alert alert-success">
                                               <strong><?php echo $this->success; ?></strong>
                                            </div>
                                        <?php
                                            } else if(isset($this->error) && !empty($this->error)) {
                                        ?>
                                            <div class="alert alert-danger">
                                               <strong><?php echo $this->error; ?></strong>
                                            </div>
                                        <?php 
                                            }
                                        ?>
                                        </div>
                                 </div>


<div class="row">
                        <div class="col-md-12 widget-module">
                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Update Tax</h4>
                                    
                                </div>

                                <div class="widget-container col-md-12 col-md-offset-3">
                                    <form class="form-horizontal" id="add-tax" method="post">


                                    <div class="form-group">
                                            <label class="col-lg-2 control-label">Tax Type <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                            <select class="form-control" id="tax_type" name="tax_type" onchange="return taxCategory(this.value);">
                                                <?php
                                                    if($this->result[0]['tax_type']==1) {
                                                ?>
                                                <option value="1" selected>Purchase</option>
                                                <option value="2">Supply</option>
                                                <?php 
                                                    } else {
                                                ?>
                                                <option value="1">Purchase</option>
                                                <option value="2" selected>Supply</option>
                                                <?php 
                                                    }
                                                ?>
                                            </select>
                                            </div>
                                    </div>

                                    <div class="form-group">
                                            <label class="col-lg-2 control-label">Tax Code <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                            <select class="form-control" id="category_code" name="category_code" onchange="return taxDetails(this.value);">
                                            <?php 
                                                if($this->result[0]['tax_type']==1) {
                                                    foreach ($this->purchase as $key => $purchase) {
                                                        if($key==$this->result[0]['tax_code']) {
                                                            $value = $this->result[0]['tax_code']."_".$this->result[0]['tax_percentage']."_".$this->result[0]['description'];
                                                            $category_select = 'selected';
                                                        } else {
                                                            $value = $key."_".$purchase['percentage']."_".$purchase['description'];
                                                            $category_select = '';
                                                        }
                                            ?>
                                                    <option value="<?php echo $value; ?>" <?php echo $category_select; ?>><?php echo $purchase['name'] ?></option>
                                            <?php
                                                    }
                                                } else if($this->result[0]['tax_type']==1) {
                                                    foreach ($this->supply as $key => $supply) {
                                                        if($key==$this->result[0]['tax_code']) {
                                                            $value = $this->result[0]['tax_code']."_".$this->result[0]['tax_percentage']."_".$this->result[0]['description'];
                                                            $category_select = 'selected';
                                                        } else {
                                                            $value = $key."_".$supply['percentage']."_".$supply['description'];
                                                            $category_select = '';
                                                        }
                                            ?>
                                                <option value="<?php echo $value; ?>" <?php echo $category_select; ?>><?php echo $supply['name'] ?></option>
                                            <?php 
                                                    }
                                                }
                                            ?>
                                            </select>
                                            </div>
                                    </div>


                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">Tax Percentage <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <input type="text" name="percentage" id="percentage" class="form-control" placeholder="Enter Percentage" autocomplete="off" value="<?php echo $this->result[0]['tax_percentage']; ?>" />
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">Description <span class="mandatory">*</span></label>
                                            <div class="col-lg-3">
                                                <textarea class="form-control" name="description" id="description" placeholder="Description about tax" autocomplete="off" style="height:200px;"><?php echo  $this->result[0]['description']; ?></textarea>
                                            </div>
                                        </div>
                                    
                                       
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">&nbsp;</label>
                                            <div class="col-lg-3">
                                                <div class="form-actions">
                                                    <button type="submit" id="send" class="btn btn-primary">Submit</button>
                                                    <button type="button" class="btn" onclick="return back();">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
    </div>
</div>
<script type="text/javascript">
    function back() {
        window.location.href='<?php echo $this->sitePath; ?>settings/tax';
    }

    function taxCategory(value) {
        var purchase = '<option value="">Select Tax Category</option>';
        var supply   = '<option value="">Select Tax Category</option>';
        <?php 
            foreach ($this->purchase as $key => $purchase) {
        ?>
            purchase += '<option value="<?php echo $key."_".$purchase['percentage']."_".$purchase['description']; ?>"><?php echo $purchase['name']; ?></option>';
        <?php
            }
        ?>

        <?php 
            foreach ($this->supply as $key => $supply) {
        ?>
            supply += '<option value="<?php echo $key."_".$supply['percentage']."_".$supply['description']; ?>"><?php echo $supply['name']; ?></option>';
        <?php
            }
        ?>

        if(value==1) {
            $("#category_code").html(purchase);
        } else if(value==2) {
            $("#category_code").html(supply);
        }
        $("#percentage").val("");
        $("#description").val("");
    }

    function taxDetails(value) {
        var details  = value.split('_');
        $("#percentage").val(details[1]);
        $("#description").val(details[2]);
    }
</script>