<div class="main-container">
<div class="container">
<div class="board-widget">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li class="active">General Settings</li>
</ul>

                        <div class="row">
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/company"; ?>"><i class="icon-briefcase"></i><span class="board-widget-label">Company Information</span></a>
                                </div>
                            </div>
                            <div class=" col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/account"; ?>"><i class="icon-file-8"></i><span class="board-widget-label">Chart of Accounts Maintenance </span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/products"; ?>"><i class="icon-bag"></i><span class="board-widget-label">List of Products and Services</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/invoice-and-credit-note-customization"; ?>"><i class="icon-indent-right"></i><span class="board-widget-label">Invoice & Credit Note Customisation</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/tax"; ?>"><i class="icon-clipboard-4"></i><span class="board-widget-label">Tax Code Table</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/notification"; ?>"><i class="icon-bubbles-7"></i><span class="board-widget-label">Notifications</span></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/theme"; ?>"><i class="icon-stack-list"></i><span class="board-widget-label">Theme Manager</span></a>
                                </div>
                            </div>
                            <!-- <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="#"><i class="icon-yelp"></i><span class="board-widget-label">Language Option</span></a>
                                </div>
                            </div> -->
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/backup"; ?>"><i class="icon-box-remove"></i><span class="board-widget-label">Restore/Delete Account</span></a>
                                </div>
                            </div>
                             <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."import/"; ?>"><i class="icon-upload-3"></i><span class="board-widget-label">Import Data</span></a>
                                </div>
                            </div>

                        </div>

<ul class="breadcrumb">
    <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
    <li class="active">Security Settings</li>
</ul>


                        <div class="row">
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/user-profiles"; ?>"><i class="icon-profile"></i><span class="board-widget-label">User Profiles</span></a>
                                </div>
                            </div>
                            <!-- <div class=" col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="#"><i class=" icon-factory"></i><span class="board-widget-label">Process Controls</span></a>
                                </div>
                            </div> -->
                            <div class="col-sm-6 col-md-3">
                                <div class="board-widget-wrap">
                                    <a href="<?php echo $this->sitePath."settings/audit-trail"; ?>"><i class="icon-files"></i><span class="board-widget-label">Audit Trails</span></a>
                                </div>
                            </div>
                        </div>


                    </div>
</div>
</div>