
<div class="main-container">
<div class="container">

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/"; ?>">Settings</a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/account"; ?>">Chart Of Accounts</a></li>
   <li class="active">Opening Balance</li>
</ul>

 <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            </div>
 </div>


   <div class="row">


                        <div class="col-md-12">
                            
                            <div class="box-widget">
                                <div class="widget-head clearfix">
                                    <span class="h-icon"><i class="icon-power-cord"></i></span>
                                    <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(1);" style="color:#fff;">List of Accounts</a></h4>
                                    <!-- <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(2);" style="color:#fff;">Balance Sheet</a></h4>
                                    <h4 class="pull-left"><a href="javascript:void(0)" onclick="return account(3);" style="color:#fff;">Income & Expenses</a></h4> -->
                                </div>
                                <div class="widget-container">
                                    <div class="widget-block">
                                        <div class="widget-content">
                                        <form class="form-horizontal" id="add-opening-balance" method="post">
                                            <table class="table responsive">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            GL Number
                                                        </th>
                                                        <th>
                                                            Chart of Accounts
                                                        </th>
                                                        <th>
                                                            Debit
                                                        </th>
                                                        <th>
                                                            Credit
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                    $l=1;
                                                    $active = array();
                                                    $asset_level1 = 1;
                                                    $asset_level2 = 2;
                                                    $total_debit  = 0.00;
                                                    $total_credit = 0.00;
                                                ?>
                                                   <tr class="balance_account assets_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px; cursor: pointer;">Assets</span></td>
                                                    <td></td>
                                                    <td></td>
                                                   </tr>


                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->asset as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account assets_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelOne; ?>','2','assets')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>
                                                            <td></td>
                                                        </tr>
                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account assets_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(1,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td><!-- <a href="javascript:void(0)" onclick="editLevels('<?php echo $levelTwo; ?>','3','assets')" data-original-title="Edit" title="Edit"><i class="icon-pencil"></i></a> --></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                               //  foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 1 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "assets_".$l2."_".$l3;
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="balance_account success assets_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                               // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                             <?php 
                                                $l = 2;
                                             ?>
                                             <tr class="balance_account liability_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;  cursor:pointer;">Liability/Credit Card</span></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->liability as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account liability_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                            <td></td>
                                                        </tr>


                                             <?php
                                               //  foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 2 && $account['level1']==$l2 && $account['level2']==0) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "liability_".$l2."_".$l3;
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="balance_account success liability_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                        }
                                                    }
                                            ?>

                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account liability_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(2,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                               //  foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 2 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "liability_".$l2."_".$l3;
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="balance_account success liability_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                               // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>


                                             <?php 
                                                $l = 3;
                                             ?>
                                             <tr class="other_account income_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;">Income</span></td>
                                                    <td></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->income as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="other_account income_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                            <td></td>
                                                        </tr>

                                                 <?php
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 3 && $account['level1']==$l2 && $account['level2']==0) {
                                                       /*if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }*/
                                                        $active[] = "income_".$l2."_0";
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="other_account success income_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                       
                                                    }
                                                }
                                            ?>

                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="other_account income_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(3,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>

                                                        <td></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                 //foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 3 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "income_".$l2."_".$l3;
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="other_account success income_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                       
                                                    }
                                                }
                                             // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>


                                            <?php 
                                                $l = 4;
                                             ?>
                                             <tr class="other_account expense_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;">Expense</span></td>
                                                    <td></td>
                                                    <td></td>
                                                   </tr>

                                            <?php
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 4 && $account['level1']==0 && $account['level2']==0) {
                                                      /* if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }*/
                                                        $active[] = "expense_".$l2."_0";
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>"  style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                        }
                                                    }
                                            ?>





                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->expense as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="other_account expense_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                            <td></td>
                                                        </tr>

                                           <?php
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 4 && $account['level1']==$l2 && $account['level2']==0) {
                                                      /* if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }*/
                                                        $active[] = "expense_".$l2."_0";
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>"  style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                        }
                                                    }
                                            ?>

                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="other_account expense_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(4,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                        <td></td>
                                                        <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                                // foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 4 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                        $active[] = "expense_".$l2."_".$l3;
                                                        $total_debit  += $account['debit_opening_balance'];
                                                        $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="other_account success expense_<?php echo $l2."_".$l3; ?>"  style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                               // }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>
                                             

                                             <?php 
                                                $l = 5;
                                             ?>
                                             <tr class="balance_account equity_active">
                                                    <td><?php echo $l."-0000-00"; ?></td>
                                                    <td><span style="font-weight:bold; font-size:14px;">Equity</span></td>
                                                    <td></td>
                                                    <td></td>
                                                   </tr>
                                                   <?php
                                                      $l2 = "1";
                                                      foreach ($this->equity as $levelOne => $listOne) {
                                                        if($l2<=9) {
                                                            $l2 = "0".$l2;
                                                        }
                                                   ?>
                                                        <tr class="balance_account equity_<?php echo $l2; ?>" style="display:none; cursor: pointer;">
                                                            <td><?php echo $l."-".$l2."00-00"; ?></td>
                                                            <td><span style="margin-left:10px;font-weight:bold; font-size:13px;"><?php echo $levelOne; ?></span></td>
                                                            <td></td>
                                                            <td></td>
                                                        </tr>
                                                <?php
                                                    $l3 = "1";
                                                    foreach ($listOne as $levelTwo => $listTwo) {
                                                        if($l3<=9) {
                                                            $l3 = "0".$l3;
                                                        }
                                                ?>
                                                    <tr class="balance_account equity_<?php echo $l2.$l3; ?>" style="display:none;">
                                                        <td><?php echo $l."-".$l2.$l3."-00"; ?></td>
                                                        <td><span style="margin-left:20px; font-weight:bold; font-size:12px; cursor: pointer;" onclick="return show(5,<?php echo $l2; ?>,<?php echo $l3; ?>);"><?php echo $levelTwo; ?></span></td>
                                                         <td></td>
                                                         <td></td>

                                                    </tr>
                                            <?php
                                                 $l4 = "1";
                                           //      foreach ($listTwo as $levelThree => $listThree) {
                                                    foreach ($this->getAccount as $account) {
                                                        if($account['account_type'] == 5 && $account['level1']==$l2 && $account['level2']==$l3) {
                                                       if($l4<=9) {
                                                            $l4 = "0".$l4;
                                                        }
                                                         $active[] = "equity_".$l2."_".$l3;
                                                         $total_debit  += $account['debit_opening_balance'];
                                                         $total_credit += $account['credit_opening_balance'];
                                            ?>
                                                 <tr class="balance_account success equity_<?php echo $l2."_".$l3; ?>" style="display:;">
                                                        <td><?php echo $l."-".$l2.$l3."-".$l4; ?></td>
                                                        <td><span style="margin-left:30px; font-size:12px; font-style:italic;"><?php echo $account['account_name']; ?></span></td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_debit[<?php echo $account['id']; ?>]" id="account_debit_<?php echo $account['id']; ?>" class="form-control amount-align debit-opening-balance account_debit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['debit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="col-lg-8">
                                                                <input type="text" name="account_credit[<?php echo $account['id']; ?>]" id="account_credit_<?php echo $account['id']; ?>" class="form-control amount-align credit-opening-balance account_credit_<?php echo $account['id']; ?>" value="<?php echo number_format($account['credit_opening_balance'],2,'.',','); ?>" onchange="return checkAmount(this);"/>
                                                            </div>
                                                        </td>

                                                    </tr>

                                            <?php 
                                                $l4++;
                                                        }
                                                    }
                                              //  }
                                                    $l3++;
                                                }
                                                    $l2++;
                                                }
                                             ?>

                                             

                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <th></th>
                                                    <th><strong>Total</strong></th>                                                    
                                                    <th>
                                                        <div class="col-lg-8">
                                                            <input type="text" name="total_debit" id="total_debit" class="form-control amount-align" readonly value="<?php echo number_format($total_debit,2,'.',','); ?>" />
                                                        </div>
                                                    </th>
                                                    <th>
                                                        <div class="col-lg-8">
                                                             <input type="text" name="total_credit" id="total_credit" class="form-control amount-align" readonly value="<?php echo number_format($total_credit,2,'.',','); ?>" />
                                                        </div>
                                                    </th>
                                                </tr>
                                             </tfoot>
                                            </table>
                                           
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-5 control-label">&nbsp;</label>
                                            <div class="col-lg-3">
                                                <div class="form-actions">
                                                    <button type="submit" id="create" class="btn btn-primary">Submit</button>
                                                    <a href="<?php echo $this->sitePath."settings/account/" ?>" class="btn btn-default">Cancel</a>
                                                </div>
                                            </div>
                                        </div>
                                         </form>
                                    </div>
                                </div>
                            </div>



                        </div>
                    </div>


</div>
</div>
<?php
    //print_r($active);
?>
<script type="text/javascript">

$(document).ready(function() {
    <?php 
        foreach ($active as $act) {
           $levels = explode("_", $act);
    ?>
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").show();
        $("<?php echo ".".$act; ?>").show();
        $("<?php echo ".".$levels[0]."_".$levels[1]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$levels[0]."_".$levels[1].$levels[2]; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
        $("<?php echo ".".$act; ?>").addClass("<?php echo $levels[0]."_active"; ?>");
    <?php
        }
    ?>
});




function account(value) {
    if(value==1) {
        $(".assets_active").show();
        $(".liability_active").show();
        $(".income_active").show();
        $(".expense_active").show();
        $(".equity_active").show();
    } else if(value==2) {
        $(".assets_active").show();
        $(".liability_active").show();
        $(".income_active").hide();
        $(".expense_active").hide();
        $(".equity_active").show();
    }  else if(value==3) {
        $(".assets_active").hide();
        $(".liability_active").hide();
        $(".income_active").show();
        $(".expense_active").show();
        $(".equity_active").hide();
    }
}

function checkAmount(data) {
    var currentId   = data.id;
    var currentAmount   = data.value;
    var splitValues = currentId.split("_");
    if(splitValues[0]!='' && splitValues[1]!='' && splitValues[2]!='') {
        if(splitValues[1]=='debit') {
            var creditId     = 'account_credit_'+splitValues[2];
            var creditValue  = $("#"+creditId).val();
            var formattedValue = numberWithOutCommasInput(creditValue);
            if(Number(formattedValue!=0)) {
                var confirmMsg = confirm('Are you sure want to enter debit amount for this account then the credit amount will become zero?');
                if(confirmMsg) {
                    var formatAmount = numberWithCommasInput(currentAmount);
                    $("#"+creditId).val('0.00');
                    $("#"+currentId).val(formatAmount);
                } else {
                    $("#"+currentId).val('0.00');
                }
            } else {
                var formatAmount = numberWithCommasInput(currentAmount);
                $("#"+currentId).val(formatAmount);
            }
        } else if(splitValues[1]=='credit') {
            var debitId     = 'account_debit_'+splitValues[2];
            var debitValue  = $("#"+debitId).val();
            var formattedValue = numberWithOutCommasInput(debitValue);
            if(Number(formattedValue!=0)) {
                var confirmMsg = confirm('Are you sure want to enter credit amount for this account then the debit amount will become zero?');
                if(confirmMsg) {
                    var formatAmount = numberWithCommasInput(currentAmount);
                    $("#"+debitId).val('0.00');
                    $("#"+currentId).val(formatAmount);
                } else {
                    $("#"+currentId).val('0.00');
                }
            } else {
                var formatAmount = numberWithCommasInput(currentAmount);
                $("#"+currentId).val(formatAmount);
            }
        }

        var debit_opening_balance  = 0.00;
        var credit_opening_balance = 0.00;
        var debit_balance = $(".debit-opening-balance");
        debit_balance.each(function() {
            debit_opening_balance += parseFloat(numberWithOutCommasInput(this.value));
            console.log(debit_opening_balance);
        });
        var credit_balance = $(".credit-opening-balance");
        credit_balance.each(function() {
            credit_opening_balance += parseFloat(numberWithOutCommasInput(this.value));
            console.log(credit_opening_balance);
        });

        $("#total_debit").val(numberWithCommasInput(debit_opening_balance));
        $("#total_credit").val(numberWithCommasInput(credit_opening_balance));
    } 
}

function numberWithCommas(x,id) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  $("#"+id).val(value);
}

function numberWithCommasInput(x) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  return value;
}

function numberWithOutCommasInput(x) {
  x=x.replace(/\,/g,''); 
  var value = parseFloat(x).toFixed(2);
  return value;
}

</script>