<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."default/settings/"; ?>">Settings</a></li>
   <li class="active">Sales Tax</li>
</ul>

  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
   <?php
    $logSession = new Zend_Session_Namespace('sess_login');
   ?>
   <?php 
        if($logSession->type!=5) {
   ?>
   <div class="row">
       <div class="col-md-12 grid-spacing">
       <a href="<?php echo $this->sitePath."settings/add-tax"; ?>" class="btn btn-primary" type="button" >Add Tax</a>
            <!-- Element to pop up -->    
       </div>
   </div>
   <?php 
        }
    ?>
   <div class="row">


                        <div class="col-md-12">
                            
                            <div class="box-widget">
                                <div class="widget-head clearfix">
                                    <span class="h-icon"><i class="icon-power-cord"></i></span>
                                    <h4 class="pull-left">Tax Codes</h4>
                                </div>
                                <div class="widget-container">
                                    <div class="widget-block">
                                        <div class="widget-content">
                                            <table class="table responsive">
                                    <thead>
                                        <tr>
                                            <th>
                                                Tax Type
                                            </th>
                                            <th>
                                                Tax Code
                                            </th>
                                            <th>
                                                Percentage
                                            </th>
                                            <th>
                                                Description
                                            </th>
                                            <th>
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php 
                                      if(isset($this->taxes) && !empty($this->taxes)) {
                                        $i=1;
                                        foreach($this->taxes as $tax) {
                                    ?>
                                        <tr>
                                        <td>
                                        <?php 
                                          if($tax['tax_type']==1) {
                                            echo "Purchase";
                                          } else if($tax['tax_type']==2) {
                                            echo "Supply";
                                          }
                                        ?>
                                        </td>
                                        <td>
                                        <?php 
                                          if($tax['tax_type']==1) {
                                            foreach ($this->purchase as $key => $purchase) {
                                              if($tax['tax_code']==$key) {
                                                echo $purchase['name'];
                                              }
                                            }
                                          } else if($tax['tax_type']==2) {
                                            foreach ($this->supply as $key => $supply) {
                                              if($tax['tax_code']==$key) {
                                                echo $supply['name'];
                                              }
                                            }
                                          } 
                                        ?>
                                        </td>
                                        <td>
                                        <?php 
                                            echo $tax['tax_percentage']." %";
                                        ?>
                                        </td>
                                        <td>
                                        <?php 
                                            echo substr($tax['description'],0,100)." ..";
                                        ?>
                                        </td>
                                        <td>
                                        <?php
                                          if($tax['tax_status']==1) {
                                        ?>
                                        <a href="<?php echo $this->sitePath."settings/tax/set-tax-id/".base64_encode($tax['id'])."/status/2/tax-name/".base64_encode($tax['tax_code']); ?>" data-original-title="Unset Tax" title="Unset Tax"><i class="icon-checkbox-checked"></i></a>
                                        <?php 
                                          } else if($tax['tax_status']==2) {
                                        ?>
                                        <a href="<?php echo $this->sitePath."settings/tax/set-tax-id/".base64_encode($tax['id'])."/status/1/tax-name/".base64_encode($tax['tax_code']); ?>" data-original-title="Set Tax" title="Set Tax"><i class="icon-checkbox-unchecked"></i></a>
                                        <?php 
                                          }
                                        ?>
                                        <a href="<?php echo $this->sitePath."settings/edit-tax/id/".base64_encode($tax['id']); ?>" data-original-title="Edit Tax" title="Edit Tax"><i class="icon-pencil-2"></i></a>
                                            <a href="javascript:void(0)" onclick="deleteTax('<?php echo base64_encode($tax['id']); ?>','<?php echo base64_encode($tax['tax_code']); ?>')" data-original-title="Delete Tax" title="Delete Tax"><i class="icon-remove-2"></i></a>

                                        </td>
                                        </tr>
                                    <?php 
                                        }
                                      } else {
                                    ?>
                                    <tr>
                                    <td colspan="5" align="center" style="text-align:center;"><h5>No Results Found</h5></td>
                                    </tr>

                                    <?php
                                      }
                                    ?>
                                      </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
<script type="text/javascript">
function deleteTax(Idvalue,Name) {
  var confirmMsg = confirm("Are you sure want to delete this tax code? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>settings/tax/delid/'+Idvalue+'/delname/'+Name;
    }
}
</script>